{    
    "msgDadosBancarios":"Enter the bank details",
    "msgEmpresas":"Enter at least one company",
    "msgConcluido":"Successfully completed!",
    "msgLider":"The project team must have a leader.",
    "msgEdicaoNaoEncontrada":"There is a scheduled edition for creating innovation projects.",
    "msgEntrarContatoLean":"If necessary, contact the LEAN area.",
    "msgPedidoAprovacaoExpirou":"The period of this edition project approvals expired.",
    "msgPedidoCriacaoExpirou":"The period of creating this edition projects has expired.",
    "msgEquipe":"Enter team members.",
    "msgSucesso":"Success",
    "msgSenhaAlterada":"Password changed.",
    "msgUsuarioNaoLocalizado": "User not found",
    "msgUsuarioNaoCadastrado": "User not registered with email.",
    "msgAnaliseDasCausas":"Enter at least one cause",
    "msgPlanoDeAcao":"Include at least one action",
    "msgArquivoObrigatorio":"Include at least one attachment",    
    "tituloEmailRecuperacaoSenha": "Password Recovery - Rexam Workflow",
    "tituloEmailResetPassword": "Password reset - Workflow Rexam",
    "tituloEmailBoasVindas": "Welcome to Rexam Workflow",
    "tituloEdicaoNaoEncontrada":"No scheduled edition",
    "tituloPedidoAprovacaoExpirou":"Approval period has expired",
    "tituloPedidoCriacaoExpirou":"Creation period has expired",
    "labelAceite":"Acceptance",
    "labelAceiteFornecedor":"Accept Supplier",
    "labelAcoesCorretivasPreventivas":"Corrective and Preventive Actions",
    "labelAcoesPreventivas":"Preventive Actions",
    "labelAcoesCorretivas":"Corrective Actions",
    "labelAcompanhamentoFornecedor":"Was there monitoring of supplier?",
    "labelAgenteFrete":"Freight agent",
    "labelAplicarReembolso": "Apply re-payment",
    "labelArquivos":"Files",
    "labelBairro":"District",
    "labelCadastro":"Register",
    "labelResponder":"To Answer",
    "labelPerguntaResponder":"Do Answer?",
    "labelCadastroSap":"Register SAP",
    "labelCalculo":"Calculation",
    "labelCalculoReembolsoFinanceiro":"Calculate the Financial Reimbursement",
    "labelCanalDeDistribuicao":"Distribution channel",
    "labelCategoria":"Categories",
    "labelCausaRaiz":"Root cause",
    "labelCentroDeFornecimento":"Supply Center",
    "labelCEP":"Postal Code",
    "labelCidade":"City",
    "labelClasse":"Class",
    "labelCodigoClienteSAP":"SAP Customer Code",
    "labelCodigoFiscal":"Tax Code",
    "labelCodigoFiscalLogin": "Fiscal code",
    "labelCodigoMetal":"Metal Code",
    "labelCodigoProdutoFornecedor":"Supplier's product code",
    "labelCodigoProdutoSAP":"SAP product code",
    "labelCoef":"Coeff. (Kg / m)",
    "labelComentarioRexam":"Aditional comments from Rexam",
    "labelComentarios":"Comments",
    "labelComentariosDaOcorrencia":"Comments occurrence",
    "labelComplementoEndereco":"Complement",
    "labelCondicaoDaExpedicao":"Shipping Conditions",
    "labelCondicaoDePagamento":"Terms of payment",
    "labelContaConciliatoria":"Conciliatory account",
    "labelCriarNOC":"Create NOC",
    "labelCustosDespesas":"Costs / expenses",
    "labelCustosFerramentas":"Tools Costs (US $)",
    "labelDadosContabeis":"Accounting Data",
    "labelDadosFiscais":"Tax data",
    "labelDataAprovacao":"Approval Date",
    "labelDataAbertura":"Opening Date",
    "labelDataAceite":"Date of Acceptance",
    "labelDataEntrada":"Entry Date",
    "labelDataFabricacao":"Date of manufacture",
    "labelDataAutorizacaoDevolucao":"Enter the return authorization date",
    "labelDataFaturamentoFornecedor":"Billing date of the Supplier",
    "labelDataOcorrencia":"Occurrence Date",
    "labelDataRecebimentoMetal": "Metal received date",
    "labelDataResposta":"Answer date",
    "labelDataEncerramento":"Closing date",
    "labelDetalhesOutrasPerdas":"Detail Other losses *",
    "labelDetalhesPerdaFerramenta":"Specify tool loss",
    "labelDetalhesProblema":"Details of the Problem",
    "labelEmailDeCobranca":"E-mail billing",
    "labelEmailEnviado": "E-mail with the password sent to ",
    "labelEmpresa":"Company",
	"labelEmpresas":"Companies",
    "labelEtapa1":"Step 1",
    "labelEtapa2":"Step 2",
    "labelEtapa3":"Step 3",
    "labelEtapa4":"Step 4",
    "labelFisica":"Natural person",
    "labelFormaDePagamento":"Payment method",
    "labelFornecedor":"Supplier",
    "labelGerouDrenoLinha":"Did the deffect genetare drain of line?",
    "labelGerouPerdaProducao":"Did the deffect generate a production loss?",
    "labelGrupoAdmTesouraria":"Cash managment group",
	"labelGrupoDeCliente": "Customer group",
    "labelGrupoDeClientes":"Customer group",
    "labelGrupoDeContas":"Group Accounts",
    "labelGrupoDePreco":"Price group",
    "labelGrupoDeVendedores":"Group of Sellers",
    "labelHistorico":"History",
    "labelHoraDeOcorrencia":"Time of occurrence",
    "labelIncoterm":"Incoterm",
    "labelInformacoesGerais":"General information",
    "labelInscricaoEstadual":"State registration",
    "labelInscricaoMunicipal":"Municipal registration",
    "labelJuridica":"Legal entity",
    "labelKGs":"Wedding in KGs",
    "labelLogradouro":"Adress",
    "labelLote":"Batch",
    "labelMoeda":"Currency",
    "labelMoedaContabilizacao":"Accounting currency",
    "labelMotivoDaSolicitacao":"Reason for request",
    "labelNao":"No",
    "labelNomeCliente":"Customer Name",
    "labelNomeDeBusca":"Search by name",
    "labelNomeEmissorNoc":"Name of the NOC issuer",
    "labelNotaFiscal":"Invoice",
	"labelNovaEmpresa":"New company",
    "labelNovoGrupoClientes":"New code for customer group",
    "labelNovoGrupoPreco":"New code for price group",
    "labelNovoZonaTransporte":"New code for transport zone",
    "labelNumeroCartaoHFI":"No. Of the HFI Card",
    "labelNumeroCliente":"Customer number",
    "labelNumeroEndereco":"Number",
    "labelObservacao":"Observation",
    "labelOrganizacaoDeVendas":"Sales organization",
    "labelOutrasPerdasCustos":"Were there other losses or costs? (ONLY IN CASE OF CRISIS AND AGREED WITH THE HEAD QUARTER)",
    "labelOutrosCustos":"Other Costs (US $)",
    "labelPaisDoCliente":"Customer Country",
    "labelPaisRexam":"Rexam country",
    "labelParecerPrevio":"Preliminary Opinion of Rexam",
    "labelPassoFinanceiro":"Financial step",
    "labelPedidoCorrecao":"Review request",
    "labelPerdaFerramenta":"Was there a tool loss? (ONLY IN CASE OF CRISIS AND AGREED WITH THE HEAD QUARTER)",
    "labelPerdasMetal":"Metal loss (US $)",
    "labelPerdasProducao":"Production Loss (US $)",
    "labelPerdaTotal":"Total loss (US $)",
    "labelPesoReclamada":"Weight Claimed",
    "labelPesoTotalBobina":"Total Weight of the Coils",
    "labelPlacaVeiculo":"Vehicle plate",
    "labelPlanta":"Plant",
    "labelPrecoCompra":"Purchase Price (US $ / ton)",
    "labelPrecoVenda":"Sale Price (US $ / ton)",
    "labelQtdAmostrasEnviadasFornecedor":"Quantity of Samples sent to the supplier",
    "labelQtdProdutosPerdidos":"Amt. Cups (Un.)",
    "labelQtsLatasTampas":"How many Cans or Ends?",
    "labelQuantidadeAmostrasEnviadasFornecedor":"Quantity of Samples sent to the supplier",
    "labelQuantidadeRetida":"Amount retained",
    "labelQuantidadeRetornoFornVenda":"Quant. Returned Supply / Sale",
    "labelRecebedorMercadoria":"Receiving Merchandise",
    "labelRecebedorMercadoriaDiferente":"Consignee of the goods is different for this record?",
    "labelReembolsoToral":"Total Reimburesement (US $)",
    "labelRegiao":"State",
    "labelRegiaoDeVendas":"Sales district",
    "labelResponsavel":"Responsible",
    "labelResposta":"Answer",
    "labelRessarcimento":"Repayment",
    "labelReteste":"Were there retest?",
    "labelRetornoIndicadorRetornoVenda":"Return or Sales Indicator",
    "labelSelecioneStatus":"Select Status",
    "labelSetorDeAtividade":"Business Sector",
    "labelSetorIndustrial":"Industrial Sector",
    "labelSeveridade":"Severity",
    "labelSim":"Yes",
    "labelStatusAprovacao":"Approval status",
    "labelTelefone":"Phone",
    "labelTipoDePessoa":"Type of person",
    "labelTipoDeServico":"Type of service",
    "labelTipoMetal":"Type of Metal",
    "labelTipoProblema":"Type of Problem",
    "labelTituloDefeito":"Deffect",
    "labelUnidadeMedida":"MeasurementUnit",
    "labelUnidadeRetida":"Unit retained as",
    "labelUploadArquivos":"Upload Files",
    "labelValor":"Value US $",
    "labelZonaDeTransporte":"Transportation Zone",
    "labelExDocumentoBancario":"(Ex check Copy; bank statement containing NAME AG and CC)",
    "liAceitar":"Accept",
    "liAnterior":"Previous",
    "liCliente":"Customer",
    "liDevolver":"Return",
    "liProximo":"Next",
    "liRexam":"Rexam",
    "liSalvar":"Save",
    "optionCategoriaMaterialDireto":"Direct material",
    "optionCategoriaMaterialIndireto":"Indirect material",
    "optionCategoriaServicos":"Servicing",
    "optionCategoriaTransporte":"Shipping / Internal movement",
    "optionDevolucao":"Devolution",
    "optionMoedaContabilizacao":"Select the currency of account",
    "optionZonaDeTransporte":"Select a value for the Transport Area field",
    "optionNovoGrupoDeClientes":"New group of customers",
    "optionNovoGrupoDePreco":"New price group",
    "optionSelecioneCategoria":"Select a value for the field category",
    "optionSelecioneCausaRaiz":"Select a value for root cause field",
    "optionSelecioneCentroDeFornecimento":"Enter Central Supply",
    "optionSelecioneClasse":"Select a value for the class field",
    "optionSelecioneClassificacaoFiscal":"Select the tax classification",
    "optionSelecioneCodMetal":"Select a value for the Metal Code field",
    "optionSelecioneCondicaoExpedicao":"Select a value for the field shipping condition",
    "optionSelecioneCondicaoPagamento":"Select a value for the field condition payment",
    "optionSelecioneContaConciliatoria":"Select the conciliatory account",
    "optionSelecioneDefeito":"Select a value for the field defect",
    "optionSelecioneEmpresas":"Select one or more values ​​for the field of business",
    "optionSelecioneFormaDePagamento":"Select a value for the field payment method",
    "optionSelecioneFornecedor":"Select a value for the Supplier field",
    "optionSelecioneGrupoAdmTesouraria":"Select the cash managment group",
    "optionSelecioneGrupoDeContas":"Select a value for the Group Account field",
    "optionSelecioneIncoterm":"Select a value for the field Incoterm",
    "optionSelecioneMoeda":"Select a value for the currency field",
    "optionSelecionePaisCliente":"Select a value for the customer's country",
    "optionSelecionePaisRexam":"Select a value for the Rexam country",
    "optionSelecionePlanta":"Select a value for the Plant field",
    "optionSelecioneProblema":"Select a value for the Problem Type field",
    "optionSelecioneRegiao":"Enter state",
    "optionSelecioneRegiaoDeVendas":"Select a value for the field Sales Region",
    "optionSelecioneSetorIndustrial":"Select the industrial sector",
    "optionSelecioneSeveridade":"Select a value for the severity field",
    "optionSelecioneTipoMetal":"Select a value for the Metal Type field",
    "optionTipoDeServico":"Select the type of service",
	"optionTransportadora":"Select the carrier",
    "optionVenda":"Sale",
    "placeAgenteFrete":"Enter the freight agent",
    "placeBairro":"Enter the district",
    "placeCEP":"Enter Zip Code",
    "placeCidade":"Enter the City",
    "placeCodigoClienteSAP":"Enter the SAP Customer Code",
    "placeCodigoFiscal":"Report the tax code",
    "placeCodigoProdutoFornecedor":"Enter the product code of the supplier",
    "placeCodigoProdutoSAP":"Enter the code from the SAP product",
    "placeComentariosAdicionais":"Report aditional comments",
    "placeComentariosDaOcorrencia":"Enter a review of the occurrence",
    "placeComplemento":"Enter Complement",
    "placeCustoDespesas":"Enter costs / expenses",
    "placeDetalharOutrasPerdas":"Detail costs and other losses",
    "placeDetalharPerdasFerramentas":"Detail loss tools",
    "placeEmail":"Enter the e-mail",
    "placeEmailCobranca":"Enter the email billing",
    "placeEmailNFE":"Enter the email for eletronic invoice",
    "placeIndicadorDevolucaoVendaMetal":"Select a value for the Return or Sales indicator field",
    "placeInformeDescricaoProblema":"Describe the problem",
    "placeInformeDetalhePerdaFerramenta":"Report details of loss of tools",
    "placeInformeLatasTampas":"Report the quantity of cans and / or ends",
    "placeINformeNumHFI":"Report No. of HFI Card",
    "placeInformeNumLote":"Report batch",
    "placeInformePesoReclamada":"Report the complain weight",
    "placeInformePesoTotalBobina":"Report the total weight coil",
    "placeInformeQntAmostrasEnviada":"Report the quantity of samples sent to supplier",
    "placeInformeQntAmostrasRetornadas":"Report the quantity of samples returned by supplier",
    "placeInformeUnidadeMedida":"Select a value for the Measure Unit field",
    "placeInformeValorPerdaFerramenta":"Report the loss tools cost",
    "placeInscricaoEstadual":"Report state registration",
    "placeInscricaoMunicipal":"Enter the municipal registration",
    "placeLogradouro":"Enter Adress",
    "placeMotivoSolicitacao":"Enter reason for the request",
    "placeNomeCliente":"Enter Customer Name",
    "placeNomeDeBusca":"Enter Name Search",
    "placeNotaFiscal":"Enter the invoice",
    "placeNovaZonaDeTransporte":"Enter the new code for transport zone",
    "placeNovoGrupoClientes":"Enter the new code for customer's group",
    "placeNovoGrupoPreco":"Enter the new code for group prices",
    "placeNumero":"Enter the number",
    "placeNumeroCliente":"Customer number",
    "placeObservacao":"Enter some observation",
    "placeParecerPrevio":"Enter preliminary opinion Rexam",
    "placePedidoCorrecao":"Review request",
    "placePlacaVeiculo":"Enter vehicle plate",
    "placeQuantidadeRetida":"Enter the amount retained",
    "placeRecebedorDaMercadoria":"Enter Receiving goods",
    "placeRegiao":"Enter State",
    "placeSelecioneDataEntrada":"Select entry date",
    "placeSelecioneDataFaturamento":"Select billing dete of supplier",
    "placeSelecioneDataOcorrencia":"Select occurence date",
    "placeSolteOsArquivosAqui":"Drop files here ...",
    "placeTelefone":"Enter Phone",
    "placeUnidadeRetida":"Enter the unit of measure on hold",
    "tituloCadastroCLiente":"Client Registration",
    "tituloCriacaoNoc":"NOC Creation",
	"labelEdicaoDeNocCliente":"NOC Edit",
    "validacaoAcompanhamentoFornecedor":"Enter it was monitoring the supplier",
    "validacaoAgenteFrete":"Enter the freight agent",
    "validacaoBairro":"Enter the district",
    "validacaoCartaoHFI":"Enter HFI card number",
    "validacaoCategoria":"Enter category",
    "validacaoCausaRaiz":"Enter the root cause",
    "validacaoCentroDeFornecimento":"Select a value for the field of Supply Center",
    "validacaoCEP":"Enter Zip Code",
    "validacaoCidade":"Enter the City",
    "validacaoClasse":"Enter the class",
    "validacaoCodigoClienteSAP":"Enter the SAP Customer Code",
    "validacaoCodigoFiscal":"Report the tax code",
    "validacaoCodigoMetal":"Enter the code from the metal",
    "validacaoCodigoProdutoFornecedor":"Enter the product code of the supplier",
    "validacaoCodigoProdutoSAP":"Enter the code from the SAP product",
    "validacaoCondicaoDeExpedicao":"Enter the Shipping Condition",
    "validacaoCondicaoDePagamento":"Enter the condition payment",
    "validacaoContaConciliatoria":"Enter the Account Conciliatory",
    "validacaoCustosDespesas":"Enter costs / expenses",
    "validacaoDataEntrada":"Enter the date of entry",
    "validacaoDataFabricacao":"Enter the date of manufacture",
    "validacaoDataFaturamenFornecedor":"Enter the date of the billing provider",
    "validacaoDataOcorrencia":"Enter the date of occurrence",
    "validacaoDcrPerdaFerramenta":"Inform details of tooling loss",
    "validacaoDcrPerdaOutrosCustos":"Enter other details of losses / costs",
    "validacaoDcrProblema":"Notify details of the problem",
    "validacaoDefeito":"Report the bug",
    "validacaoEmail":"Enter the e-mail",
    "validacaoEmailCobranca":"Enter the email billing",
    "validacaoEmailNFE":"Enter the email for eletronic invoice",
    "validacaoEmpresas":"Enter one or more companies",
    "validacaoFormaDePagamento":"Enter payment method",
    "validacaoFornecedor":"Enter the supplier",
    "validacaoGerouDrenoLinha":"Enter the defect generated drain line",
    "validacaoGerouPerdaProducao":"Enter the defect generated production loss",
    "validacaoGrupoClientes":"Enter the customer's group",
    "validacaoGrupoDeContas":"Enter the account group",
    "validacaoGrupoPreco":"Enter the price group",
    "validacaoIncoterm":"Enter Incoterm",
    "validacaoIndicadorDevolucaoVenda":"Enter it had indicator of return or sell the code metal",
    "validacaoInscricaoEstadual":"Report state registration",
    "validacaoInscricaoMunicipal":"Enter the municipal registration",
    "validacaoLogradouro":"Enter Backyard",
    "validacaoLote":"Enter lot",
    "validacaoMoeda":"Enter currency",
    "validacaoMoedaContabilizacao":"Enter the accounting currency",
    "validacaoMotivoDaSolicitacao":"Enter reason for the request",
    "validacaoNomeCliente":"Enter Customer Name",
    "validacaoNomeDeBusca":"Enter Name Search",
    "validacaoNotaFiscal":"Enter the invoice",
    "validacaoNovaZonaDeTransporte":"Enter the new code for transport zone",
    "validacaoNovoGrupoClientes":"New code for customer group",
    "validacaoNovoGrupoPreco":"Enter the new code for group prices",
    "validacaoNumero":"Enter the number",
    "validacaoNumeroCliente":"Enter Customer number",
    "validacaoPaisDaRexam":"Enter the Rexam Country",
    "validacaoPaisDoCliente":"Inform the customer's country",
    "validacaoPedidoCorrecao":"Enter Correction Request",
    "validacaoPerdaFerramenta":"Enter if there was loss tool",
    "validacaoPerdaOutrosCustos":"Enter other losses or other costs if it occurred",
    "validacaoPesoReclamada":"Enter the weight Claimed",
    "validacaoPesoTotalBobina":"Enter the total weight of the coil",
    "validacaoPlacaVeiculo":"Enter vehicle plate",
    "validacaoPlanta":"Enter the plant",
    "validacaoQtdAmostraEnviada":"Enter the qty. Samples sent to the supplier (half-tins or plates)",
    "validacaoQtdAmostraRetorno":"Enter the qty. Return supplier / sell",
    "validacaoQtdDefeitoDrenoLinha":"Enter how many cans and / or covers",
    "validacaoQtdDefeitoPerdaProducao":"Enter how many cans and / or covers",
    "validacaoQuantidadeRetida":"Enter the amount retained",
    "validacaoRecebedorDiferente":"Enter if the recipient of this merchandise is different from this register",
    "validacaoRegiao":"Enter the Region",
    "validacaoRegiãoDeVendas":"Enter the sales district",
    "validacaoReteste":"Enter it occurred retest",
    "validacaoSelecioneClassificacaoFiscal":"Enter the tax classification",
    "validacaoSelecioneGrupoAdmTesouraria":"Enter cash management group",
    "validacaoSelecioneSetorIndustrial":"Industrial sector Enter",
    "validacaoSeveridade":"Enter the severity",
    "validacaoTelefone":"Enter Phone",
    "validacaoTipoDeServico":"Enter the type of service",
    "validacaoTipoMetal":"Enter the type of metal",
    "validacaoTipoProblema":"Enter the type of problem",
    "validacaoUnidadeMedida":"Enter the unit of measure",
    "validacaoUnidadeRetida":"Enter the unit of measure on hold",
    "validacaoValorPerdaFerramenta":"Enter the amount of the loss tool",
    "validacaoValorPerdaOutrosCustos":"Enter the amount of other losses / costs",
    "validacaoZonaDeTransporte":"Enter the transport zone",
    "buttonCancelar":"Cancel",
    "buttonIncluirBanco":"Include Bank",
    "buttonIncluirEmpresa":"Add Company",
    "buttonIncluirMembro":"Add team member",
    "buttonSalvar":"Save",
    "labelAgenciaComDigito":"Agency",
    "labelAguardandoAprovacaoSAP":"Waiting for approval of SAP",
    "labelAguardandoAprovacaoSetorFinanceiro":"Waiting for approval of the financial sector",
    "labelAguardandoCorrecaoClientes":"Waiting for Requester correction",
    "labelAguardandoCorrecaoFornecedor":"Waiting for correction of the Supplier",
    "labelAguardandoSetorDadosContabeis":"Waiting for the financial data industry",
    "labelAguardandoSetorDadosFiscais":"Waiting for the Fiscal Data sector",
    "labelAguardandoSetoresDadosFiscaisDadosContabeis":"Waiting for the sectors of Tax Data and Financial Data",
    "labelAprovacaoFinanceiro":"Approval Financial",
    "labelBanco":"Bank",
    "labelCadastroCancelado":"Registration canceled",
    "labelCadastroConcluido":"Registration completed",
    "labelCadastroFornecedor":"Supplier Registration",
    "labelCartaAutorizacao":"Charter Authorization",
    "labelCBU":"CBU",
    "labelClienteEnvasadoraProdutoAcabado":"Customer Filling / Finished Product?",
    "labelContaCorrenteComDigito":"Current account",
    "labelDadosBancarios":"Bank data",
    "labelDocumentoBancario":"Banking Document",
    "labelIncotermFOB":"FOB?",
    "labelJustificativaCondicaoPagamento":"Justification Payment Condition",
    "labelJustificativaFormaPagamento":"Justification Form Payment",
    "labelNome":"Name",
    "labelNomeSobrenomeContato":"Name / Surname Contact",
    "labelNumeroFornecedorSAP":"Number SAP Supplier",
    "labelOrganizaçãoCompra":"Purchasing Organization",
    "labelOutros":"Other",
    "labelPaisFornecedor":"Supplier of the country",
    "labelRetornarPara":"Return To",
    "labelTipoLogradouro":"Type of Pasture",
    "liAnexos":"Attachments",
    "liFornecedor":"Supplier",
    "optionContabilidade":"Accounting",
    "optionFinanceiro":"Financial",
    "optionOrganizacaoCompra":"Select the buying organization",
    "optionPaisFornecedor":"Select the country of the supplier",
    "optionSelecioneBanco":"Select one or more banks",
    "optionSelecioneMoeda":"Select the currency",
    "optionSelecioneOndeDeveRetornar":"Select where to return",
    "optionSolicitante":"Applicant",
    "optionTipoLogradouro":"Select the type of Backyard",
    "placeAgenciaComDigito":"Agency",
    "placeCBU":"CBU",
    "placeContaCorrenteComDigito":"Current account",
    "placeJustificativaCondicaoPagamento":"Justification Payment Condition",
    "placeJustificativaFormaPagamento":"Justification Form Payment",
    "placeNome":"Name",
    "placeNomeSobrenomeContato":"Name / Surname Contact",
    "placeNumeroFornecedorSAP":"Number SAP Supplier",
    "thAgencia":"Agency",
    "thBanco":"Bank",
    "thCBU":"CBU",
    "thContaCorrente":"Current Account",
    "thEmpresa":"Company",
    "thOrganizacaoCompras":"Purchasing Organization",
    "tituloNovaEmpresa":"New Company",
    "tituloNovoBanco":"New Bank",
    "validacaoAgenciaComDigito":"Inform Agency (with digit)",
    "validacaoContaCorrenteComDigito":"Enter the Current account (with digit)",
    "validacaoIncotermFOB":"Incoterm FOB",
    "validacaoJustificativaCondicaoPagamento":"Enter Rationale Condition Payment",
    "validacaoJustificativaFormaPagamento":"Enter Justification Form Payment",
    "validacaoNome":"Enter Name",
    "validacaoNumeroFornecedorSAP":"Enter SAP Supplier Number",
    "validacaoOrganizacaoCompra":"Enter the purchasing organization",
    "validacaoPaisFornecedor":"Enter the country of the supplier",
    "validacaoRetornarPara":"InformeRetornarPara",
    "validacaoSelecioneArquivoCodigoFiscal":"Select a file type Tax Code",
    "validacaoSelecioneArquivoTipoCartaAutorizacao":"Select a file type Charter Authorization",
    "validacaoSelecioneArquivoTipoDocumentoBancario":"Select a file type Banking Document",
    "validacaoSelecioneArquivoTipoInscricaoEstadual":"Select a State Registration file type",
    "validacaoSelecioneArquivoTipoInscricaoMunicipal":"Select a type Municipal Description file",
    "validacaoSelecioneBanco":"Enter one or more banks",
    "validacaoSelecioneEmpresa":"Enter a company",
    "validacaoSelecioneMoeda":"Enter the Currency",
    "validacaoTipoLogradouro":"Enter the type Backyard",
    "validaNomeSobrenomeContato":"Enter Name / Contact Last Name",
    "labelMaterial":"Material",
    "labelCodigoDoMaterialNoSAP":"Material ID in SAP",
    "placeCodigoDoMaterialNoSAP":"Material ID in SAP",
    "validacaoCodigoDoMaterialNoSAP":"Enter the Material ID in SAP",
    "labelDevolverPara":"Returning To",
    "labelSuprimentos":"Supplies",
    "optionSuprimentos":"Supplies",
    "optionFiscal":"Tax",
    "optionContabil":"Accounting",
    "optionEngenharia":"Engineering",
    "labelClasseAvaliacao":"Class Rating",
    "placeClasseAvaliacao":"Class Rating",
    "validacaoClasseAvaliacao":"Report to Class Rating",
    "labelModeloMaterial":"Material Model",
    "optionSelecioneAPlanta":"Select Plant",
    "labelDescricaoCurta":"Short Description",
    "placeDescricaoCurta":"Short Description",
    "validacaoDescricaoCurta":"Enter the Short Description",
    "optionUnidadeMedida":"Unit of measurement",
    "labelGrupoMercadoria":"Merchandise Group",
    "optionGrupoMercadoria":"Select the Merchandise Group",
    "validacaoGrupoMercadoria":"Enter Merchandise Group",
    "labelDescricaoLonga":"Long Description",
    "placeDescricaoLonga":"Long Description",
    "validacaoDescricaoLonga":"Enter the Long List",
    "labelDescricaoImportada":"Description Imported",
    "placeDescricaoImportada":"Description Imported",
    "labelOrigemMaterial":"Source Material",
    "optionOrigemMaterial":"Select the Source Material",
    "validacaoOrigemMaterial":"Enter the Source Material",
    "labelEngenharia":"Engineering",
    "labelFerramentaIntermutavel":"Interchangeable Tool",
    "labelItemCritico":"Critical Item",
    "labelItemRecuperavel":"Recoverable Item",
    "labelDeposito":"Deposit",
    "optionDeposito":"Select the deposit",
    "validacaoDeposito":"Enter the deposit",
    "labelFuncaoMaterial":"Material Function",
    "optionFuncaoMaterial":"Material Function",
    "placeUtilizacaoEquipamento":"Using the equipment",
    "optionUtilizacaoEquipamento":"Select the use of the equipment",
    "validacaoUtilizacaoEquipamento":"Enter the use of the equipment",
    "labelEquipamento":"Equipment",
    "optionEquipamento":"Select the equipment",
    "validacaoEquipamento":"Enter the Machine",
    "labelFabricanteReferencia":"Manufacturer / Reference",
    "placeFabricanteReferencia":"Manufacturer / Reference",
    "validacaoFabricanteReferencia":"Enter Manufacturer / Reference",
    "labelEstoqueMinimo":"Minimum stock",
    "placeEstoqueMinimo":"Minimum stock",
    "validacaoEstoqueMinimo":"Enter Minimum stock",
    "labelEstoqueMaximo":"Max Out",
    "placeEstoqueMaximo":"Max Out",
    "validacaoEstoqueMaximo":"Inform the Most Out",
    "placeTipoMRP":"MRP type",
    "optionTipoMRP":"Select the MRP type",
    "validacaoTipoMRP":"Enter the MRP type",
    "placePlanejadorMRP":"MRP Planner",
    "optionPlanejadorMRP":"Select the MRP Planner",
    "validacaoPlanejadorMRP":"Enter the MRP Planner",
    "placeTamanhoDoLoteMRP":"Lot size MRP",
    "optionTamanhoDoLoteMRP":"Select Lot size MRP",
    "validacaoTamanhoDoLoteMRP":"Enter Lot size MRP",
    "labelTipoDeFert":"Type FERT",
    "labelLata":"Tin",
    "labelampa":"Cover",
    "labelDeixarVersaoBloqueadoEmZ1":"Leave Version blocked in Z1?",
    "labelDeixarVersaoBloqueadoEm03":"Leave blocked in version 03?",
    "labelQuantidadeLatasPorCamada":"Cans Amount Per Layer",
    "placeQuantidadeLatasPorCamada":"Cans Amount Per Layer",
    "validacaoQuantidadeLatasPorCamada":"Enter the cans Amount Per Layer",
    "labelTipoDeLata":"Tin Type",
    "placeTipoDeLata":"Tin Type",
    "validacaoTipoDeLata":"Enter the Tin Type",
    "labelObservacoes":"Observations",
    "placeObservacoes":"Observations",
    "labelInformacoesListaTecnica":"Technical Information Bill",
    "labelNovaInformacaoListaTecnica":"New Technical Information List",
    "labelQuantidade":"Quantity",
    "placeQuantidade":"Quantity",
    "validacaoQuantidade":"Enter the Quantity",
    "labelProduto":"Product",
    "placeProduto":"Product",
    "validacaoProduto":"Enter the product",
    "labelCodigo":"Code",
    "placeCodigo":"Code",
    "validacaoCodigo":"Enter the code",
    "labelFiscal":"Tax",
    "optionSelecioneCategoriaCFOP":"Select the category CFOP",
    "labelCategoriaCFOP":"Category CFOP",
    "validacaoCategoriaCFOP":"Enter the CFOP category",
    "labelClassificacaoFiscal":"Tax rate",
    "labelUtilizacaoDoMaterial":"Using the Media",
    "placeUtilizacaoDoMaterial":"Using the Media",
    "validacaoUtilizacaoDoMaterial":"ValidacaoUtilização Material",
    "labelLabEsc":"Lab./escr.",
    "optionLabEsc":"Select the LAB. / ESC.",
    "validacaoLabEsc":"Enter the LAB. / ESC.",
    "labelCentroDeLucro":"Profit Center",
    "optionCentroDeLucro":"Select the Profit Center",
    "validacaCentroDeLucro":"Enter Profit Center",
    "labelDepositoDeProducao":"Production Depot",
    "optionDepositoDeProducao":"Select the Production Depot",
    "validacaoDepositoDeProducao":"Enter Production Depot",
    "labelGrupoMRP":"MRP Group",
    "optionGrupoMRP":"Select the MRP Group",
    "validacaoGrupoMRP":"Enter the MRP Group",
    "labelAguardandoCorrecaoCadastro":"Waiting for correction in the register",
    "labelAguardandoSetorSuprimentos":"Waiting supplies industry",
    "labelAguardandoSetoresFiscalEContabil":"Waiting for tax and accounting sectors",
    "labelAguardandoSetorFiscal":"Waiting for fiscal sector",
    "labelAguardandoSetorContabil":"Waiting accounting industry",
    "labelAguardandoSetorEngenharia":"Waiting engineering sector",
    "labelPesoBruto":"Gross Weight",
    "placePesoBruto":"Gross Weight",
    "validacaoPesoBruto":"Enter Weight",
    "labelPesoLiquido":"Net Weight",
    "placePesoLiquido":"Net Weight",
    "validacaoPesoLiquido":"Enter Net Weight",
    "labelTipoDeMaterial":"Material Type",
    "labelCodigoDoMaterial":"Material ID",
    "labelAplicacaoDoEquipamento":"Application equipment",
    "optionAplicacaoDoEquipamento":"Select Device Application",
    "validacaoAplicacaoDoEquipamento":"Enter the Device Application",
    "labelPartNumber":"Part Number",
    "placePartNumber":"Part Number",
    "validacaoPartNumber":"Enter the Part Number",
    "labelQuantidadeLatasTampasPorPalete":"Number of cans / Covers For Pallet",
    "placeQuantidadeLatasTampasPorPalete":"Number of cans / Covers For Pallet",
    "validacaoQuantidadeLatasTampasPorPalete":"Enter the cans Quantity / Pallet Covers For",
    "labelCadastroDeMaterial":"Registration Material",
    "labelCustoMaterial":"Cost Material",
    "placeCustoMaterial":"Cost Material",
    "validacaoCustoMaterial":"Enter Cost Material",
    "labelCodigoNCM":"NCM code",
    "placeCodigoNCM":"NCM code",
    "validacaoCodigoNCM":"Enter NCM code",
    "validacaoAcoesCorretivas":"Enter corrective actions",
    "validacaoAcoesPreventivas":"Enter preventive actions",
    "validacaoParecer":"Inform the Conclusion",
    "labelAguardandoAceite":"Waiting agreement",
    "labelAguardandoResposta":"Waiting Answer",
    "labelAguardandoRespostaEspecialistaLean":"Waiting Lean Specialist Response",
    "labelAguardandoRespostaGerente":"Waiting Manager Response",
    "labelAguardandoRespostaLiderLean":"Waiting Lean Leader Response",
    "labelAguardandoRespostaSuperiorImediato":"Waiting Supervisor Response",
    "labelAlocacaoDeRecursosDeficienteFaltaDeRecursos":"Resources not Enough / Lack of Resources",
    "labelAlto":"High",
    "labelAnaliseDoProblemaESuasCausas":"Root cause analysis",
    "labelAnaliseDosPorques":"Five Why Analysis",
    "labelAnalisePriorizacaoSeAplicavel":"Priorization Analysis (if applicable)",
    "labelAntesDaInovacao":"Before Innovation (can / ends by minutes)",
    "labelApprover":"Approver",
    "labelAprovacao":"Approval",
    "labelAprovar":"Approve",
    "labelARexamNaoTeraQueDesembolsarValoresParaATransportadora":"Rexam is not responsible to refund the transportation supplier",
    "labelAtuaSobreGargalo":"Action on Bottleneck",
    "labelBaixo":"Low",
    "labelCancelada":"Cancelled",
    "labelCargo":"Job Title",
    "labelCategorizacao":"Categorization",
    "labelCausa":"Cause",
    "labelCausas":"Causes",
    "labelCliente":"Customer",
    "labelClienteCadastro":"Customer Registration",
    "labelCodigoDoProduto":"Product Code",
    "labelComentariosDoCliente":"Customer Comments",
    "labelConcluida":"Finished",
    "labelConclusao":"Finish",
    "labelCondicoesAmbientaisOuClimaticas":"Environmental or climatic conditions",
    "labelCondicoesDoAmbienteDeTrabalhoInadequadas":"Inappropriate job conditions",
    "labelContencao":"Containment Action – Immediate action defining what to do with the affected lot and/or suspect",
    "labelConteudoInadequado":"Inappropriate content",
    "labelControlesAdministrativosAusentesOuInadequados":"Absent or Inadequate management controls",
    "labelCriacaoDeNocCliente":"Customer NOC Creation",
    "labelCriacaoDeProjetoInovacao":"Innovation Project Creation",
    "labelCriacaoNocFornecedor":"Create NOC Supplier",
    "labelDadosDeAtendimentoReclamação":"Data service the complaint",
    "labelDataAutorizacaoDevolucao":"Date of Return Authorization",
    "labelDataAutorizacaoRessarcimento":"Date of payment approval",
    "labelDataChegadaDoLoteDevoldidoAFabrica":"Date of incoming product returned",
    "labelDataDeAprovacaoPeloEspecialistaLean":"Date of Lean Specialist Approval",
    "labelDataDeAprovacaoPeloGerente":"Date of Manager Approval ",
    "labelDataDeAprovacaoPeloSuperiorImediato":"Date of Supervisor Approval",
    "labelDataDeAprovaçãoPeloLiderLean":"Approval Date by Lean Leader",
    "labelDataimplantacaoDoProjeto":"Date of implementation of project",
    "labelDeficienciaNaOrganizaçãoELimpezaDaArea":"Disability in organizing and cleaning the area",
    "labelDefinicaoDoProblema":"Problem definition",
    "labelDepartamento":"Department",
    "labelDepoisDaInovacao":"After Innovation (can / ends by minutes)",
    "labelDescricaoDoProjeto":"Project Description",
    "labelDesperdicioAnoAntesDaInovacao":"Waste year (US $, Before Innovation)",
    "labelDesperdicioAnoDepoisDaInovacao":"Waste year (US $, After Innovation)",
    "labelDesperdicioMesAntesDaInovacao":"Waste Month (US $, Before Innovation)",
    "labelDesperdicioMesDepoisDaInovacao":"Waste Month (US $, After Innovation)",
    "labelDesvioDeProcedimentoOuRequisito":"Procedure or Requirement Deviation",
    "labelDevolucao":"Return?",
    "labelDispatch":"Dispatch",
    "labelEconomiaGeradaPorAno":"Savings generated per year (US $)",
    "labelEconomiaGeradaPorMes":"Savings generated by Month (US $)",
    "labelEmailParaNotificacoes":"E-mail for notifications",
    "labelEmAprovacao":"In progress - Appoval step",
    "labelEmRevisaoDeResposta":"Answer Revision",
    "labelEquipamentoMaterial":"Equipment / Material",
    "labelEquipamentoQueFalhou":"Equipment that failed",
    "labelEquipeDoProjeto":"Project Team",
    "labelErroEmDesenhosEspecificacoesOuDados":"Error on Drawings, specifications or data",
    "labelEspecialistaLean":"Lean Specialist",
    "labelEspecialistaLeanQueAprovou":"Approved by Lean Specialist",
    "labelEspecificacaoDeMaterialOuDeEquipamentoInadequada":"Inadequate specification of material or equipment",
    "labelEsteProjetoEstaSendoImportadoDeOutraUnidade":"This project is being imported from another unit?",
    "labelEstimativaDoCustoDaReclamacaoAtendimento":"Cost Estimate of the Complaint Attendance Service",
    "labelEstimativaDoCustoDaReclamacaoOutros":"Cost Estimate of the Complaint / Others",
    "labelFabrica":"Plant",
    "labelFabricaDevolucao":"Product Return from Plant",
    "labelFalhaDoFornecedorDoEquipamentoOuMaterial":"Failure of equipment or materials supplier",
    "labelFalhaNaComunicacaoInternaVerbalOuOutros":"Failure of internal communication (verbal / others)",
    "labelFalhaNosMecanismosDeDeteccaoDeFalhas":"Failure on Defect Detection Process",
    "labelFaltaDeAtencaoAosDetalhes":"Lack of detail atention",
    "labelFaltaDeProcedimento":"Lack of Procedure",
    "labelFaltaDeReciclagemPeriodica":"Lack of periodic training",
    "labelFenomenosExternos":"External Phenomena",
    "labelFornecedorCadastro":"Suppiler Data",
	"labelTransportadora":"Carrier",
    "labelGanhosMensurados":"Measurable gains",
    "labelGanhosNaoMensurados":"Results Achieved",
    "labelGanhosObtidos":"Gains",
    "labelGerente":"Manager",
    "labelGerenteQueAprovou":"Approved by Manager",
    "labelGestao":"Management",
    "labelGrupoClassificacaoContabil":"Group Accounting Rate",
    "labelHoraDeFabricacao":"Time of production",
    "labelHouveRiscosEliminadosPeloPeojeto":"Has Risks eliminated by the project?",
    "labelInadequadaSupervisao":"Inadequate supervision",
    "labelIncendioOuExplosaoExterna":"Fire or external explosion",
    "labelInformarLiderDoProjeto":"Notify project leader",
    "labelInformeUmaResposta":"Inform the answer",
    "labelInfraestrutura":"Infrastructure",
    "labelInovacaoAprovacaoDoSuperiorImediato":"Inovation - Supervisor Approval",
    "labelInovacaoAprovacaoEspecialistaLean":"Inovation - Lean Specialist Approval",
    "labelInovacaoAprovacaoGerente":"Inovation - Manager Approval",
    "labelInovacaoAprovacaoLiderLean":"Inovation - Lean Leader Approval",
    "labelInovacaoCadastro":"Date of Supervisor Approval",
    "labelInovacaoHistorico":"Inovation - Historic Data",
    "labelInstalacoesInadequadas":"Inadequate Facilities",
    "labelInterfaceHomemMaquinaInadequadas":"Inadequate Man-Machine Interface",
    "labelInvestimentoDoProjeto":"The Project investment",
    "labelJustificativaDaReprovacao":"Justification of disapproval",
    "labelJustificativaReprovacao":"Justification of disapproval",
    "labelLider":"Leader",
    "labelLiderLean":"Lean Leader",
    "labelLiderLeanQueAprovou":"Lean Leader who approved",
    "labelManutencaoDasInstalacoesAusenteOuInadequada":"Missing or Inadequate Facilities Maintenance",
    "labelMapaCausaRaiz":"Root cause map",
    "labelmaterialDefeituoso":"Deficiency of material",
    "labelMaterialDeSuporteInadequado":"Inadequate support material",
    "labelMatricula":"Register",
    "labelMedio":"Average",
    "labelMetodologiaInadequada":"Inadequate methodology",
    "labelMotivoCorrecao":"Reason of correction",
    "labelNaoFoiFornecidoOTreinamento":"No training was provided",
    "labelNocCliente":"Customer NOC",
    "labelNocInformativa":"Just informed NOC?",
    "labelNomeDoParticipante":"Name of Participant",
    "labelNomeDoProjeto":"Name of project",
    "labelNotasRelevantes":"Relevant Notes",
    "labelNovaCausa":"New cause",
    "labelNovaPlanta":"New Plant",
    "labelOrganizacaoDoTrabalhoInadequada":"Inadequate work organization",
    "labelOutrasEconomiasMensais":"Saving generated (in Reais, not linked with loss of can or ends).",
    "labelOutrosFatoresHumanos":"Other human factors",
    "labelOutroTipoDeDocumento":"Other Document Type",
    "labelParecer":"Conclusion",
    "labelParecerDaAreaExterno":"Conclusion (external)",
    "labelParecerDaAreaInterno":"Conclusion (internal)",
    "labelPessoal":"Staff",
    "labelPlanejamentoDoTrabalhoInadequado":"Inadequate Work Planning",
    "labelPlantas":"Plants",
    "labelPoliticaNaoAdequadamenteDefinidaDisseminadaOuRreforcada":"Policy not properly defined, disseminated or enhanced",
    "labelPontosInovação":"Innovation Points",
    "labelPontosMelhoria":"Improvement Points",
    "labelPorQue1":"Why 1",
    "labelPorQue2":"Why 2",
    "labelPorQue3":"Why 3",
    "labelPorQue4":"Why 4",
    "labelPorQue5":"Why 5",
    "labelPraticaInsuficienteDuranteOTreinamento":"Insufficient practice During training",
    "labelPrensaMatriz":"Machine Line Number or Matrix / Position Number",
    "labelProcedimento":"Procedure",
    "labelProcedimentoNaoClaroAmbiguoOuIncompleto":"Unclear procedure, ambiguous or incomplete",
    "labelProjeto":"Project",
    "labelProjetoAprovado":"Approval project",
    "labelProjetoDesenvolvidoNaUnidade":"Project developed in unit",
    "labelProjetoReprovado":"Failed project",
    "labelProjetos":"Projects",
    "labelQual":"Which One?",
    "labelQuantidadeASerRessarcidaEmLata":"Amount to be payment - Number of Cans",
    "labelQuantidadeASerRessarcidaEmTampa":"Amount to be payment - Number of Ends",
    "labelQuantidadeAutorizadaDevolver":"Quantity authorized to return",
    "labelQuantidadeDeAprovados":"Number of approved",
    "labelQuantidadeDeExpirados":"Number of expired",
    "labelQuantidadeDeInscritos":"Number of registered",
    "labelQuantidadeDeReprovados":"Number of rejected",
    "labelQuantidadeDevolvida":"Quantity returned",
    "labelQuantidadeemAprovacao":"Quantity in Approval step",
    "labelQuantidadeLatasTampasPerdidas":"Quantity of can / end lost",
    "labelRelatorioDeParticipantes":"Participants report",
    "labelRepostaDoFornecedor":"Supplier answer",
    "labelReprovar":"Disapprove",
    "labelPerguntaResponder":"To answer?",
    "labelRespostaRexam":"Rexam answer",
    "labelRouboAssaltoVandalismo":"Theft, assault, vandalism",
    "labelSelecioneAnaliseDePriorizacao":"Select the prioritization analysis",
    "labelSeuProjetoEstaVinculadoPerdaDeLatasTampas":"Is there your project linked to loss cans / end?",
    "labelSolicitarCorrecao":"Request correction",
    "labelSolucoesImplementadas":"Implemented solutions",
    "labelSuperiorImediato":"Supervisor",
    "labelSuperiorImediatoQueQprovou":"Supervisor who approved",
    "labelSupervisorResponsavel":"Supervisor responsible",
    "labelSuprimentoDeEnergiaOuAguaInadequados":"Power or water supply Inadequate",
    "labelTipoDeDocumento":"Document Type",
    "labelTipodeProjeto":"Type of project",
    "labelTotalDeCreditos":"Total of Points",
    "labelTraducaoDoFato":"Translation of occurrence",
    "labelTreinamento":"Training",
    "labelTurma":"Group / Team / Company",
    "labelUnidade":"Unit",
    "labelUnidadeDoParticipante":"Unit of participant",
    "labelUnidadeDoProjeto":"Unit of project",
    "labelUnidadesPerdidasPorAnoAntesDaInovacao":"Units lost per year (Before Innovation)",
    "labelUnidadesPerdidasPorAnoDepoisDaInovacao":"Units lost per year (After Innovation)",
    "labelUnidadesPerdidasPorMesAntesDaInovacao":"Units lost by Month (Before Innovation)",
    "labelUnidadesPerdidasPorMesDepoisDaInovacao":"Units lost by Month (After Innovation)",
    "labelValorDaLataTampa":"Value of can / end",
    "labelValorDoFrete":"Shipping Fee",
    "labelValorInovacao":"Innovation Value",
    "labelValorMelhoria":"Improvement Value",
    "labelValorTotal":"Total Value",
    "optionCliente":"Select Customer",
    "optionFabrica":"Select the factory",
    "optionInovacao":"Innovation",
    "optionMelhoria":"Improvement",
    "optionProjeto":"Report the project",
    "optionResposta":"Answer",
    "optionSelecioneACausaRaiz":"Select Root Cause",
    "optionSelecioneAEtapaParaQualDesejaDevolver":"Select the step to Which to return (previous step)",
    "optionSelecioneATurma":"Select team",
    "optionSelecioneFabricaDevolucao":"Select the Plant to return",
    "optionSelecioneParecer":"Select the option According the attendance",
    "optionSelecioneTipoDeProjeto":"Select type of project",
    "optionSupervisorResponsavel":"Select surpervisor",
    "optionTipoDeDocumento":"Select typr of document",
    "optionUnidadeDoParticipante":"Select unit of Participant",
    "optionUnidadeOndeProjetoFoiDesenvolvido":"Select the unit that the project came from",
    "placeAnaliseDoProblemaESuasCausas":"Root cause analysis",
    "placeAntesDaInovacao":"Before Innovation Project Implementation",
    "placeCausa":"Cause",
    "placeCodigoDoProduto":"Product Code",
    "placeComentarios":"Comments",
    "placeComentariosDoCliente":"Customer Comments",
    "placeConclusao":"Finish",
    "placeContencao":"Containment Action – Immediate action defining what to do with the affected lot and/or suspect",
    "placeDadosDeAtendimentoReclamação":"Data service the complaint",
    "placeDefinicaoDoProblema":"Definition of the problem",
    "placeDepoisDaInovacao":"After Innovation (cans / caps per minute)",
    "placeEmailParaNotificacoes":"Enter with the email for notifications",
    "placeEstimativaDoCustoDaReclamacaoAtendimento":"Cost estimation for assistance claim",
    "placeEstimativaDoCustoDaReclamacaoOutros":"Cost estimation for claim / others",
    "placeGanhosNaoMensurados":"Enter with results Achieved",
    "placeGrupoClassificacaoContabil":"Select the group accounting rate",
    "placeHoraDeFabricacao":"Manufacture of Time",
    "placeInformeJustificativaDeReprovacao":"Enter with justification for failure",
    "placeInvestimentoDoProjeto":"Investment of the project (in Reais)",
    "placeMotivoCorrecao":"Inform reason of correction",
    "placeNomeDoProjeto":"Enter with name of project",
    "placeNotasRelevantes":"Relevant Notes",
    "placeOutrasEconomiasMensais":"Enter with saving generated monthly (in Reais, not tied to loss of cans or lids)",
    "placeOutroTipoDeDocumento":"Other Document Type",
    "placeParecerDaAreaExterno":"Conclusion (external)",
    "placeParecerDaAreaInterno":"Conclusion (internal)",
    "placePorQue1":"Why 1",
    "placePorQue2":"Why 2",
    "placePorQue3":"Why 3",
    "placePorQue4":"Why 4",
    "placePorQue5":"Why 5",
    "placePrensaMatriz":"Machine Line Number or Matrix / Position Number",
    "placeQual":"Which One?",
    "placeQuantidadeASerRessarcidaEmLata":"Amount to be payment - Number of Cans",
    "placeQuantidadeASerRessarcidaEmTampa":"Amount to be payment - Number of Ends",
    "placeQuantidadeAutorizadaDevolver":"Quantity authorized to return",
    "placeQuantidadeDevolvida":"Quantity returned",
    "placeQuantidadeLatasTampasPerdidas":"Quantity of can / end loss",
    "placeSolucoesImplementadas":"Implemented solutions",
    "placeTraducaoDoFato":"Translation of occurrence",
    "placeTurma":"Crew",
    "placeUnidadeDoProjeto":"Enter with unit of the project",
    "placeValorDoFrete":"Shipping Fee",
    "tituloEquipeDoProjeto":"Project Team",
    "validacaoAlocacaoDeRecursosDeficienteFaltaDeRecursos":"Inform if there where  Resources not Enough / Lack of Resources",
    "validacaoAnaliseDoProblemaESuasCausas":"Report of Root cause analysis",
    "validacaoCausa":"Inform the Cause",
    "validacaoCliente":"Inform the Customer",
    "validacaoClienteEnvasadoraProdutoAcabado":"Beverage Company / Finished Product?",
    "validacaoComentariosDoCliente":"Inform the Customer Comments",
    "validacaoConclusao":"Inform Conclusion",
    "validacaoCondicoesAmbientaisOuClimaticas":"Inform the Environmental or climatic conditions",
    "validacaoCondicoesDoAmbienteDeTrabalhoInadequadas":"Inform if there where Inappropriate job conditions",
    "validacaoConteudoInadequado":"Inform if there was inappropriate content",
    "validacaoControlesAdministrativosAusentesOuInadequados":"Inform if There Were missing or inappropriate administrative controls",
    "validacaoDadosDeAtendimentoReclamação":"Enter care data the complaint",
    "validacaoDataAutorizacaoRessarcimento":"Enter the date authorization reimbursement",
    "validacaoDataChegadaDoLoteDevoldidoAFabrica":"Inform the date of incoming product returned",
    "validacaoDataimplantacaoDoProjeto":"Inform the date of implementation of project",
    "validacaoDeficienciaNaOrganizaçãoELimpezaDaArea":"Please state whether there was deficiency in organizing and cleaning the area",
    "validacaoDefinicaoDoProblema":"Enter the definition of the problem",
    "validacaoDesvioDeProcedimentoOuRequisito":"Inform if there was Procedure or Requirement Deviation",
    "validacaoDevolucao":"Inform if it is return",
    "validacaoEmailParaNotificacoes":"Inform e-mail for notifications",
    "validacaoEquipamentoQueFalhou":"Inform if Equipment that failed",
    "validacaoErroEmDesenhosEspecificacoesOuDados":"Inform if there was Error on Drawings, specifications or data",
    "validacaoEspecificacaoDeMaterialOuDeEquipamentoInadequada":"Inform if there were missing or inappropriate Material Specification / Equipment",
    "validacaoEsteProjetoEstaSendoImportadoDeOutraUnidade":"Report if the project is been exported from another unit",
    "validacaoEstimativaDoCustoDaReclamacaoAtendimento":"Inform the Cost estimation for assistance claim",
    "validacaoEstimativaDoCustoDaReclamacaoOutros":"Inform the Cost estimation for claim / others",
    "validacaoEtapaParaQualDesejaDevolver":"Inform the step to Which to return (previous step)",
    "validacaoFabrica":"Inform the factory",
    "validacaoFabricaDevolucao":"Inform the Plant to return",
    "validacaoFalhaDoFornecedorDoEquipamentoOuMaterial":"Inform if there was Failure of equipment or materials supplier",
    "validacaoFalhaNaComunicacaoInternaVerbalOuOutros":"Inform if there was Failure of internal communication (verbal / others)",
    "validacaoFalhaNosMecanismosDeDetecçãoDeFalhas":"Please state whether there was failure in the Fault Detection Mechanisms",
    "validacaoFaltaDeAtencaoAosDetalhes":"Inform if there was Lack of detail atention",
    "validacaoFaltaDeProcedimento":"Inform if there was Lack of Procedure",
    "validacaoFaltaDeReciclagemPeriodica":"Inform if there was Lack of periodic training",
    "validacaoGanhosNaoMensurados":"Report results Achieved",
    "validacaoGrupoClassificacaoContabil":"Please Group Accounting Rate",
    "validacaoHoraDeFabricacao":"Inform the time of production",
    "validacaoHoraDeOcorrencia":"Inform the time of ocurrence",
    "validacaoInadequadaSupervisao":"Inform if there was inappropriate management",
    "validacaoIncendioOuExplosaoExterna":"Inform if there was fire or external explosion",
    "validacaoInformeAEtapaParaQualDesejaDevolver":"Enter the step to which to return",
    "validacaoInformeCategoria":"Inform category",
    "validacaoInformeJustificativaDeReprovacao":"Enter the justification of Fail",
    "validacaoInformeSeDesejaAprovar":"Tell whether to approve the project",
    "validacaoInstalacoesInadequadas":"Inform if there where Inadequate Facilities",
    "validacaoInterfaceHomemMaquinaInadequadas":"Inadequate Man-Machine Interface",
    "validacaoInvestimentoDoProjeto":"Enter the Project Investment (in Reais)",
    "validacaoManutencaoDasInstalacoesAusenteOuInadequada":"Inform if there where Missing or Inadequate Facilities Maintenance",
    "validacaoMaterialDefeituoso":"Inform if there was deficiency of material",
    "validacaoMaterialDeSuporteInadequado":"Inform if there was Inadequate support material",
    "validacaoMetodologiaInadequada":"Inform if there was Inadequate methodology",
    "validacaoMotivoCorrecao":"Inform correction reason",
    "validacaoNaoExistemDadosCadastrados":"There are actually no data",
    "validacaoNaoFoiFornecidoOTreinamento":"Inform if training was not provided",
    "validacaonidadeDoProjeto":"Enter the unit of the project",
    "validacaoNomeDoProjeto":"Enter with name of the project",
    "validacaoOrganizacaoDoTrabalhoInadequada":"Inform if there was Inadequate work organization",
    "validacaoOutrasEconomiasMensais":"Report saving generated monthly (in Reais, not tied to loss of cans or lids)",
    "validacaoOutrosFatoresHumanos":"Inform if There Were other human factors",
    "validacaoOutroTipoDeDocumento":"Inform Other Document Type",
    "validacaoParecerDaAreaExterno":"Inform the Conclusion (external)",
    "validacaoParticipante":"Select the participant",
    "validacaoPerdaAntesDaInovacao":"Report loss before innovation (cans / caps per minute)",
    "validacaoPerdaDepoisDaInovacao":"Report loss after innovation (cans / caps per minute)",
    "validacaoPlanejamentoDoTrabalhoInadequado":"Inform if there was Inadequate Work Planning",
    "validacaoPoliticaNaoAdequadamenteDefinidaDisseminadaOuRreforcada":"Inform if the Policy was not properly defined, disseminated or enhanced",
    "validacaoPorQue1":"Inform - Why 1",
    "validacaoPorQue2":"Inform - Why 2",
    "validacaoPorQue3":"Inform - Why 3",
    "validacaoPraticaInsuficienteDuranteOTreinamento":"Inform if there was insufficient practice During training",
    "validacaoPrensaMatriz":"Inform the Machine Line Number or Matrix / Position Number",
    "validacaoProcedimentoNaoClaroAmbiguoOuIncompleto":"Inform if there was Unclear procedure, ambiguous or incomplete",
    "validacaoProjeto":"Report the project",
    "validacaoQual":"Report Witch one?",
    "validacaoQuantidadeASerRessarcidaEmLata":"Inform the amount to be payment - Number of Cans",
    "validacaoQuantidadeASerRessarcidaEmTampa":"Inform the amount to be payment - Number of Ends",
    "validacaoQuantidadeAutorizadaDevolver":"Inform the quantity authorized to return",
    "validacaoQuantidadeDevolvida":"Inform the quantity returned",
    "validacaoResposta":"Inform an answer",
    "validacaoRessarcimento":"Have Reimbursement?",
    "validacaoRouboAssaltoVandalismo":"Inform if there was theft, assault, vandalism",
    "validacaoSelecioneATurma":"Repot group / team / Company",
    "validacaoSolucoesImplementadas":"Inform the Implemented solutions",
    "validacaoStatus":"Inform status",
    "validacaoSupervisorResponsavel":"Inform your supervisor",
    "validacaoSuprimentoDeEnergiaOuAguaInadequados":"Inform of there where power or water supply Inadequate",
    "validacaoTipoDeDocumento":"Inform the document type",
    "validacaoTipodeProjeto":"Enter the type of project",
    "validacaoTraducaoDoFato":"Inform the translation of occurrence",
    "validacaoUnidadeDoParticipante":"Select the participant's unit",
    "validacaoValorDoFrete":"Inform the Shipping Fee",
    "validacaUnidadeOndeProjetoFoiDesenvolvido":"Report the unit where the project was developed",
    "validaCodigoDoProduto":"Inform the Product Code",
    "labelHistoricoDeAprovacoes":"Approval History",
    "labelAguardandoDispatch":"Waiting for dispatch",
    "labelAguardandoAprovacao":"Waiting for approval",
    "labelAprovado":"Approved",
    "labelReprovado":"Fail",
    "labelLogar":"Sign In",
    "labelCPF":"ID number",
    "labelSenha":"Password",
    "validacaoUsuario":"Enter your username.",
    "validacaoSenha":"Enter your password.",
    "labelEsqueciSenha":"Forgot password?",
    "labelEsqueciSenha1":"Forgot password",
    "labelContinuarLogado":"Stay signed in",
    "labelNovaConta":"Create account",
    "labelPrecisaNovaConta":"Need an account?",
    "labelResetPassword":"Reset Password",
    "placeUsuario":"Enter your document number.",
    "labelLembreiSenha":"I remembered my password!",
    "labelMatricula":"Register",
    "placeMatricula":"Enter your enrollment",
    "validacaoMatricula":"Enter your enrollment.",
    "labelDataNascimento":"Date of birth",
    "validacaoDataNascimento":"Enter your date of birth.",
    "labelValidarInformacoes":"Validate Information",
    "labelChangePassword":"Change Password",
    "labelInfoUsuario":"Enter a new password for",
    "labelNewPassword":"New password",
    "validacaoNewPassword":"Enter your new password.",
    "labelConfirmNewPassword":"Confirm new password",
    "validacaoConfirmNewPassword":"Confirm your new password.",
    "validacaoPasswordsNotMatch":"Passwords do not match.",
    "labelPossuiRegistro":"Already registered?",
    "labelContinuar":"Continue",
    "labelCNPJ":"CNPJ",
    "labelEmail":"E-mail",
    "labelEmailNFE":"E-mail eletronic invoice",
    "labelEmailRecuperacao":"Please enter email address for password recover",
    "labelE":"AND",
    "labelLogin": "Login",
    "labelRecuperarSenha":"Recover Password",
    "validacaoMotivo":"Enter reason",
    "labelNomeRepresentante":"Nome do Representante",
    "placeNomeRepresentante":"Nome do Representante",
    "validacaoNomeRepresentante":"Informe o Nome do Representante",
    "labelResumoOcorrencia":"Resumo da Ocorrência",
    "placeResumoOcorrencia":"Resumo da Ocorrência",
    "validacaoResumoOcorrencia":"Informe o Resumo da Ocorrência",
    "validacaoDataAutorizacaoDevolucao":"Informe a data de autorização devolução",
    "labelCPM":"CPM",
    "tituloSemCadastroDePontos":"Register of missing points",
    "msgSemCadastroDePontos":"Contact the Lean Enterprise (leaninforma@rexam.com)",
    "labelNovaAcao": "Nova Ação",
    "placeCausas": "Informe uma causa",
    "validacaoCausas": "Informe uma causa",
    "labelAcaoCorrespondente": "Ação Correspondente",
    "placeAcaoCorrespondente": "Informe a ação correspondente",
    "validacaoAcaoCorrespondente": "Informe a ação correspondente",
    "placeResponsavel": "Informe o responsável",
    "validacaoResponsavel": "Informe o responsável",
    "labelPrazo": "Prazo",
    "validacaoPrazo": "Informe o Prazo",
    "labelPrazoExecucao": "Prazo de Execução",
    "labelAcao": "Ação",
    "labelPlanoDeAcao": "Plano de Ação",
    "labelEtapaAnaliseInicial": "Análise Inicial e Ações Imediatas",
    "labelEtapaPlanoDeAcao": "Plano de Ação e Conclusão",
    "labelCodigoPlanoAcao": "Código Plano de Ação",
    "labelUrlCodigoPlanoAcao": "Url Plano de Ação",
    "placeCodigoPlanoAcao": "Informe o Código Plano de Ação",
    "validacaoCodigoPlanoAcao": "Informe o Código Plano de Ação",
    "obsCbuBancos":"(Required only for Argentina and Peru)",
    "labelPedirCorrecaoSolicitante":"Send to requesting review",
    "validacaoContencao":"Inform Containment",
	"optionLatas":"Cans",
	"optionTampas":"Lids",
	"labelAcaoDeDeteccao":"Action of Detection - Why the defect was not detected and segregated internally?",
	"placeAcaoDeDeteccao":"Action of Detection - Why the defect was not detected and segregated internally?",
    "labelNumeroDoDocumento":"Document number",
    "placeNumeroDoDocumento":"Document number",
    "liSalvarRascunho":"Save Draft",
	"excelAcaoContencao":"Containment Action:",
	"excelAcaoContencaoDeteccao":"01 - CONTAINMENT AND DETECTION ACTION",
	"excelAcaoDeteccao":"Detection Action:",
	"excelCodLataTampa":"Code of Cans or End Cans (number of lot):",
	"excelConclusao":"03 - CONCLUSION",
	"excelConclusaoComentarios":"COMMENTS:",
	"excelConclusaoDevolucao":"RETURN? (Y/N)",
	"excelConclusaoParecerProcedencia":"CONFIRMATION IF THE DEFECT PROCEEDS OR NOT:",
	"excelConclusaoQuantidadeAutorizadaDevolvida":"Amount of Return approved:",
	"excelConclusaoQuantidadeAutorizadaRessarcimento":"Amount of Repayment approved:",
	"excelConclusaoRessarcimento":"REPAYMENT? (Y/N)",
	"excelConfirmacaoAcao":"ACTION:",
	"excelConfirmacaoCausas":"02 - CONFIRMATION OF REAL AND POTENTIAL CAUSES",
	"excelConfirmacaoPrazo":"DEAD LINE:",
	"excelConfirmacaoResponsavel":"RESPONSIBLE:",
	"excelDadosDescricao":"00 - DATA INPUT - DESCRIPTION OF OCCURRENCE",
	"excelDataFabricacao":"Production Date:",
	"excelDataOcorrencia":"Occurrence Date:",
	"excelDataPreenchidoPor":"Date:",
	"excelDefeitoReclamado":"Claimed Defect:",
	"excelDescricaoDesvio":"Description deviation reported by the customer:",
	"excelFormulario":"FORM",
	"excelMeioAmbiente":"Environment",
	"excelNotaFiscal":"Invoice:",
	"excelNotasRelevantes":"Relevant Notes: (machine, area, process, fail root cause, etc)",
	"excelPreenchidoPor":"Filled by:",
	"excelQualidade":"Quality",
	"excelQuantidadeReclamadaRetida":"Amount Claimed / Hold for Inspection Product in Customer Place:",
	"excelSaudeSeguranca":"Health and Safety",
	"excelSegurancaAlimentos":"Food Safety",
	"excelTituloAnexo":"ATTACHED - CORRECTIVE AND PREVENTIVE ACTION (CUSTOMER COMPLAINT RESPONSE)",
	"excelTraducaoFato":"Translation of fact: (finding after visit or evidence confirmation)",
    "liExportarExcel":"Excel Export",
    "excelTitulo":"TITLE:",
	"LabelDigito":"Digit"

}