{
    "msgDadosBancarios": "Informe los datos bancarios",
    "msgEmpresas": "Informe al menos una empresa",
    "msgConcluido": "Enviado con éxito!",
    "msgLider": "El equipo del proyecto debe tener un líder.",
    "msgEdicaoNaoEncontrada": "No hay una edición prevista para la creación de proyectos de innovación.",
    "msgEntrarContatoLean": "Si fuera necesario, contacte el área LEAN.",
    "msgPedidoAprovacaoExpirou": "El período de aprobación de los proyectos de esta edición ha expirado.",
    "msgPedidoCriacaoExpirou": "El período de creación de los proyectos de esta edición ha expirado.",
    "msgEquipe": "Informe los miembros del equipo.",
    "msgSucesso": "Éxito",
    "msgSenhaAlterada": "Contraseña cambiada",
    "msgUsuarioNaoLocalizado": "Usuario no encontrado",
    "msgUsuarioNaoCadastrado": "El usuario no registrado en el correo electrónico.",
    "msgAnaliseDasCausas":"Introduzca al menos una causa",
    "msgPlanoDeAcao":"Incluya al menos una acción",
    "msgArquivoObrigatorio":"Incluya al menos un archivo adjunto",
    "tituloEmailRecuperacaoSenha": "Recuperação de Senha - Rexam Workflow",
    "tituloEmailResetPassword": "Senha reiniciada - Workflow Rexam",
    "tituloEmailBoasVindas": "Bem vindo ao Workflow",
    "tituloEdicaoNaoEncontrada": "Sin edición programada",
    "tituloPedidoAprovacaoExpirou": "Período de aprobación ha expirado",
    "tituloPedidoCriacaoExpirou": "Período de creación ha expirado",
    "labelAceite": "Aceptación",
    "labelAceiteFornecedor": "Acepte Proveedor",
    "labelAcoesCorretivasPreventivas": "Acciones Correctivas y Preventivas",
    "labelAcoesPreventivas": "Acciones Preventivas",
    "labelAcoesCorretivas": "Acciones Correctivas",
    "labelAcompanhamentoFornecedor": "¿Hubo acompañamiento del proveedor en planta?",
    "labelAgenteFrete": "Agente de flete",
    "labelArquivos": "Archivos",
    "labelBairro": "Barrio / Localidad",
    "labelCadastro": "Catastro ",
    "labelCadastroSap": "Registro SAP",
    "labelCalculo": "Cálculo ",
    "labelCalculoReembolsoFinanceiro": "Calcular Reembolso Financiero",
    "labelCanalDeDistribuicao": "Canal de distribución",
    "labelCategoria": "Categorías",
    "labelCausaRaiz": "Causa Raíz",
    "labelCentroDeFornecimento": "Centro de Abastecimiento",
    "labelCEP": "Código postal",
    "labelCidade": "Ciudad",
    "labelClasse": "Clase",
    "labelCodigoClienteSAP": "Código SAP Cliente",
    "labelCodigoFiscal": "Código Fiscal (CUIT, RUT, RUC)",
    "labelCodigoFiscalLogin": "Clave fiscal",
    "labelCodigoMetal": "Código Metal",
    "labelCodigoProdutoFornecedor": "Código de producto proveedor",
    "labelCodigoProdutoSAP": "Código de producto SAP",
    "labelCoef": "Coef.(Kg/m):",
    "labelComentarioRexam": "Comentarios Adicionales de Rexam",
    "labelComentarios": "Comentarios ",
    "labelComentariosDaOcorrencia": "Comentarios ocurrencia",
    "labelComplementoEndereco": "Complemento",
    "labelCondicaoDaExpedicao": "Condición de entrega",
    "labelCondicaoDePagamento": "Condiciones de pago",
    "labelContaConciliatoria": "Cuenta contable",
    "labelCriarNOC": "Crear NOC",
    "labelCustosDespesas": "Costos/gastos",
    "labelCustosFerramentas": "Costos Herramientas(US$):",
    "labelDataAprovacao":"Fecha de Aprobación",
    "labelDadosContabeis": "Datos de Contabilidad",
    "labelDadosFiscais": "Datos fiscales",
    "labelDataAbertura": "Fecha de Apertura",
    "labelDataAceite": "Fecha de Aceptación",
    "labelDataEntrada": "Fecha de Entrada",
    "labelDataFabricacao": "Fecha de fabricación",
    "labelDataFaturamentoFornecedor": "Fecha de Fact. del Proveedor",
    "labelDataOcorrencia": "Fecha de Ocurrencia:",
    "labelDataResposta": "Fecha de la respuesta ",
    "labelDataEncerramento": "Fecha tope ",
    "labelDetalhesOutrasPerdas": "Especificar Otras Pérdidas",
    "labelDetalhesPerdaFerramenta": "Especificar pérdida de herramienta",
    "labelDetalhesProblema": "Detalles del Problema",
    "labelEmailDeCobranca": "Correo de cobranza",
    "labelEmailEnviado": "Correo con la contraseña enviado para ",
    "labelEmpresas": "Compañías",
    "labelEtapa1": "Paso 1",
    "labelEtapa2": "Paso 2",
    "labelEtapa3": "Paso 3",
    "labelEtapa4": "Paso 4",
    "labelFisica": "Física",
    "labelFormaDePagamento": "Forma de pago",
    "labelFornecedor": "Proveedor",
	"labelTransportadora": "Transportista",
    "labelGerouDrenoLinha": "¿El defecto generó vaciado de linea?",
    "labelGerouPerdaProducao": "¿El defecto generó pérdida de producción?",
    "labelGrupoAdmTesouraria": "Grupo ADM Tesorería",
	"labelGrupoDeCliente": "Grupo de cliente",
    "labelGrupoDeClientes": "Grupo de clientes",
    "labelGrupoDeContas": "Grupo de cuentas",
    "labelGrupoDePreco": "Grupo de precios",
    "labelGrupoDeVendedores": "Grupo de Ventas",
    "labelHistorico": "Historia ",
    "labelHoraDeOcorrencia": "Hora de ocurrencia",
    "labelIncoterm": "Incoterm",
    "labelInformacoesGerais": "Información general",
    "labelInscricaoEstadual": "Registro de Estado",
    "labelInscricaoMunicipal": "Registro Municipal",
    "labelJuridica": "Jurídico",
    "labelKGs": "Copos em KGs :",
    "labelLogradouro": "Dirección",
    "labelLote": "Lote",
    "labelMoeda": "Moneda",
    "labelMoedaContabilizacao": "Moneda de contabilización",
    "labelMotivoDaSolicitacao": "Motivo de la Solicitud",
    "labelNao": "No",
    "labelNomeCliente": "Nombre del cliente",
    "labelNomeDeBusca": "Búsqueda por nombre",
    "labelNomeEmissorNoc": "Nombre del Emisor de la NOC",
    "labelNotaFiscal": "Factura",
	"labelNovaEmpresa":"Nueva empresa",
    "labelNovoGrupoClientes": "Nuevo código de grupo de clientes",
    "labelNovoGrupoPreco": "Nuevo código de grupo de precios",
    "labelNovoZonaTransporte": "Nuevo código de área de transporte",
    "labelNumeroCartaoHFI": "Nº de la Tarjeta HFI",
    "labelNumeroCliente": "Número de cliente",
    "labelNumeroEndereco": "Número",
    "labelObservacao": "Observación",
    "labelOrganizacaoDeVendas": "Organización de ventas",
    "labelOutrasPerdasCustos": "¿Hubo otras pérdidas u otros costos? (SOLO EM CASO DE CRISIS Y DE ACUERDO CON LA OFICINA)",
    "labelOutrosCustos": "Otros Costos (US$):",
    "labelPaisDoCliente": "País del cliente",
    "labelPaisRexam": "País Rexam",
    "labelParecerPrevio": "Dictamen preliminar Rexam",
    "labelPassoFinanceiro": "Paso Financiera",
    "labelPedidoCorrecao": "Pedido de corrección",
    "labelPerdaFerramenta": "¿Hubo pérdida de herramienta? (SOLO EM CASO DE CRISIS Y DE ACUERDO CON LA OFICINA)",
    "labelPerdasMetal": "Pérdida Metal(US$):",
    "labelPerdasProducao": "Las Pérdidas producción(US$):",
    "labelPerdaTotal": "Pérdida Total(US$):",
    "labelPesoReclamada": "Peso Reclamada",
    "labelPesoTotalBobina": "Peso Total de la Bobina",
    "labelPlacaVeiculo": "Placa del vehículo",
    "labelPlanta": "Planta",
    "labelPrecoCompra": "Precio de Compra (US$):",
    "labelPrecoVenda": "Precio de Venta (US$):",
    "labelQtdAmostrasEnviadasFornecedor": "Ctd. Muestras Enviadas al Proveedor",
    "labelQtdProdutosPerdidos": "Cant. tazas (UN.):",
    "labelQtsLatasTampas": "¿Cuántas Latas y/o Tapas?",
    "labelQuantidadeAmostrasEnviadasFornecedor": "Ctd. Muestras Enviadas al Proveedor",
    "labelQuantidadeRetida": "Cantidad  retenido",
    "labelQuantidadeRetornoFornVenda": "Ctd. Retorno Proveedor/Venta",
    "labelRecebedorMercadoria": "Recepción de Mercadería",
    "labelRecebedorMercadoriaDiferente": "Destinatario de las mercaderías es diferente de este registro?",
    "labelReembolsoToral": "Reembolso Total(US$):",
    "labelRegiao": "Estado / Provincia",
    "labelRegiaoDeVendas": "Zona de ventas",
    "labelResponsavel": "Responsable ",
    "labelResposta": "Respuesta",
    "labelRessarcimento": "Reembolso",
    "labelReteste": "¿Hubo re-test?",
    "labelRetornoIndicadorRetornoVenda": "Indicador de Retorno o Venta",
    "labelSelecioneStatus": "Seleccionar Estado",
    "labelSetorDeAtividade": "Sector empresarial",
    "labelSetorIndustrial": "Sector industrial",
    "labelSeveridade": "Severidad",
    "labelSim": "Sí",
    "labelStatusAprovacao": "Estado de aprobación ",
    "labelTelefone": "Teléfono",
    "labelTipoDePessoa": "Tipo de Persona",
    "labelTipoDeServico": "Tipo de Servicio",
    "labelTipoMetal": "Tipo de Metal",
    "labelTipoProblema": "Tipo Problema",
    "labelTituloDefeito": "Defecto",
    "labelUnidadeMedida": "Unidad de Medida",
    "labelUnidadeRetida": "Unidad de medida retenido",
    "labelUploadArquivos": "Subir archivo",
    "labelValor": "Valor: US$",
    "labelZonaDeTransporte": "Zona de Transporte",
    "labelExDocumentoBancario": "ES - (Ex: Copia de cheque, extracto bancario, CBU con Nombre, Agencia y CC o CA)",
    "liAceitar": "Aceptar",
    "liAnterior": "Anterior",
    "liCliente": "Cliente",
    "liDevolver": "Retorno",
    "liProximo": "Siguiente",
    "liRexam": "Rexam",
    "liSalvar": "Grabar",
    "optionCategoriaMaterialDireto": "Material directo",
    "optionCategoriaMaterialIndireto": "Materiales indirectos",
    "optionCategoriaServicos": "Servicios",
    "optionCategoriaTransporte": "Envío/Movimiento interno",
    "optionDevolucao": "Devolución",
	"optionTransportadora": "Seleccione la transportista",
    "optionMoedaContabilizacao": "Seleccione la moneda de cuenta",
    "optionZonaDeTransporte": "Seleccione un valor para el campo zona de transporte",
    "optionNovoGrupoDeClientes": "Nuevo grupo de clientes",
    "optionNovoGrupoDePreco": "Nuevo grupo de precios",
    "optionSelecioneCategoria": "Seleccione un valor para el campo categoría",
    "optionSelecioneCausaRaiz": "Seleccionar un valor para el campo Causa Raíz",
    "optionSelecioneCentroDeFornecimento": "Seleccione un valor para el campo Centro de Abastecimiento",
    "optionSelecioneClasse": "Seleccione un valor para el campo de la clase",
    "optionSelecioneClassificacaoFiscal": "Seleccione la clasificación fiscal",
    "optionSelecioneCodMetal": "Seleccionar un valor para el campo Código Metal",
    "optionSelecioneCondicaoExpedicao": "Seleccione un valor para el campo Condición de entrega",
    "optionSelecioneCondicaoPagamento": "Seleccione un valor para el campo Condiciones de pago",
    "optionSelecioneContaConciliatoria": "Seleccione la cuenta contable",
    "optionSelecioneDefeito": "Seleccione un valor para el defecto del campo",
    "optionSelecioneEmpresas": "Seleccione uno o más valores para el campo de negocios",
    "optionSelecioneFormaDePagamento": "Seleccione un valor para el campo forma de pago",
    "optionSelecioneFornecedor": "Seleccionar un valor para el campo Proveedor",
    "optionSelecioneGrupoAdmTesouraria": "Seleccione Grupo ADM Tesorería",
    "optionSelecioneGrupoDeContas": "Seleccione un valor para el campo Grupo Cuenta",
    "optionSelecioneIncoterm": "Seleccione un valor para el campo Incoterm",
    "optionSelecioneMoeda": "Seleccione un valor para el campo de moneda",
    "optionSelecionePaisCliente": "Seleccione un valor para el campo país del cliente",
    "optionSelecionePaisRexam": "Seleccione un valor para el campo País Rexam",
    "optionSelecionePlanta": "Seleccione un valor para el campo Planta",
    "optionSelecioneProblema": "Seleccione un valor para el campo Tipo Problema",
    "optionSelecioneRegiao": "Seleccione un valor para el campo región",
    "optionSelecioneRegiaoDeVendas": "Seleccione un valor para el campo región de venta",
    "optionSelecioneSetorIndustrial": "Seleccione el sector industrial",
    "optionSelecioneSeveridade": "Seleccione un valor para el campo Gravedad",
    "optionSelecioneTipoMetal": "Seleccionar un valor para el campo Tipo Metal",
    "optionTipoDeServico": "Seleccione el tipo de servicio",
    "optionVenda": "Venta",
    "placeAgenteFrete": "Ingrese el agente de flete",
    "placeBairro": "Ingrese el Barrio / Localidad",
    "placeCEP": "Ingrese el código postal",
    "placeCidade": "Ingrese la Ciudad",
    "placeCodigoClienteSAP": "Ingrese el Código SAP Cliente",
    "placeCodigoFiscal": "Informar el código fiscal",
    "placeCodigoProdutoFornecedor": "Informar el código de producto del proveedor",
    "placeCodigoProdutoSAP": "Informar código de producto SAP",
    "placeComentariosAdicionais": "Informe comentarios adicionales",
    "placeComentariosDaOcorrencia": "Introduzca una revisión de la ocurrencia",
    "placeComplemento": "Informe el Complemento",
    "placeCustoDespesas": "Informar costos/gastos",
    "placeDetalharOutrasPerdas": "Detalle otras pérdidas y costos",
    "placeDetalharPerdasFerramentas": "Detalle perdidas de herramental",
    "placeEmail": "Ingrese la dirección de correo",
    "placeEmailCobranca": "Ingrese el correo de cobranza",
    "placeEmailNFE": "Ingrese el correo electrónico nota fiscal",
    "placeIndicadorDevolucaoVendaMetal": "Seleccionar un valor para el campo Indicador de Retorno o Venta",
    "placeInformeDescricaoProblema": "Informe la descripción del problema",
    "placeInformeDetalhePerdaFerramenta": "Informe detalles de la perdida de herramental",
    "placeInformeLatasTampas": "Informe cuantas latas y/o tapas",
    "placeINformeNumHFI": "Informe el numero de tarjeta de HFI",
    "placeInformeNumLote": "Informe el Número de lote",
    "placeInformePesoReclamada": "Informe el peso reclamado",
    "placeInformePesoTotalBobina": "Informe el peso total de la bobina ",
    "placeInformeQntAmostrasEnviada": "Informe la cantidad de muestras enviadas al proveedor",
    "placeInformeQntAmostrasRetornadas": "Informe la cantidad de muestras devueltas por el proveedor",
    "placeInformeUnidadeMedida": "Seleccione la unidad de medida",
    "placeInformeValorPerdaFerramenta": "Informe el valor de la pérdida de herramental",
    "placeInscricaoEstadual": "Informar el registro estatal",
    "placeInscricaoMunicipal": "Introduzca el registro municipal",
    "placeLogradouro": "Informe la Dirección",
    "placeMotivoSolicitacao": "Ingrese motivo de la solicitud",
    "placeNomeCliente": "Ingrese Nombre del cliente",
    "placeNomeDeBusca": "Ingrese búsqueda por nombre",
    "placeNotaFiscal": "Informar la factura",
    "placeNovaZonaDeTransporte": "Ingrese el nuevo código zona de transporte",
    "placeNovoGrupoClientes": "Ingrese el nuevo código de grupo de clientes",
    "placeNovoGrupoPreco": "Ingrese el nuevo código de grupo de precios",
    "placeNumero": "Ingrese el número",
    "placeNumeroCliente": "Número de cliente",
    "placeObservacao": "Informar observación",
    "placeParecerPrevio": "Introduzca opinión preliminar Rexam",
    "placePedidoCorrecao": "Ingrese el pedido de corrección",
    "placePlacaVeiculo": "Introduzca la placa del vehículo",
    "placeQuantidadeRetida": "Informar la cantidad retenido",
    "placeRecebedorDaMercadoria": "Informe el receptor de la mercadería",
    "placeRegiao": "Ingrese el Estado / Provincia",
    "placeSelecioneDataEntrada": "Seleccione la fecha de entrada",
    "placeSelecioneDataFaturamento": "Seleccione la fecha de facturación del proveedor",
    "placeSelecioneDataOcorrencia": "Seleccione la fecha de ocurrencia",
    "placeSolteOsArquivosAqui": "Caída de los archivos aquí ...",
    "placeTelefone": "Informar teléfono",
    "placeUnidadeRetida": "Informar unidad de medida retenido",
    "tituloCadastroCLiente": "Alta de Cliente",
    "tituloCriacaoNoc": "Creación de NOC",
	"labelEdicaoDeNocCliente": "Edición de NOC",
    "validacaoAcompanhamentoFornecedor": "Ingresar si esta acompañado del proveedor",
    "validacaoAgenteFrete": "Ingrese el agente de flete",
    "validacaoBairro": "Ingrese el barrio / localidad",
    "validacaoCartaoHFI": "Ingresar el número de tarjeta de HFI",
    "validacaoCategoria": "Introduzca la categoría",
    "validacaoCausaRaiz": "Ingresar la causa raíz",
    "validacaoCentroDeFornecimento": "Ingrese Central de Abastecimiento",
    "validacaoCEP": "Introduzca el código postal",
    "validacaoCidade": "Ingrese la Ciudad",
    "validacaoClasse": "Informar a la clase",
    "validacaoCodigoClienteSAP": "Ingrese el Código SAP Cliente",
    "validacaoCodigoFiscal": "Informar el código fiscal",
    "validacaoCodigoMetal": "Ingresar el código del metal",
    "validacaoCodigoProdutoFornecedor": "Informar el código de producto del proveedor",
    "validacaoCodigoProdutoSAP": "Informar código de producto SAP",
    "validacaoCondicaoDeExpedicao": "Ingrese la Condición de entrega",
    "validacaoCondicaoDePagamento": "Ingrese las condiciones de pago",
    "validacaoContaConciliatoria": "Seleccione la cuenta contable",
    "validacaoCustosDespesas": "Informar costos/gastos",
    "validacaoDataEntrada": "Ingresar la fecha de entrada",
    "validacaoDataFabricacao": "Informe la fecha de fabricación",
    "validacaoDataFaturamenFornecedor": "Ingresar la fecha de factura del proveedor",
    "validacaoDataOcorrencia": "Ingresar la fecha del acontecimiento",
    "validacaoDcrPerdaFerramenta": "Ingresar detalles de la pérdida de herramientas",
    "validacaoDcrPerdaOutrosCustos": "Ingresar detalles de otras pérdidas/costos",
    "validacaoDcrProblema": "Informar el detalles del problema",
    "validacaoDefeito": "Informar al defecto",
    "validacaoEmail": "Ingrese la dirección de correo",
    "validacaoEmailCobranca": "Ingrese lo correo de cobranza",
    "validacaoEmailNFE": "Ingrese el correo electrónico nota fiscal",
    "validacaoEmpresas": "Ingrese una o más empresas",
    "validacaoFormaDePagamento": "Informar la forma de pago",
    "validacaoFornecedor": "Informar al proveedor",
    "validacaoGerouDrenoLinha": "Ingresar el defecto que genero el drenaje de linea",
    "validacaoGerouPerdaProducao": "Informe defecto que genero perdida de producción",
    "validacaoGrupoClientes": "Ingrese los clientes del Grupo",
    "validacaoGrupoDeContas": "Ingrese el grupo de cuentas",
    "validacaoGrupoPreco": "Ingrese el grupo de precios",
    "validacaoIncoterm": "Ingrese Incoterm",
    "validacaoIndicadorDevolucaoVenda": "Ingresar indicador de rentabilidad o vender el código de metal",
    "validacaoInscricaoEstadual": "Informar el registro estatal",
    "validacaoInscricaoMunicipal": "Introduzca el registro municipal",
    "validacaoLogradouro": "Informe la dirección",
    "validacaoLote": "Ingrese el Lote",
    "validacaoMoeda": "Informar a la moneda",
    "validacaoMoedaContabilizacao": "Introduzca la moneda de cuenta",
    "validacaoMotivoDaSolicitacao": "Ingrese motivo de la solicitud",
    "validacaoNomeCliente": "Ingrese Nombre del cliente",
    "validacaoNomeDeBusca": "Ingrese búsqueda por nombre",
    "validacaoNotaFiscal": "Informar la factura",
    "validacaoNovaZonaDeTransporte": "Ingrese el nuevo código de zona de transporte ",
    "validacaoNovoGrupoClientes": "Ingrese el nuevo código de grupo de clientes",
    "validacaoNovoGrupoPreco": "Ingrese el nuevo código de grupo de precios",
    "validacaoNumero": "Ingrese el número",
    "validacaoNumeroCliente": "Informar número de cliente",
    "validacaoPaisDaRexam": "Ingrese el País Rexam",
    "validacaoPaisDoCliente": "Informar país del cliente ",
    "validacaoPedidoCorrecao": "Introduzca la solicitud de corrección",
    "validacaoPerdaFerramenta": "Ingresar si hubo perdida de herramientas",
    "validacaoPerdaOutrosCustos": "Ingresar si ocurrio otras pérdidas u otros costos ",
    "validacaoPesoReclamada": "Ingresar el peso reclamado",
    "validacaoPesoTotalBobina": "Ingresar  el peso total de la bobina",
    "validacaoPlacaVeiculo": "Introduzca la placa del vehículo",
    "validacaoPlanta": "Ingresar la planta",
    "validacaoQtdAmostraEnviada": "Ingresar Qty. De muestras enviadas al proveedor (medias latas o placas)",
    "validacaoQtdAmostraRetorno": "Ingresar Qty. retorno proveedor / venta",
    "validacaoQtdDefeitoDrenoLinha": "Ingresar cantidad latas y/o tapas",
    "validacaoQtdDefeitoPerdaProducao": "Ingresar cantidad de latas y/o Tapas",
    "validacaoQuantidadeRetida": "Informar cantidad retenido",
    "validacaoRecebedorDiferente": "Informar el beneficiario de esta mercadería es diferente de este registro",
    "validacaoRegiao": "Ingrese el estado",
    "validacaoRegiãoDeVendas": "Ingrese la zona de ventas",
    "validacaoReteste": "Infromar si ocurrió retest",
    "validacaoSelecioneClassificacaoFiscal": "Introduzca la clasificación fiscal",
    "validacaoSelecioneGrupoAdmTesouraria": "Seleccione Grupo ADM Tesorería",
    "validacaoSelecioneSetorIndustrial": "Informar sector industrial",
    "validacaoSeveridade": "Informar a la gravedad",
    "validacaoTelefone": "Informar teléfono",
    "validacaoTipoDeServico": "Informar el tipo de servicio",
    "validacaoTipoMetal": "Ingresar el tipo de metal",
    "validacaoTipoProblema": "Ingresar el tipo de problema",
    "validacaoUnidadeMedida": "Ingresar la unidad de medida",
    "validacaoUnidadeRetida": "Informar unidad de medida retenido",
    "validacaoValorPerdaFerramenta": "Ingresar el valor de la pérdida de herramienta",
    "validacaoValorPerdaOutrosCustos": "Ingresar el valor de otras pérdidas/costos",
    "validacaoZonaDeTransporte": "Ingrese la zona de transporte",
    "buttonCancelar": "Cancelar",
    "buttonIncluirBanco": "Incluir Banco",
    "buttonIncluirEmpresa": "Incluir Empresa",
    "buttonIncluirMembro": "Incluir miembro del equipo",
    "buttonSalvar": "Grabar",
    "labelAgenciaComDigito": "Agencia",
    "labelAguardandoAprovacaoSAP": "Esperando la aprobación de SAP",
    "labelAguardandoAprovacaoSetorFinanceiro": "Esperando la aprobación del sector financiero",
    "labelAguardandoCorrecaoClientes": "Esperando corrección del solicitante",
    "labelAguardandoCorrecaoFornecedor": "Esperando corrección del proveedor",
    "labelAguardandoSetorDadosContabeis": "Aguardando el sector de Datos Contables",
    "labelAguardandoSetorDadosFiscais": "Aguardando el sector de Dados Fiscales",
    "labelAguardandoSetoresDadosFiscaisDadosContabeis": "Aguardando los sectores de Dados Fiscales e Dados Contables",
    "labelAprovacaoFinanceiro": "Aprobación Financiero",
    "labelBanco": "Banco",
    "labelCadastroCancelado": "Registro cancelado",
    "labelCadastroConcluido": "Registro completado",
    "labelCadastroFornecedor": "Alta de Proveedores",
    "labelCartaAutorizacao": "Carta de Autorización",
    "labelCBU": "CBU",
    "labelClienteEnvasadoraProdutoAcabado": "Cliente es envasador / Producto Terminado?",
    "labelContaCorrenteComDigito": "Cuenta bancaria",
    "labelDadosBancarios": "Datos Bancarios",
    "labelDocumentoBancario": "Documento Bancário",
    "labelIncotermFOB": "FOB?",
    "labelJustificativaCondicaoPagamento": "Justificación de condición de pago",
    "labelJustificativaFormaPagamento": "Justificación de forma de pago",
    "labelNome": "Nombre",
    "labelNomeSobrenomeContato": "Nombre/Apellido Contacto",
    "labelNumeroFornecedorSAP": "Número Proveedor SAP",
    "labelOrganizaçãoCompra": "Organización de Compras",
    "labelOutros": "Otros",
    "labelPaisFornecedor": "País del Proveedor",
    "labelRetornarPara": "Volver para",
    "labelTipoLogradouro": "Tipo de Calle",
    "liAnexos": "Archivos adjuntos",
    "liFornecedor": "Proveedor",
    "optionContabilidade": "Contabilidad",
    "optionFinanceiro": "Financiero",
    "optionOrganizacaoCompra": "Seleccione la organización de compra",
    "optionPaisFornecedor": "Seleccione el país del proveedor",
    "optionSelecioneBanco": "Seleccione uno o más bancos",
    "optionSelecioneMoeda": "Seleccione la moneda",
    "optionSelecioneOndeDeveRetornar": "Seleccione retorno",
    "optionSolicitante": "Solicitante",
    "optionTipoLogradouro": "Seleccione el Tipo de Calle",
    "placeAgenciaComDigito": "Agencia",
    "placeCBU": "CBU",
    "placeContaCorrenteComDigito": "Conta bancaria",
    "placeJustificativaCondicaoPagamento": "Justificación de condición de pago",
    "placeJustificativaFormaPagamento": "Justificación de forma de pago",
    "placeNome": "Nombre",
    "placeNomeSobrenomeContato": "Nombre/Apellido Contacto",
    "placeNumeroFornecedorSAP": "Número Proveedor SAP",
    "thAgencia": "Agencia",
    "thBanco": "Banco",
    "thCBU": "CBU",
    "thContaCorrente": "Conta Bancaria",
    "thEmpresa": "Empresa",
    "thOrganizacaoCompras": "Organización de Compras",
    "tituloNovaEmpresa": "Nueva Empresa",
    "tituloNovoBanco": "Nuevo Banco",
    "validacaoAgenciaComDigito": "Informe Agencia (con dígito)",
    "validacaoContaCorrenteComDigito": "Informe la Conta Bancaria (con dígito)",
    "validacaoIncotermFOB": "Incoterm FOB",
    "validacaoJustificativaCondicaoPagamento": "Informe Justificación Condición Pagamento",
    "validacaoJustificativaFormaPagamento": "Informe Justificación Forma Pagamento",
    "validacaoNome": "Informe el Nombre",
    "validacaoNumeroFornecedorSAP": "Informe el Número Proveedor SAP",
    "validacaoOrganizacaoCompra": "Informe la organización de compra",
    "validacaoPaisFornecedor": "Informe el país del proveedor",
    "validacaoRetornarPara": "Informe Retornar a",
    "validacaoSelecioneArquivoCodigoFiscal": "Adjunte un archivo de Código Fiscal",
    "validacaoSelecioneArquivoTipoCartaAutorizacao": "Adjunte un archivo de Carta Autorización",
    "validacaoSelecioneArquivoTipoDocumentoBancario": "Adjunte un archivo de Documento Bancario",
    "validacaoSelecioneArquivoTipoInscricaoEstadual": "Adjunte un archivo de Registro Estatal",
    "validacaoSelecioneArquivoTipoInscricaoMunicipal": "Adjunte un archivo de Registro Municipal",
    "validacaoSelecioneBanco": "Informe uno o más bancos",
    "validacaoSelecioneEmpresa": "Informe una empresa",
    "validacaoSelecioneMoeda": "Informe la Moneda",
    "validacaoTipoLogradouro": "Informe el Tipo de Calle",
    "validaNomeSobrenomeContato": "Informe el Nombre/Apellido de Contacto",
    "labelMaterial": "Material",
    "labelCodigoDoMaterialNoSAP": "Código del Material en SAP",
    "placeCodigoDoMaterialNoSAP": "Código del Material en SAP",
    "validacaoCodigoDoMaterialNoSAP": "Informe el Código del Material en SAP",
    "labelDevolverPara": "Volver para",
    "labelSuprimentos": "Suministros",
    "optionSuprimentos": "Suministros",
    "optionFiscal": "Fiscal",
    "optionContabil": "Contable",
    "optionEngenharia": "Ingeniería",
    "labelClasseAvaliacao": "Clase Evaluación",
    "placeClasseAvaliacao": "Clase Evaluación",
    "validacaoClasseAvaliacao": "Informe la Clase Evaluación",
    "labelModeloMaterial": "Modelo de Material",
    "optionSelecioneAPlanta": "Seleccione la Planta",
    "labelDescricaoCurta": "Descripción breve",
    "placeDescricaoCurta": "Descripción breve",
    "validacaoDescricaoCurta": "Informe la Descripción breve",
    "optionUnidadeMedida": "Unidad de medida",
    "labelGrupoMercadoria": "Grupo de artículos",
    "optionGrupoMercadoria": "Seleccione el Grupo de artículos",
    "validacaoGrupoMercadoria": "Informe el Grupo de artículos",
    "labelDescricaoLonga": "Descripción Larga",
    "placeDescricaoLonga": "Descripción Larga",
    "validacaoDescricaoLonga": "Informe la Descripción Larga",
    "labelDescricaoImportada": "Descripcción en Inglés",
    "placeDescricaoImportada": "Descripcción en Inglés",
    "labelOrigemMaterial": "Origen Material",
    "optionOrigemMaterial": "Seleccione la Origen Material",
    "validacaoOrigemMaterial": "Informe la Origen Material",
    "labelEngenharia": "Ingeniería",
    "labelFerramentaIntermutavel": "Herramienta Intercambiable",
    "labelItemCritico": "Ítem Crítico",
    "labelItemRecuperavel": "Ítem Recuperable",
    "labelDeposito": "Almacén",
    "optionDeposito": "Seleccione el Almacén",
    "validacaoDeposito": "Informe el Almacén",
    "labelFuncaoMaterial": "Función del Material",
    "optionFuncaoMaterial": "Función del Material",
    "placeUtilizacaoEquipamento": "Uso del Equipamiento",
    "optionUtilizacaoEquipamento": "Seleccione el uso del equipamiento",
    "validacaoUtilizacaoEquipamento": "Informe el uso del equipamiento",
    "labelEquipamento": "Equipamiento",
    "optionEquipamento": "Seleccione el Equipamiento",
    "validacaoEquipamento": "Informe el Equipamiento",
    "labelFabricanteReferencia": "Fabricante/Referencia",
    "placeFabricanteReferencia": "Fabricante/Referencia",
    "validacaoFabricanteReferencia": "Informe el Fabricante/Referencia",
    "labelEstoqueMinimo": "Stock Mínimo",
    "placeEstoqueMinimo": "Stock Mínimo",
    "validacaoEstoqueMinimo": "Informe el Stock Mínimo",
    "labelEstoqueMaximo": "Stock Máximo",
    "placeEstoqueMaximo": "Stock Máximo",
    "validacaoEstoqueMaximo": "Informe el Stock Máximo",
    "placeTipoMRP": "Tipo MRP",
    "optionTipoMRP": "Seleccione el Tipo MRP",
    "validacaoTipoMRP": "Informe el Tipo MRP",
    "placePlanejadorMRP": "Planeador MRP",
    "optionPlanejadorMRP": "Seleccione el Planeador MRP",
    "validacaoPlanejadorMRP": "Informe el Planeador MRP",
    "placeTamanhoDoLoteMRP": "Tamaño del Lote MRP",
    "optionTamanhoDoLoteMRP": "Seleccione el Tamaño del Lote MRP",
    "validacaoTamanhoDoLoteMRP": "Informe el Tamaño del Lote MRP",
    "labelTipoDeFert": "Tipo de FERT",
    "labelLata": "Lata",
    "labelampa": "Tapa",
    "labelDeixarVersaoBloqueadoEmZ1": "Bloquear Versión en Z1?",
    "labelDeixarVersaoBloqueadoEm03": "Bloquear Versión en 03?",
    "labelQuantidadeLatasPorCamada": "Cantidad de latas por capa",
    "placeQuantidadeLatasPorCamada": "Cantidad de latas por capa",
    "validacaoQuantidadeLatasPorCamada": "Informe la Cantidad de latas por Capa",
    "labelTipoDeLata": "Tipo de Lata",
    "placeTipoDeLata": "Tipo de Lata",
    "validacaoTipoDeLata": "Informe el Tipo de Lata",
    "labelObservacoes": "Observaciones",
    "placeObservacoes": "Observaciones",
    "labelInformacoesListaTecnica": "Información Lista Técnica",
    "labelNovaInformacaoListaTecnica": "Nueva Información Lista Técnica",
    "labelQuantidade": "Cantidad",
    "placeQuantidade": "Cantidad",
    "validacaoQuantidade": "Informe la Cantidad",
    "labelProduto": "Producto",
    "placeProduto": "Producto",
    "validacaoProduto": "Informe el Produto",
    "labelCodigo": "Código",
    "placeCodigo": "Código",
    "validacaoCodigo": "Informe el Código",
    "labelFiscal": "Fiscal",
    "optionSelecioneCategoriaCFOP": "Seleccione la categoría CFOP",
    "labelCategoriaCFOP": "Categoría CFOP",
    "validacaoCategoriaCFOP": "Informe la categoría CFOP",
    "labelClassificacaoFiscal": "Clasificación Fiscal",
    "labelUtilizacaoDoMaterial": "Utilización del Material",
    "placeUtilizacaoDoMaterial": "Utilización del Material",
    "validacaoUtilizacaoDoMaterial": "Validación Utilización del Material",
    "labelLabEsc": "Lab./escr.",
    "optionLabEsc": "Seleccione el Lab./escr.",
    "validacaoLabEsc": "Informe el Lab./escr.",
    "labelCentroDeLucro": "Centro de Lucro",
    "optionCentroDeLucro": "Seleccione el Centro de Lucro",
    "validacaCentroDeLucro": "Informe el Centro de Lucro",
    "labelDepositoDeProducao": "Almacén De Producción",
    "optionDepositoDeProducao": "Seleccione el Almacén De Producción",
    "validacaoDepositoDeProducao": "Informe el Almacén De Producción",
    "labelGrupoMRP": "Grupo MRP",
    "optionGrupoMRP": "Seleccione el Grupo MRP",
    "validacaoGrupoMRP": "Informe el Grupo MRP",
    "labelAguardandoCorrecaoCadastro": "Esperando la correción en el registro",
    "labelAguardandoSetorSuprimentos": "Esperando sector de suministros",
    "labelAguardandoSetoresFiscalEContabil": "Esperando sectores fiscal y contable",
    "labelAguardandoSetorFiscal": "Esperando sector fiscal",
    "labelAguardandoSetorContabil": "Esperando sector contable",
    "labelAguardandoSetorEngenharia": "Esperando sector de ingeniería",
    "labelPesoBruto": "Peso Bruto",
    "placePesoBruto": "Peso Bruto",
    "validacaoPesoBruto": "Informe el Peso Bruto",
    "labelPesoLiquido": "Peso Neto",
    "placePesoLiquido": "Peso Neto",
    "validacaoPesoLiquido": "Informe el Peso Neto",
    "labelTipoDeMaterial": "Tipo de Material",
    "labelCodigoDoMaterial": "Código del Material",
    "labelAplicacaoDoEquipamento": "Aplicación del Equipamiento",
    "optionAplicacaoDoEquipamento": "Seleccione la Aplicación del Equipamiento",
    "validacaoAplicacaoDoEquipamento": "Informe la Aplicación del Equipamiento",
    "labelPartNumber": "Part Number",
    "placePartNumber": "Part Number",
    "validacaoPartNumber": "Informe el Part Number",
    "labelQuantidadeLatasTampasPorPalete": "Cantidad de Latas/Tapas Por Pallet",
    "placeQuantidadeLatasTampasPorPalete": "Cantidad de Latas/Tapas Por Pallet",
    "validacaoQuantidadeLatasTampasPorPalete": "Informe la cantidad de Latas/Tapas Por Pallet",
    "labelCadastroDeMaterial": "Alta de Material",
    "labelCustoMaterial": "Costo Material",
    "placeCustoMaterial": "Costo Material",
    "validacaoCustoMaterial": "Informe el Costo Material",
    "labelCodigoNCM": "Código NCM",
    "placeCodigoNCM": "Código NCM",
    "validacaoCodigoNCM": "Informe el Código NCM",
    "validacaoAcoesCorretivas": "Informe las acciones correctivas",
    "validacaoAcoesPreventivas": "Informe las acciones preventivas",
    "validacaoParecer":"Indique la Conclusión",
    "labelAguardandoAceite":"En espera de aceptación",
    "labelAguardandoResposta":"Esperando Respuesta",
    "labelAguardandoRespostaEspecialistaLean":"Esperando Respuesta Especialista Lean",
    "labelAguardandoRespostaGerente":"Esperando Respuesta Gerente",
    "labelAguardandoRespostaLiderLean":"Esperando Respuesta Líder Lean",
    "labelAguardandoRespostaSuperiorImediato":"Esperando Respuesta Superior Inmediato",
    "labelAlocacaoDeRecursosDeficienteFaltaDeRecursos":"Asignación de Recursos Deficiente / Falta de Recursos",
    "labelAlto":"Alto",
    "labelAnaliseDoProblemaESuasCausas":"Análisis de causa raíz",
    "labelAnaliseDosPorques":"5 Porqués Análisis",
    "labelAnalisePriorizacaoSeAplicavel":"Análisis de Priorización (se aplicable)",
    "labelAntesDaInovacao":"Antes de la innovación (latas/tapas por minuto)",
    "labelApprover":"Responsable de Aprobación",
    "labelAprovacao":"Aprobación",
    "labelAprovar":"Aprobar",
    "labelARexamNaoTeraQueDesembolsarValoresParaATransportadora":"Rexam no es responsable de reembolsar al provedor",
    "labelAtuaSobreGargalo":"Acción sobre Cuello de la Botella",
    "labelBaixo":"Bajo",
    "labelCancelada":"Cancelado",
    "labelCargo":"Función",
    "labelCategorizacao":"Categorización",
    "labelCausa":"Causa",
    "labelCausas":"Causas",
    "labelCliente":"Cliente",
    "labelClienteCadastro":"Registro del cliente",
    "labelCodigoDoProduto":"Codigo de Producto",
    "labelComentariosDoCliente":"Comentarios de cliente",
    "labelConcluida":"Terminada",
    "labelConclusao":"Termino",
    "labelCondicoesAmbientaisOuClimaticas":"condiciones ambientales o climáticos",
    "labelCondicoesDoAmbienteDeTrabalhoInadequadas":"condiciones de trabajo inadecuadas",
    "labelContencao":"Acción de contención - acción inmediata para definir qué hacer con el lote afectado y/o sospechoso",
    "labelConteudoInadequado":"contenido inapropiado",
    "labelControlesAdministrativosAusentesOuInadequados":"Controles de gestión ausentes o inadecuadas",
    "labelCriacaoDeNocCliente":"Creación de NOC Cliente",
    "labelCriacaoDeProjetoInovacao":"Creación de Proyecto de Innovación",
    "labelCriacaoNocFornecedor":"Crear NOC Proveedor",
    "labelDadosDeAtendimentoReclamação":"Datos de tratamiento de reclamaciones",
    "labelDataAutorizacaoDevolucao":"Fecha de autorización de devolución",
    "labelDataAutorizacaoRessarcimento":"Fecha de aprobación de resarcimiento",
    "labelDataChegadaDoLoteDevoldidoAFabrica":"Fecha de recibimiento del producto devolvido",
    "labelDataDeAprovacaoPeloEspecialistaLean":"Fecha de aprobación de Especialista Lean",
    "labelDataDeAprovacaoPeloGerente":"Fecha de aprobación de Gerente",
    "labelDataDeAprovacaoPeloSuperiorImediato":"Fecha de aprobación de Superior Inmediato",
    "labelDataDeAprovaçãoPeloLiderLean":"Fecha de aprobación por el Líder Lean",
    "labelDataimplantacaoDoProjeto":"Fecha de implementación del proyecto",
    "labelDeficienciaNaOrganizaçãoELimpezaDaArea":"Deficiencia en la organización y limpieza de la zona",
    "labelDefinicaoDoProblema":"Fecha de Implementación del Proyecto ",
    "labelDepartamento":"Departamento ",
    "labelDepoisDaInovacao":"Después de la Innovación (latas/tapas por minuto)",
    "labelDescricaoDoProjeto":"Descripción del Proyecto",
    "labelDesperdicioAnoAntesDaInovacao":"Residuos del año (US$, antes de la innovación)",
    "labelDesperdicioAnoDepoisDaInovacao":"Residuos del año (US$, después de la innovación)",
    "labelDesperdicioMesAntesDaInovacao":"Residuos del mês (US$, antes de la innovación)",
    "labelDesperdicioMesDepoisDaInovacao":"Residuos del mês (US$, después de la innovación)",
    "labelDesvioDeProcedimentoOuRequisito":"Desviación de procedimiento o requisito",
    "labelDevolucao":"Devolución?",
    "labelDispatch":"Despacho",
    "labelEconomiaGeradaPorAno":"Ahorros generados por año (US$)",
    "labelEconomiaGeradaPorMes":"Ahorros generados por mês (US$)",
    "labelEmailParaNotificacoes":"Correo (e-mail) para informes",
    "labelEmAprovacao":"En aprobación",
    "labelEmRevisaoDeResposta":"Respuesta en revision",
    "labelEquipamentoMaterial":"Maquinaria / Materiales",
    "labelEquipamentoQueFalhou":"Maquinaria que fallo",
    "labelEquipeDoProjeto":"Equipo de Proyeto",
    "labelErroEmDesenhosEspecificacoesOuDados":"Error en los planos, especificaciones o datos",
    "labelEspecialistaLean":"Especialista Lean",
    "labelEspecialistaLeanQueAprovou":"Aprobado por Especialista Lean",
    "labelEspecificacaoDeMaterialOuDeEquipamentoInadequada":"Especificación de materiales o equipos inadecuados",
    "labelEsteProjetoEstaSendoImportadoDeOutraUnidade":"¿Este proyecto está siendo importada desde otra unidad?",
    "labelEstimativaDoCustoDaReclamacaoAtendimento":"Estimación de Costos del Servicio de Asistencia de Reclamos",
    "labelEstimativaDoCustoDaReclamacaoOutros":"Estimación de Costos de Asistencia de Reclamos / Otros",
    "labelFabrica":"Planta",
    "labelFabricaDevolucao":"Devolución origen Planta",
    "labelFalhaDoFornecedorDoEquipamentoOuMaterial":"Falla de materiales o equipos del proveedor",
    "labelFalhaNaComunicacaoInternaVerbalOuOutros":"Falla de comunicación interna (verbal / otros)",
    "labelFalhaNosMecanismosDeDeteccaoDeFalhas":"Falla en los mecanismos de detección",
    "labelFaltaDeAtencaoAosDetalhes":"Falta de atención a los detalles",
    "labelFaltaDeProcedimento":"Falta del procedimiento",
    "labelFaltaDeReciclagemPeriodica":"Falta de entreinamiento periódico",
    "labelFenomenosExternos":"Fenomenos Externos",
    "labelFornecedorCadastro":"Registro Provedores",
    "labelGanhosMensurados":"Ganancias medibles",
    "labelGanhosNaoMensurados":"Resultados obtenidos",
    "labelGanhosObtidos":"Ganancias de Hecho",
    "labelGerente":"Gerente",
    "labelGerenteQueAprovou":"Aprobado por Gerente",
    "labelGestao":"Gestión",
    "labelGrupoClassificacaoContabil":"Clasificación de grupo de cuenta contable",
    "labelHoraDeFabricacao":"Hora de producción",
    "labelHouveRiscosEliminadosPeloPeojeto":"Riesgos habia eliminado por el Proyecto?",
    "labelInadequadaSupervisao":"La supervisión inadecuada",
    "labelIncendioOuExplosaoExterna":"Fuego o explosión externa",
    "labelInformarLiderDoProjeto":"Dile que es El Proyecto del líder",
    "labelInformeUmaResposta":"Informar la respuesta",
    "labelInfraestrutura":"Infraestructura",
    "labelInovacaoAprovacaoDoSuperiorImediato":"Inovación - aprobación de Superior Inmediato",
    "labelInovacaoAprovacaoEspecialistaLean":"Inovación - aprobación de Especialista Lean",
    "labelInovacaoAprovacaoGerente":"Inovación - aprobación de Gerente",
    "labelInovacaoAprovacaoLiderLean":"Inovación - aprobación de Líder Lean",
    "labelInovacaoCadastro":"Fecha de aprobación de Superior Inmediato",
    "labelInovacaoHistorico":"Inovación - Historico",
    "labelInstalacoesInadequadas":"Instalaciones inadecuadas",
    "labelInterfaceHomemMaquinaInadequadas":"Interfaz hombre-máquina inadecuada",
    "labelInvestimentoDoProjeto":"La inversión del proyecto (en Reais)",
    "labelJustificativaDaReprovacao":"Justificación reprobación",
    "labelJustificativaReprovacao":"Justificación reprobación",
    "labelLider":"Líder",
    "labelLiderLean":"Líder Lean",
    "labelLiderLeanQueAprovou":"Aprobo Líder Lean",
    "labelManutencaoDasInstalacoesAusenteOuInadequada":"Mantenimiento de instalaciones faltantes o inadecuados",
    "labelMapaCausaRaiz":"Mapa de Causa Raíz",
    "labelmaterialDefeituoso":"Material defectuoso",
    "labelMaterialDeSuporteInadequado":"Material de apoyo inadecuado",
    "labelMatricula":"Registro",
    "labelMedio":"Promedio",
    "labelMetodologiaInadequada":"Metodología inadecuada",
    "labelMotivoCorrecao":"Correción razón",
    "labelNaoFoiFornecidoOTreinamento":"No fue hecha la capacitación",
    "labelNocCliente":"NOC del cliente",
    "labelNocInformativa":"NOC sólo para información",
    "labelNomeDoParticipante":"Nombre del participante",
    "labelNomeDoProjeto":"Nombre del Proyecto",
    "labelNotasRelevantes":"Observaciones importantes",
    "labelNovaCausa":"Nueva causa",
    "labelNovaPlanta":"Nueva planta",
    "labelOrganizacaoDoTrabalhoInadequada":"Organización del trabajo inadecuada",
    "labelOutrasEconomiasMensais":"Ahorro mensual generada (en Reais, no ligada a la pérdida de latas o tapas)",
    "labelOutrosFatoresHumanos":"Otros factores humanos",
    "labelOutroTipoDeDocumento":"Otro tipo de documento",
    "labelParecer":"Conclusión",
    "labelParecerDaAreaExterno":"Conclusión de Area Externa",
    "labelParecerDaAreaInterno":"Conclusión de Area Interna",
    "labelPessoal":"Personal",
    "labelPlanejamentoDoTrabalhoInadequado":"Planificación (trabajo) insuficiente",
    "labelPlantas":"Plantas",
    "labelPoliticaNaoAdequadamenteDefinidaDisseminadaOuRreforcada":"La política no definida o no diseminada correctamente",
    "labelPontosInovação":"Puntos de Innovación",
    "labelPontosMelhoria":"Puntos de Mejora",
    "labelPorQue1":"Porque 1",
    "labelPorQue2":"Porque 2",
    "labelPorQue3":"Porque 3",
    "labelPorQue4":"Porque 4",
    "labelPorQue5":"Porque 5",
    "labelPraticaInsuficienteDuranteOTreinamento":"Práctica insuficiente durante el entrenamiento",
    "labelPrensaMatriz":"Número de línea, máquina, matriz o cabezal",
    "labelProcedimento":"Procedimiento",
    "labelProcedimentoNaoClaroAmbiguoOuIncompleto":"Procedimiento no claro, ambiguo o incompleto",
    "labelProjeto":"Proyecto",
    "labelProjetoAprovado":"Proyecto Aprobado",
    "labelProjetoDesenvolvidoNaUnidade":"Proyecto DESARROLLADO en la Unidad",
    "labelProjetoReprovado":"Reprobado Proyecto",
    "labelProjetos":"Proyectos",
    "labelQual":"Cual?",
    "labelQuantidadeASerRessarcidaEmLata":"Cantidad a resarcir, en lata",
    "labelQuantidadeASerRessarcidaEmTampa":"Cuantidad de resarcimiento en tapa",
    "labelQuantidadeAutorizadaDevolver":"Cantidad aprobada por devolución",
    "labelQuantidadeDeAprovados":"Número de aprobados",
    "labelQuantidadeDeExpirados":"Número de Proyectos obsoletos",
    "labelQuantidadeDeInscritos":"Los Suscriptores amount",
    "labelQuantidadeDeReprovados":"Número de Proyectos reprobado",
    "labelQuantidadeDevolvida":"Cantidad real recibida en devolución",
    "labelQuantidadeemAprovacao":"Cuantidad en aprobación",
    "labelQuantidadeLatasTampasPerdidas":"Cantidad de latas / tapas perdidas",
    "labelRelatorioDeParticipantes":"Dígales a los participantes",
    "labelRepostaDoFornecedor":"Respuesta de Proveedor",
    "labelReprovar":"Reprobar",
    "labelResponder":"Responder",
    "labelPerguntaResponder":"Responder?",
    "labelRespostaRexam":"Respuesta de Rexam",
    "labelRouboAssaltoVandalismo":"Robo, asalto, vandalismo",
    "labelSelecioneAnaliseDePriorizacao":"Seleccione el análisis de priorización",
    "labelSeuProjetoEstaVinculadoPerdaDeLatasTampas":"Su Diseño latas con asociados La Perdida / tapas?",
    "labelSolicitarCorrecao":"Solicitar corrección",
    "labelSolucoesImplementadas":"Implementado Soluciones",
    "labelSuperiorImediato":"Supervisor",
    "labelSuperiorImediatoQueQprovou":"Supervisor que aprobo",
    "labelSupervisorResponsavel":"Supervisor de Responsable",
    "labelSuprimentoDeEnergiaOuAguaInadequados":"Fuente de alimentación o agua inadecuado",
    "labelTipoDeDocumento":"Tipo de Documento",
    "labelTipodeProjeto":"Tipo de proyecto",
    "labelTotalDeCreditos":"créditos totales",
    "labelTraducaoDoFato":"Traducción de ocurrencia",
    "labelTreinamento":"Entrenamiento",
    "labelTurma":"Clase",
    "labelUnidade":"Unidad",
    "labelUnidadeDoParticipante":"Unidad del participante",
    "labelUnidadeDoProjeto":"Unidad del Proyecto",
    "labelUnidadesPerdidasPorAnoAntesDaInovacao":"Unidades perdieron al Año (antes Innovación)",
    "labelUnidadesPerdidasPorAnoDepoisDaInovacao":"Unidades perdieron al Año (despues de la Innovación)",
    "labelUnidadesPerdidasPorMesAntesDaInovacao":"Unidades perdidas por mes (antes Innovación)",
    "labelUnidadesPerdidasPorMesDepoisDaInovacao":"Unidades perdidas por mes (despues de la Innovación)",
    "labelValorDaLataTampa":"Valor de la Lata / Tampa",
    "labelValorDoFrete":"La tarifa de transporte/flete",
    "labelValorInovacao":"Valor de la innovación que",
    "labelValorMelhoria":"Es Mejora valor",
    "labelValorTotal":"Valor total",
    "optionCliente":"Seleccione Cliente",
    "optionFabrica":"Seleccione la fábrica",
    "optionInovacao":"Innovación",
    "optionMelhoria":"Mejora",
    "optionProjeto":"Proyecto Dile",
    "optionResposta":"Respuesta",
    "optionSelecioneACausaRaiz":"Seleccione la causa raíz",
    "optionSelecioneAEtapaParaQualDesejaDevolver":"Seleccione el paso al cual regresar",
    "optionSelecioneATurma":"Seleccione la clase",
    "optionSelecioneFabricaDevolucao":"Seleccione la fábrica para devolución",
    "optionSelecioneParecer":"Seleccione la opción segun la asistencia",
    "optionSelecioneTipoDeProjeto":"Seleccione el tipo de proyecto",
    "optionSupervisorResponsavel":"Seleccione el supervisor del responsable",
    "optionTipoDeDocumento":"Seleccione el tipo de documento",
    "optionUnidadeDoParticipante":"Seleccione la Unidad del participante",
    "optionUnidadeOndeProjetoFoiDesenvolvido":"Seleccione la Unidad en la que el Proyecto Desarrollo",
    "placeAnaliseDoProblemaESuasCausas":"Análisis de causa raíz",
    "placeAntesDaInovacao":"Antes de Implementación de Proyecto de Innovación",
    "placeCausa":"Causa",
    "placeCodigoDoProduto":"Codigo de Producto",
    "placeComentarios":"Comentarios",
    "placeComentariosDoCliente":"Comentarios de cliente",
    "placeConclusao":"Termino",
    "placeContencao":"Acción de contención - acción inmediata para definir qué hacer con el lote afectado y/o sospechoso",
    "placeDadosDeAtendimentoReclamação":"Llame a los datos de la denuncia",
    "placeDefinicaoDoProblema":"Definición del problema",
    "placeDepoisDaInovacao":"Despues la Innovación (latas / tapas por minuto)",
    "placeEmailParaNotificacoes":"Introduzca El Correo electrónico de notificaciones",
    "placeEstimativaDoCustoDaReclamacaoAtendimento":"Estimación de Costos de asistencia a reclamo",
    "placeEstimativaDoCustoDaReclamacaoOutros":"Estimación de Costos de reclamo/otros",
    "placeGanhosNaoMensurados":"DILE resultados obtenidos",
    "placeGrupoClassificacaoContabil":"Seleccione la clasificación de grupo de cuenta contable",
    "placeHoraDeFabricacao":"Fabricante tiempo",
    "placeInformeJustificativaDeReprovacao":"Introduzca su justificación de falla",
    "placeInvestimentoDoProjeto":"Dile a la inversión del proyecto (en reales)",
    "placeMotivoCorrecao":"DILE la Razón de Corrección",
    "placeNomeDoProjeto":"Introduzca el nombre del Proyecto",
    "placeNotasRelevantes":"Notas Relevantes",
    "placeOutrasEconomiasMensais":"Ahorro generada Mensual Dile (en reales no ligado a la pérdida de latas o tapas)",
    "placeOutroTipoDeDocumento":"Otro tipo de documento",
    "placeParecerDaAreaExterno":"Conclusión de Area Externa",
    "placeParecerDaAreaInterno":"Conclusión de Area Interna",
    "placePorQue1":"Porque 1",
    "placePorQue2":"Porque 2",
    "placePorQue3":"Porque 3",
    "placePorQue4":"Porque 4",
    "placePorQue5":"Porque 5",
    "placePrensaMatriz":"Número de línea, máquina, matriz o cabezal",
    "placeQual":"Cual?",
    "placeQuantidadeASerRessarcidaEmLata":"Cantidad a resarcir, en lata",
    "placeQuantidadeASerRessarcidaEmTampa":"Cuantidad de resarcimiento en tapa",
    "placeQuantidadeAutorizadaDevolver":"Cantidad aprobada por devolución",
    "placeQuantidadeDevolvida":"Cantidad real recibida en devolución",
    "placeQuantidadeLatasTampasPerdidas":"Cantidad de latas / tapas perdidas",
    "placeSolucoesImplementadas":"Implementado Soluciones",
    "placeTraducaoDoFato":"Traducción de ocurrencia",
    "placeTurma":"Equipo de trabajo (turno)",
    "placeUnidadeDoProjeto":"Introduzca la Unidad del Proyecto",
    "placeValorDoFrete":"La tarifa de transporte/flete",
    "tituloEquipeDoProjeto":"Equipo del Proyecto",
    "validacaoAlocacaoDeRecursosDeficienteFaltaDeRecursos":"Indique si hubo Asignación de Recursos Deficiente / Falta de Recursos",
    "validacaoAnaliseDoProblemaESuasCausas":"Informe de Análisis de causa raíz",
    "validacaoCausa":"Indique la causa",
    "validacaoCliente":"Indique el Cliente",
    "validacaoClienteEnvasadoraProdutoAcabado":"Embotelladora / Producto terminado?",
    "validacaoComentariosDoCliente":"Indique los comentarios de cliente",
    "validacaoConclusao":"Ingrese el Conclusión",
    "validacaoCondicoesAmbientaisOuClimaticas":"Indique condiciones ambientales o climáticos",
    "validacaoCondicoesDoAmbienteDeTrabalhoInadequadas":"Informar si había condiciones de trabajo inadecuadas",
    "validacaoConteudoInadequado":"Informar si había contenido inapropiado",
    "validacaoControlesAdministrativosAusentesOuInadequados":"Indique si ha habido falta o inapropiado controles administrativos",
    "validacaoDadosDeAtendimentoReclamação":"Dígale al servicio de los datos de la denuncia",
    "validacaoDataAutorizacaoRessarcimento":"Introduzca la compensación autorización Fecha",
    "validacaoDataChegadaDoLoteDevoldidoAFabrica":"Indique la fecha de recibimiento del producto devolvido",
    "validacaoDataimplantacaoDoProjeto":"Informar la fecha de implementación de proyecto",
    "validacaoDeficienciaNaOrganizaçãoELimpezaDaArea":"Indique si existe deficiencia en la organización y limpieza de la zona",
    "validacaoDefinicaoDoProblema":"Introduzca la Definición del problema",
    "validacaoDesvioDeProcedimentoOuRequisito":"Indique si hubo Desviación de procedimiento o requisito",
    "validacaoDevolucao":"Decir si es devolución",
    "validacaoEmailParaNotificacoes":"Introduzca El Correo electrónico de notificaciones",
    "validacaoEquipamentoQueFalhou":"Indique si Maquinaria que falla",
    "validacaoErroEmDesenhosEspecificacoesOuDados":"Indique si hubo error en los planos, especificaciones o datos",
    "validacaoEspecificacaoDeMaterialOuDeEquipamentoInadequada":"Indique si ha habido falta o inapropiado especificaciones de materiales o equipo",
    "validacaoEsteProjetoEstaSendoImportadoDeOutraUnidade":"Decirle este Proyecto está cuidando Unidad de otra",
    "validacaoEstimativaDoCustoDaReclamacaoAtendimento":"Indique Estimación de Costos de asistencia a reclamo",
    "validacaoEstimativaDoCustoDaReclamacaoOutros":"Indique Estimación de Costos de reclamo/otros",
    "validacaoEtapaParaQualDesejaDevolver":"Indique el paso al cual regresar",
    "validacaoFabrica":"Indique la fábrica",
    "validacaoFabricaDevolucao":"Indique la fábrica para devolución",
    "validacaoFalhaDoFornecedorDoEquipamentoOuMaterial":"Indique si hubo falla de materiales o equipos del proveedor",
    "validacaoFalhaNaComunicacaoInternaVerbalOuOutros":"Indique la Falla de comunicación interna (verbal / otros)",
    "validacaoFalhaNosMecanismosDeDetecçãoDeFalhas":"Indique si hubo fallo en los mecanismos de detección de fallos",
    "validacaoFaltaDeAtencaoAosDetalhes":"Indique si hubo Falta de atención a los detalles",
    "validacaoFaltaDeProcedimento":"Indique si hubo Falta del procedimiento",
    "validacaoFaltaDeReciclagemPeriodica":"Indique si hubo Falta de entreinamiento periódico",
    "validacaoGanhosNaoMensurados":"Dile resultados obtenidos",
    "validacaoGrupoClassificacaoContabil":"Seleccione la clasificación de grupo de cuenta contable",
    "validacaoHoraDeFabricacao":"Indique la hora de producción",
    "validacaoHoraDeOcorrencia":"Indique la hora de ocurrencia",
    "validacaoInadequadaSupervisao":"Informar si hubo una gestión inadecuada",
    "validacaoIncendioOuExplosaoExterna":"Indique si hubo fuego o explosión externa",
    "validacaoInformeAEtapaParaQualDesejaDevolver":"Dígale al paso al que volver",
    "validacaoInformeCategoria":"Introduzca su categoría",
    "validacaoInformeJustificativaDeReprovacao":"Dile a la justificación Fracaso",
    "validacaoInformeSeDesejaAprovar":"Digale si aprobar",
    "validacaoInstalacoesInadequadas":"Informar si había Instalaciones inadecuadas",
    "validacaoInterfaceHomemMaquinaInadequadas":"Interfaz hombre-máquina inadecuada",
    "validacaoInvestimentoDoProjeto":"Dile a Proyectos de Inversión (en reales)",
    "validacaoManutencaoDasInstalacoesAusenteOuInadequada":"Informar si había Mantenimiento de instalaciones faltantes o inadecuados",
    "validacaoMaterialDefeituoso":"Indique si hubo material defectuoso",
    "validacaoMaterialDeSuporteInadequado":"Indique si existe material de apoyo inadecuado",
    "validacaoMetodologiaInadequada":"Indique si hubo Metodología inadecuada",
    "validacaoMotivoCorrecao":"Dile a Razón de Corrección",
    "validacaoNaoExistemDadosCadastrados":"Hay realmente no hay datos",
    "validacaoNaoFoiFornecidoOTreinamento":"Indique si no fue hecha la capacitación",
    "validacaonidadeDoProjeto":"Introduzca la Unidad del Proyecto",
    "validacaoNomeDoProjeto":"Introduzca el nombre del Proyecto",
    "validacaoOrganizacaoDoTrabalhoInadequada":"Indique si hubo Organización del trabajo inadecuada",
    "validacaoOutrasEconomiasMensais":"Ahorro generada Mensual Dile (en reales no ligado a la pérdida de latas o tapas)",
    "validacaoOutrosFatoresHumanos":"Indique si hubo otros factores humanos",
    "validacaoOutroTipoDeDocumento":"Indique Otro tipo de documento",
    "validacaoParecerDaAreaExterno":"Indique la Conclusión de Area Externa",
    "validacaoParticipante":"Seleccione el participante",
    "validacaoPerdaAntesDaInovacao":"Introduzca perdida antes Innovación (latas / tapas por minuto)",
    "validacaoPerdaDepoisDaInovacao":"Introduzca su loss despues de Innovación (latas / tapas por minuto)",
    "validacaoPlanejamentoDoTrabalhoInadequado":"Indique si hubo Planificación (trabajo) insuficiente",
    "validacaoPoliticaNaoAdequadamenteDefinidaDisseminadaOuRreforcada":"Indique si la política no estaba definida o no diseminada correctamente",
    "validacaoPorQue1":"Indique Porque 1",
    "validacaoPorQue2":"Indique Porque 2",
    "validacaoPorQue3":"Indique Porque 3",
    "validacaoPraticaInsuficienteDuranteOTreinamento":"Indique si hubo práctica insuficiente durante el entrenamiento",
    "validacaoPrensaMatriz":"Indique el número de línea, máquina, matriz o cabezal",
    "validacaoProcedimentoNaoClaroAmbiguoOuIncompleto":"Indique si hubo Procedimiento no claro, ambiguo o incompleto",
    "validacaoProjeto":"Dile El Proyecto",
    "validacaoQual":"Introduzca Cual",
    "validacaoQuantidadeASerRessarcidaEmLata":"Ingresse la Cantidad a resarcir, en lata",
    "validacaoQuantidadeASerRessarcidaEmTampa":"Ingresse la Cuantidad de resarcimiento en tapa",
    "validacaoQuantidadeAutorizadaDevolver":"Ingresse la Cantidad aprobada por devolución",
    "validacaoQuantidadeDevolvida":"Ingresse la Cantidad real recibida en devolución",
    "validacaoResposta":"Ingrese una respuesta",
    "validacaoRessarcimento":"Tener Reembolso?",
    "validacaoRouboAssaltoVandalismo":"Indique si hubo Robo, asalto, vandalismo",
    "validacaoSelecioneATurma":"Introduzca clase",
    "validacaoSolucoesImplementadas":"Introduzca las Soluciones implementadas",
    "validacaoStatus":"Diga Status",
    "validacaoSupervisorResponsavel":"El supervisor Introduzca su",
    "validacaoSuprimentoDeEnergiaOuAguaInadequados":"Indique si había Fuente de alimentación o agua inadecuado",
    "validacaoTipoDeDocumento":"Indique Tipo de Documento",
    "validacaoTipodeProjeto":"Introduzca el tipo de proyecto",
    "validacaoTraducaoDoFato":"Indique la traducción de ocurrencia",
    "validacaoUnidadeDoParticipante":"Seleccione la Unidad del participante",
    "validacaoValorDoFrete":"Indique la tarifa de transporte/flete",
    "validacaUnidadeOndeProjetoFoiDesenvolvido":"Digale a la Unidad en la que el Proyecto Desarrollo",
    "validaCodigoDoProduto":"Indique el código de producto",
    "labelHistoricoDeAprovacoes":"Historia de aprobación",
    "labelAguardandoDispatch":"A la espera de la entrega",
    "labelAguardandoAprovacao":"A la espera de la aprobación",
    "labelAprovado":"Bueno",
    "labelReprovado":"Fallar",
    "labelLogar":"Registrarse",
    "labelCPF":"Número de Identificación",
    "labelSenha":"Contraseña",
    "validacaoUsuario":"Introduzca su nombre de usuario.",
    "validacaoSenha":"Ingrese su Contraseña.",
    "labelEsqueciSenha":"¿Te ha olvidado? Contraseña",
    "labelEsqueciSenha1":"Usted se ha olvidado de Contraseña",
    "labelContinuarLogado":"Mantener el acceso acceso",
    "labelNovaConta":"Crear Cuenta una",
    "labelPrecisaNovaConta":"¿Una Cuenta need?",
    "labelResetPassword":"Restablecer Contraseña",
    "placeUsuario":"Escriba su CPF.",
    "labelLembreiSenha":"Recordar mi contraseña !",
    "labelMatricula":"Registro",
    "placeMatricula":"Introduzca su registro",
    "validacaoMatricula":"Escriba su registro.",
    "labelDataNascimento":"Cierra nacimiento",
    "validacaoDataNascimento":"Ingrese su fecha de nacimiento.",
    "labelValidarInformacoes":"Información Validar",
    "labelChangePassword":"Cambie La Contraseña",
    "labelInfoUsuario":"Una nueva Contraseña Introduzca a",
    "labelNewPassword":"Nueva Contraseña",
    "validacaoNewPassword":"Ingrese su Contraseña nueva.",
    "labelConfirmNewPassword":"Confirmar Contraseña nueva",
    "validacaoConfirmNewPassword":"Confirme su nueva Contraseña.",
    "validacaoPasswordsNotMatch":"Las Contraseñas en coinciden.",
    "labelPossuiRegistro":"Ya ha está registrado?",
    "labelContinuar":"Continuar",
    "labelCNPJ":"CNPJ",
    "labelEmail":"Correo Electrónico",
    "labelEmailNFE":"Correo Electrónico NFE",
    "labelEmailRecuperacao":"Por favor introduzca la corrección electrónica Dirección de recuperar la Contraseña",
    "labelE":"Y",
    "labelRecuperarSenha":"Recuperar Contraseña",
    "validacaoMotivo":"Ingrese razón",
    "labelNomeRepresentante":"Nombre del representante",
    "placeNomeRepresentante":"Nombre del representante",
    "validacaoNomeRepresentante":"Introduzca el nombre del representante",
    "labelResumoOcorrencia":"Resumen de ocurrencias",
    "placeResumoOcorrencia":"Resumen de ocurrencias",
    "validacaoResumoOcorrencia":"Dile Resumen de ocurrencias",
    "validacaoDataAutorizacaoDevolucao":"Introduzca la fecha de autorización para la devolución",
    "labelCPM":"CPM",
    "tituloSemCadastroDePontos":"Registro de los puntos que faltan",
    "msgSemCadastroDePontos":"Póngase en contacto con el Lean Enterprise (leaninforma@rexam.com)",
    "labelNovaAcao": "Nova Ação",
    "placeCausas": "Informe uma causa",
    "validacaoCausas": "Informe uma causa",
    "labelAcaoCorrespondente": "Ação Correspondente",
    "placeAcaoCorrespondente": "Informe a ação correspondente",
    "validacaoAcaoCorrespondente": "Informe a ação correspondente",
    "placeResponsavel": "Informe o responsável",
    "validacaoResponsavel": "Informe o responsável",
    "labelPrazo": "Prazo",
    "validacaoPrazo": "Informe o Prazo",
    "labelPrazoExecucao": "Prazo de Execução",
    "labelAcao": "Ação",
    "labelPlanoDeAcao": "Plano de Ação",
    "labelEtapaAnaliseInicial": "Análise Inicial e Ações Imediatas",
    "labelEtapaPlanoDeAcao": "Plano de Ação e Conclusão",
    "labelCodigoPlanoAcao": "Código Plano de Ação",
    "labelUrlCodigoPlanoAcao": "Url Plano de Ação",
    "placeCodigoPlanoAcao": "Informe o Código Plano de Ação",
    "validacaoCodigoPlanoAcao": "Informe o Código Plano de Ação",
    "obsCbuBancos":"(Sólo necesario para Argentina y Perú)",
    "labelPedirCorrecaoSolicitante":"Enviar para revisión del solicitante",
    "validacaoContencao":"Informar la contención",
	"optionLatas":"Latas",
	"optionTampas":"Tapas",
	"labelAcaoDeDeteccao":"Acción de Detección - ¿Por qué no se detectó y fue retenido el defecto internamente?",
	"placeAcaoDeDeteccao":"Acción de Detección - ¿Por qué no se detectó y fue retenido el defecto internamente?",
    "labelNumeroDoDocumento":"Número del documento",
    "placeNumeroDoDocumento":"Número del documento",
    "excelSaudeSeguranca": "Salud y Seguridad",
    "excelMeioAmbiente":"Medio Ambiente",
    "excelSegurancaAlimentos": "Inocuidad",
    "excelTituloAnexo": "ANEXO - ACCION CORRECTIVA Y PREVENTIVA (RESPUESTA DE RECLAMO DE CLIENTE)",
    "excelDadosDescricao": "00 - DATOS Y DESCRIPCION DE OCURRENCIA",
    "excelDefeitoReclamado": "Defecto Reclamado:",
    "excelCodLataTampa": "Cod. Lata-Tampa (nº lote):",
    "excelDataOcorrencia": "Fecha de Ocurrencia:",
    "excelDataFabricacao": "Fecha - Produción:",
    "excelNotaFiscal":"Factura:",
    "excelQuantidadeReclamadaRetida": "Cantidad Reclamada:",
    "excelDescricaoDesvio": "Descripción del Desvio:",
    "excelTraducaoFato": "Descripción del Evento: (constatación despues de la atención de Ball)",
    "excelNotasRelevantes": "Notas Importante (máquina, area, proceso, complemento del origen de la falla, etc)",
    "excelPreenchidoPor": "Preenchido por:",
    "excelDataPreenchidoPor": "Fecha:",
    "excelAcaoContencaoDeteccao": "01 - ACCIÓN DE CONTENCIÓN Y DETECCIÓN",
    "excelAcaoContencao": "Acción de contención – Acción imediata sobre el lote afectado o sospechoso:",
    "excelAcaoDeteccao": "Detección – Debido a que el defecto no se detecto internamente?",
    "excelConfirmacaoCausas": "02 - DEFINICION DE LAS ACCIONES PARA LA CAUSA RAIZ / DIRECTA O POTENCIAL",
    "excelConfirmacaoAcao": "ACCIÓN:",
    "excelConfirmacaoResponsavel": "RESPONSABLE:",
    "excelConfirmacaoPrazo": "PLAZO:",
    "excelConclusao": "03 - CONCLUSION",
    "excelConclusaoParecerProcedencia": "PARECER: (PROCEDENCIA)",
    "excelConclusaoComentarios": "COMENTARIOS DEL PARECER:",
    "excelConclusaoRessarcimento": "REEMBOLSO? (S/N)",
    "excelConclusaoDevolucao":"DEVOLUCIÓN? (S/N)",
    "excelConclusaoQuantidadeAutorizadaRessarcimento": "Cantidad autorizada a ser reembolsada:",
    "excelConclusaoQuantidadeAutorizadaDevolvida":"Cantidad autorizada a ser devuelta:",
    "liSalvarRascunho":"Grabar Rascunho",
    "liExportarExcel":"Exportar Excel",
    "excelTitulo":"TÍTULO:",
	"LabelDigito":"Dígito"
}
































