{
    "msgDadosBancarios": "Informe os dados bancários",
    "msgEmpresas": "Informe pelo menos uma empresa",
    "msgConcluido": "Concluído com sucesso!",
    "msgLider": "A equipe do projeto precisa ter um líder.",
    "msgEdicaoNaoEncontrada": "Não existe uma edição programada para criação de projetos de inovação.",
    "msgEntrarContatoLean": "Caso seja necessário, entre em contato com a área LEAN.",
    "msgPedidoAprovacaoExpirou": "O período de aprovações de projetos dessa edição expirou.",
    "msgPedidoCriacaoExpirou": "O período de criação de projetos dessa edição expirou.",
    "msgEquipe": "Informe os membros da equipe.",
    "msgSucesso": "Sucesso",
    "msgSenhaAlterada": "Senha alterada.",
    "msgSemDadosParaEdicao": "Não foram encontrados dados para a edição selecionada",
    "msgUsuarioNaoLocalizado": "Usuário não localizado",
    "msgUsuarioNaoCadastrado": "Usuário com e-mail não cadastrado.",
    "msgAnaliseDasCausas":"Informe pelo menos uma causa",
    "msgPlanoDeAcao":"Inclua pelo menos uma ação",
    "msgArquivoObrigatorio":"Inclua pelo menos um anexo",
    "tituloEmailRecuperacaoSenha": "Recuperação de Senha - Rexam Workflow",
    "tituloEmailResetPassword": "Senha reiniciada - Workflow Rexam",
    "tituloEmailBoasVindas": "Bem vindo ao Rexam Workflow",
    "tituloEdicaoNaoEncontrada": "Nenhuma edição programada",
    "tituloPedidoAprovacaoExpirou": "Período de aprovação expirou",
    "tituloPedidoCriacaoExpirou": "Período de criação expirou",
    "tituloRelatorioPlantasInovacao": "Relatório de Plantas",
    "labelAceite": "Aceite",
    "labelAceiteFornecedor": "Aceite do Fornecedor",
    "labelAcoesCorretivasPreventivas": "Ações Corretivas e Preventivas",
    "labelAcoesCorretivas": "Ações Corretivas",
    "labelAcoesPreventivas": "Ações Preventivas",
    "labelAcompanhamentoFornecedor": "Houve acompanhamento do fornecedor?",
    "labelAgenteFrete": "Agente Frete",
    "labelAplicarReembolso": "Aplicar Reembolso",
    "labelArquivos": "Arquivos",
    "labelBairro": "Bairro",
    "labelCadastro": "Cadastro",
    "labelCadastroSap":"Cadastro SAP",
    "labelCalculo": "Cálculo",
    "labelCalculoReembolsoFinanceiro": "Cálculo Reembolso Financeiro",
    "labelCanalDeDistribuicao": "Canal de Distribuição",
    "labelCategoria": "Categorias",
    "labelCausaRaiz": "Causa Raiz",
    "labelCentroDeFornecimento": "Centro de Fornecimento",
    "labelCEP": "CEP",
    "labelCidade": "Cidade",
    "labelClasse": "Classe",
    "labelCodigoClienteSAP": "Código Cliente SAP",
    "labelCodigoFiscal": "Código Fiscal",
    "labelCodigoFiscalLogin": "CNPJ",
    "labelCodigoMetal": "Código do Metal",
    "labelCodigoProdutoFornecedor": "Código do Produto Fornecedor",
    "labelCodigoProdutoSAP": "Código do Produto SAP",
    "labelCoef": "Coef.(Kg/m):",
    "labelComentarioRexam": "Comentários Adicionais da Rexam",
    "labelComentarios": "Comentários",
    "labelComentariosDaOcorrencia": "Comentários da ocorrência",
    "labelComplementoEndereco": "Complemento",
    "labelCondicaoDaExpedicao": "Condição da Expedição",
    "labelCondicaoDePagamento": "Condição de Pagamento",
    "labelContaConciliatoria":"Conta Conciliatória",
    "labelCriarNOC": "Criar NOC",
    "labelCustosDespesas": "Outros custos adicionais a latas perdidas e horas paradas",
    "labelCustosFerramentas": "Custos Ferramentas (US$):",
    "labelDataAprovacao":"Data de Aprovação",
    "labelDadosContabeis":"Dados Contábeis",
    "labelDadosFiscais":"Dados Fiscais",
    "labelDataAbertura": "Data de Abertura",
    "labelDataAceite": "Data de Aceite",
    "labelDataEntrada": "Data Recebimento do Metal",
    "labelDataFabricacao": "Data de Fabricação",
    "labelDataFaturamentoFornecedor": "Data de Fat. do Fornecedor",
    "labelDataOcorrencia": "Data de Ocorrência",
    "labelDataRecebimentoMetal": "Data de Recebimento do Metal",
    "labelDataResposta": "Data da Resposta",
    "labelDataEncerramento": "Data de encerramento",
    "labelDetalhesOutrasPerdas": "Detalhar outras perdas *",
    "labelDetalhesPerdaFerramenta": "Detalhar perda ferramental",
    "labelDetalhesProblema": "Detalhes do Problema",
    "labelEmailDeCobranca": "E-mail de cobrança",
    "labelEmailEnviado": "E-mail com a senha enviado para ",
    "labelEmpresa": "Empresa",
	"labelEmpresas": "Empresas",
    "labelEtapa1": "Etapa 1",
    "labelEtapa2": "Etapa 2",
    "labelEtapa3": "Etapa 3",
    "labelEtapa4": "Etapa 4",
    "labelFisica": "Física",
    "labelFormaDePagamento": "Forma de Pagamento",
    "labelFornecedor": "Fornecedor",
    "labelGerouDrenoLinha": "O defeito gerou dreno de linha?",
    "labelGerouPerdaProducao": "O defeito gerou perda de produção?",
    "labelGrupoAdmTesouraria":"Grupo ADM tesouraria",
    "labelGrupoDeCliente": "Grupo de cliente",
	"labelGrupoDeClientes": "Grupo de clientes",
    "labelGrupoDeContas": "Grupo de contas",
    "labelGrupoDePreco": "Grupo de preço",
    "labelGrupoDeVendedores": "Grupo de vendedores",
    "labelHistorico": "Histórico",
    "labelHoraDeOcorrencia": "Hora de Ocorrência",
    "labelIncoterm": "Incoterm",
    "labelInformacoesGerais": "Informações gerais",
    "labelInscricaoEstadual": "Inscrição estadual",
    "labelInscricaoMunicipal": "Inscrição municipal",
    "labelJuridica": "Jurídica",
    "labelKGs": "Copos em KGs :",
    "labelLogradouro": "Logradouro",
    "labelLote": "Lote",
    "labelMoeda": "Moeda",
    "labelMoedaContabilizacao":"Moeda de contabilização",
    "labelMotivoDaSolicitacao": "Motivo da solicitação",
    "labelNao": "Não",
    "labelNomeCliente": "Nome cliente",
    "labelNomeDeBusca": "Nome de Busca",
    "labelNomeEmissorNoc": "Nome do Emissor da NOC",
    "labelNotaFiscal": "Nota Fiscal",
	"labelNovaEmpresa":"Nova empresa",
    "labelNovoGrupoClientes": "Novo código grupo clientes",
    "labelNovoGrupoPreco": "Novo código grupo preço",
    "labelNovoZonaTransporte": "Novo código zona de transporte",
    "labelNumeroCartaoHFI": "Nº do Cartão HFI",
    "labelNumeroCliente":"Número Cliente",
    "labelNumeroEndereco": "Número",
    "labelObservacao": "Observação",
    "labelOrganizacaoDeVendas": "Organização de Vendas",
    "labelOutrasPerdasCustos": "Houve outras perdas ou outros custos? (APENAS EM CASO DE CRISE E ACORDADO COM O CORPORATIVO)",
    "labelOutrosCustos": "Outros Custos (US$):",
    "labelPaisDoCliente": "País do Cliente",
    "labelPaisRexam": "País da Rexam",
    "labelParecerPrevio": "Parecer prévio Rexam",
    "labelPassoFinanceiro":"Passo Financeiro",
    "labelPedidoCorrecao":"Pedido de Correção",
    "labelPerdaFerramenta": "Houve perda de ferramenta? (APENAS EM CASO DE CRISE E ACORDADO COM O CORPORATIVO)",
    "labelPerdasMetal": "Custo Metal Perdido (US$):",
    "labelPerdasProducao": "Custo de Produção (US$):",
    "labelPerdaTotal": "Perda Total (US$):",
    "labelPesoReclamada": "Peso Reclamado (Kg)",
    "labelPesoTotalBobina": "Peso Total da Bobina (Kg)",
    "labelPlacaVeiculo": "Placa Veículo",
    "labelPlanta": "Planta",
    "labelPrecoCompra": "Preço de Compra (US$/ton):",
    "labelPrecoVenda": "Preço de Venda (US$/ton):",
    "labelQtdAmostrasEnviadasFornecedor": "Qtd. Amostras Enviadas ao Fornecedor:",
    "labelQtdProdutosPerdidos": "Qtd. Copos (Unid.) :",
    "labelQtsLatasTampas": "Quantas Latas e/ou Tampas?",
    "labelQuantidadeAmostrasEnviadasFornecedor": "Qtd. Amostras Enviadas ao Forn. (meia-lata ou chapa)",
    "labelQuantidadeRetida": " Quantidade retida",
    "labelQuantidadeRetornoFornVenda": "Qtd. Retorno Fornecedor/Venda",
    "labelRecebedorMercadoria": "Recebedor da Mercadoria",
    "labelRecebedorMercadoriaDiferente": "Recebedor de mercadoria diferente deste cadastro?",
    "labelReembolsoToral": "Reembolso Total (US$):",
    "labelRegiao": "Estado",
    "labelRegiaoDeVendas": "Região de Vendas",
    "labelResponsavel": "Responsável",
    "labelResposta": "Resposta",
    "labelRessarcimento": "Ressarcimento",
    "labelReteste": "Houve reteste?",
    "labelRetornoIndicadorRetornoVenda": "Indicador de Retorno ou Venda",
    "labelSelecioneStatus": "Selecione o Status",
    "labelSetorDeAtividade": "Setor de Atividade",
    "labelSetorIndustrial":"Setor Industrial",
    "labelSeveridade": "Severidade",
    "labelSim": "Sim",
    "labelStatusAprovacao": "Status Aprovação",
    "labelTelefone": "Telefone",
    "labelTipoDePessoa": "Tipo de Pessoa",
    "labelTipoDeServico": "Tipo de Serviço",
    "labelTipoMetal": "Tipo de Metal",
    "labelTipoProblema": "Tipo Problema",
    "labelTituloDefeito": "Defeito",
    "labelTituloCriticidade": "Criticidade",
    "labelUnidadeMedida": "Unidade de Medida",
    "labelUnidadeRetida": " Unidade de medida retida",
    "labelUploadArquivos": "Upload de Arquivos",
    "labelValor": "Valor: US$",
    "labelZonaDeTransporte": "Zona de Transporte",
    "labelExDocumentoBancario": "(Ex: Cópia de cheque; Extrato bancário contendo NOME AG e CC)",
    "labelEdicao": "Edição",
    "labelParticipante": "Participante",
    "liAceitar": "Aceitar",
    "liAnterior": "Anterior",
    "liCliente":"Cliente",
    "liDevolver":"Devolver",
    "liProximo": "Próximo",
    "liRexam":"Rexam",
    "liSalvar": "Enviar",
    "optionCategoriaMaterialDireto": "Material Direto",
    "optionCategoriaMaterialIndireto": "Material Indireto",
    "optionCategoriaServicos": "Serviços",
    "optionCategoriaTransporte": "Frete/Movimentação Interna",
    "optionDevolucao": "Devolução (Metal origem venda direta)",
    "optionMoedaContabilizacao": "Selecione a moeda de contabilização",
    "optionZonaDeTransporte": "Selecione um valor para o campo Zona de Transporte",
    "optionNovoGrupoDeClientes": "Novo grupo de clientes",
    "optionNovoGrupoDePreco": "Novo grupo de preço",
    "optionSelecioneCategoria": "Selecione um valor para o campo Categoria",
    "optionSelecioneCausaRaiz": "Selecione um valor para o campo Causa Raiz",
    "optionSelecioneCentroDeFornecimento": "Selecione um valor para o campo Centro de Fornecimento",
    "optionSelecioneClasse": "Selecione um valor para o campo Classe",
    "optionSelecioneClassificacaoFiscal":"Selecione a classificação fiscal",
    "optionSelecioneCodMetal": "Selecione um valor para o campo Código Metal",
    "optionSelecioneCondicaoExpedicao": "Selecione um valor para o campo Condição de Expedição",
    "optionSelecioneCondicaoPagamento": "Selecione um valor para o campo Condição de Pagamento",
    "optionSelecioneContaConciliatoria":"Selecione a conta conciliatória",
    "optionSelecioneDefeito": "Selecione um valor para o campo Defeito",
    "optionSelecioneEmpresas": "Selecione um ou mais valores para o campo Empresas",
    "optionSelecioneFormaDePagamento": "Selecione um valor para o campo Forma de Pagamento",
    "optionSelecioneFornecedor": "Selecione um valor para o campo Fornecedor",
    "optionSelecioneGrupoAdmTesouraria":"Selecione o grupo ADM tesouraria",
    "optionSelecioneGrupoDeContas": "Selecione um valor para o campo Grupo de Contas",
    "optionSelecioneIncoterm": "Selecione um valor para o campo Incoterm",
    "optionSelecioneMoeda": "Selecione um valor para o campo Moeda",
    "optionSelecionePaisCliente": "Selecione um valor para o campo País do Cliente",
    "optionSelecionePaisRexam": "Selecione um valor para o campo País da Rexam",
    "optionSelecionePlanta": "Selecione um valor para o campo Planta",
    "optionSelecioneProblema": "Selecione um valor para o campo Tipo Problema",
    "optionSelecioneRegiao": "Selecione um Estado",
    "optionSelecioneRegiaoDeVendas": "Selecione uma Região de Vendas",
    "optionSelecioneSetorIndustrial":"Selecione o setor industrial",
    "optionSelecioneSeveridade": "Selecione um valor para o campo Severidade",
    "optionSelecioneTipoMetal": "Selecione um valor para o campo Tipo Metal",
    "optionTipoDeServico": "Selecione o tipo de serviço",
    "optionEdicao": "Selecione a edição",
    "optionParticipante": "Selecione o participante",
    "optionVenda": "Venda (Metal origem sucata)",
    "placeAgenteFrete": "Insira aqui o código SAP do agente",
    "placeBairro": "Informe o Bairro",
    "placeCEP": "Informe o CEP",
    "placeCidade": "Informe a Cidade",
    "placeCodigoClienteSAP": "Informe o Código Cliente SAP",
    "placeCodigoFiscal": "Informe o código fiscal",
    "placeCodigoProdutoFornecedor": "Informe o código do produto fornecedor",
    "placeCodigoProdutoSAP": "Informe o código do produto SAP",
    "placeComentariosAdicionais": "Informe Comentários Adicionais",
    "placeComentariosDaOcorrencia": "Informe algum comentário da ocorrência",
    "placeComplemento": "Informe o Complemento",
    "placeCustoDespesas": "Outros custos adicionais a latas perdidas e horas paradas",
    "placeDetalharOutrasPerdas": "Detalhar outras perdas e custos",
    "placeDetalharPerdasFerramentas": "Detalhar perda ferramental",
    "placeEmail": "Informe o E-mail",
    "placeEmailCobranca": "Informe o E-mail de Cobrança",
    "placeEmailNFE": "Informe o E-mail NFE",
    "placeIndicadorDevolucaoVendaMetal": "Selecionar um valor para o campo Indicador de Retorno ou Venda",
    "placeInformeDescricaoProblema": "Informe a descrição do problema",
    "placeInformeDetalhePerdaFerramenta": "Informe detalhes da perda ferramental",
    "placeInformeLatasTampas": "Informe quantas latas e/ou tampas",
    "placeINformeNumHFI": "Informe número do cartão HFI",
    "placeInformeNumLote": "Informe número do lote",
    "placeInformePesoReclamada": "Informe o peso reclamado",
    "placeInformePesoTotalBobina": "Informe o peso total da bonina",
    "placeInformeQntAmostrasEnviada": "Informe a quantidade de amostras enviadas ao fornecedor",
    "placeInformeQntAmostrasRetornadas": "Informe a quantidade de amostras retornadas pelo fonnecedor",
    "placeInformeUnidadeMedida": "Selecione a unidade de medida",
    "placeInformeValorPerdaFerramenta": "Informe o valor da perda de ferramenta",
    "placeInscricaoEstadual": "Informe a Inscrição Estadual",
    "placeInscricaoMunicipal": "Informe a Inscrição Municipal",
    "placeLogradouro": "Informe o Logradouro",
    "placeMotivoSolicitacao": "Informe o Motivo da Solicitação",
    "placeNomeCliente": "Informe o Nome do Cliente",
    "placeNomeDeBusca": "Informe o Nome de Busca",
    "placeNotaFiscal": "Informe a nota fiscal",
    "placeNovaZonaDeTransporte": "Informe o novo código zona de transporte",
    "placeNovoGrupoClientes": "Informe o novo código grupo clientes",
    "placeNovoGrupoPreco": "Informe o novo código grupo preço",
    "placeNumero": "Informe o número",
    "placeNumeroCliente":"Número Cliente",
    "placeObservacao": "Informe alguma observação",
    "placeParecerPrevio": " Informe parecer prévio Rexam",
    "placePedidoCorrecao":"Pedido de Correção",
    "placePlacaVeiculo": "Informe placa veículo",
    "placeQuantidadeRetida": " Informe a quantidade retida",
    "placeRecebedorDaMercadoria": "Informe o Recebedor da Mercadoria",
    "placeRegiao": "Informe o Estado",
    "placeSelecioneDataEntrada": "Selecione a data de entrada",
    "placeSelecioneDataFaturamento": "Selecione a data de faturamento do fornecedor",
    "placeSelecioneDataOcorrencia": "Selecione a data de ocorrência",
    "placeSolteOsArquivosAqui": "Solte os arquivos aqui...",
    "placeTelefone": "Informe o Telefone",
    "placeUnidadeRetida": " Informe a unidade de medida retida",
    "tituloCadastroCLiente": "Cadastro de Cliente",
    "tituloCriacaoNoc": "Criação de NOC",
    "validacaoAcompanhamentoFornecedor": "Informe se teve acompanhamento do fornecedor",
    "validacaoAgenteFrete": "Informe o Agente Frete",
    "validacaoBairro": "Informe o Bairro",
    "validacaoCartaoHFI": "Informe número do cartão HFI",
    "validacaoCategoria": "Informe a categoria",
    "validacaoCausaRaiz": "Informe a causa raiz",
    "validacaoCentroDeFornecimento": "Informe o Centro de Fornecimento",
    "validacaoCEP": "Informe o CEP",
    "validacaoCidade": "Informe a Cidade",
    "validacaoClasse": "Informe a classe",
    "validacaoCodigoClienteSAP": "Informe o Código Cliente SAP",
    "validacaoCodigoFiscal": "Informe o Código Fiscal",
    "validacaoCodigoMetal": "Informe o código do metal",
    "validacaoCodigoProdutoFornecedor": "Informe o código do produto fornecedor",
    "validacaoCodigoProdutoSAP": "Informe o código do produto SAP",
    "validacaoCondicaoDeExpedicao": "Informe a Condição de Expedição",
    "validacaoCondicaoDePagamento": "Informe a Condição de Pagamento",
    "validacaoContaConciliatoria":"Informe a Conta Conciliatória",
    "validacaoCustosDespesas": "Informe outros custos adicionais a latas perdidas e horas paradas",
    "validacaoDataEntrada": "Informe a data de entrada",
    "validacaoDataFabricacao": "Informe a data de fabricação",
    "validacaoDataFaturamenFornecedor": "Informe a data de faturamento do fornecedor",
    "validacaoDataOcorrencia": "Informe a data de ocorrência",
    "validacaoDcrPerdaFerramenta": "Informe detalhes da perda ferramental",
    "validacaoDcrPerdaOutrosCustos": "Informe detalhes de outras perdas / custos",
    "validacaoDcrProblema": "Informe detalhes do problema",
    "validacaoDefeito": "Informe o defeito",
    "validacaoEmail": "Informe o E-mail",
    "validacaoEmailCobranca": "Informe o E-mail de Cobrança",
    "validacaoEmailNFE": "Informe o E-mail NFE",
    "validacaoEmpresas": "Informe uma ou mais Empresas",
    "validacaoFormaDePagamento": "Informe a Forma de Pagamento",
    "validacaoFornecedor": "Informe o fornecedor",
    "validacaoGerouDrenoLinha": "Informe se o defeito gerou dreno de linha",
    "validacaoGerouPerdaProducao": "Informe se o defeito gerou perda de produção",
    "validacaoGrupoClientes": "Informe o grupo clientes",
    "validacaoGrupoDeContas": "Informe o Grupo de Contas",
    "validacaoGrupoPreco": "Informe o grupo preço",
    "validacaoIncoterm": "Informe o Incoterm",
    "validacaoIndicadorDevolucaoVenda": "Informe se teve indicador de devolução ou venda código do metal",
    "validacaoInscricaoEstadual": "Informe a Inscrição Estadual",
    "validacaoInscricaoMunicipal": "Informe a Inscrição Municipal",
    "validacaoLogradouro": "Informe o Logradouro",
    "validacaoLote": "Informe o lote",
    "validacaoMoeda": "Informe a moeda",
    "validacaoMoedaContabilizacao": "Informe a moeda de contabilização",
    "validacaoMotivoDaSolicitacao": "Informe o Motivo da Solicitação",
    "validacaoNomeCliente": "Informe o Nome do Cliente",
    "validacaoNomeDeBusca": "Informe o Nome de Busca",
    "validacaoNotaFiscal": "Informe a nota fiscal",
    "validacaoNovaZonaDeTransporte": "Informe o novo código zona de transporte",
    "validacaoNovoGrupoClientes": "Informe o novo código grupo clientes",
    "validacaoNovoGrupoPreco": "Informe o novo código grupo preço",
    "validacaoNumero": "Informe o Número",
    "validacaoNumeroCliente":"Informe o número do Cliente",
    "validacaoPaisDaRexam": "Informe o País da Rexam",
    "validacaoPaisDoCliente": "Informe o País do Cliente",
    "validacaoPedidoCorrecao":"Informe o Pedido de Correção",
    "validacaoPerdaFerramenta": "Informe se ocorreu perda de ferramenta",
    "validacaoPerdaOutrosCustos": "Informe se ocorreu outras perdas ou outros custos",
    "validacaoPesoReclamada": "Informe o peso reclamada",
    "validacaoPesoTotalBobina": "Informe o peso total da bobina",
    "validacaoPlacaVeiculo": "Informe placa veículo",
    "validacaoPlanta": "Informe a planta",
    "validacaoQtdAmostraEnviada": "Informe a qtd. amostras enviadas ao fornecedor (meia-latas ou chapas)",
    "validacaoQtdAmostraRetorno": "Informe a qtd. retorno fornecedor/venda",
    "validacaoQtdDefeitoDrenoLinha": "Informe quantas latas e/ou tampas",
    "validacaoQtdDefeitoPerdaProducao": "Informe quantas latas e/ou tampas",
    "validacaoQuantidadeRetida": " Informe a quantidade retida",
    "validacaoRecebedorDiferente": "Informe se o recebedor de mercadoria é diferente deste cadastro",
    "validacaoRegiao": "Informe o Estado",
    "validacaoRegiãoDeVendas": "Informe a Região de Vendas",
    "validacaoReteste": "Informe se ocorreu reteste",
    "validacaoSelecioneClassificacaoFiscal":"Informe a classificação fiscal",
    "validacaoSelecioneGrupoAdmTesouraria":"Informe o grupo ADM tesouraria",
    "validacaoSelecioneSetorIndustrial":"Informe o setor industrial",
    "validacaoSeveridade": "Informe a severidade",
    "validacaoTelefone": "Informe o Telefone",
    "validacaoTipoDeServico": "Informe o tipo de serviço",
    "validacaoTipoMetal": "Informe o tipo de metal",
    "validacaoTipoProblema": "Informe o tipo de problema",
    "validacaoUnidadeMedida": "Informe a unidade de medida",
    "validacaoUnidadeRetida": " Informe a unidade de medida retida",
    "validacaoValorPerdaFerramenta": "Informe o valor da perda de ferramenta",
    "validacaoValorPerdaOutrosCustos": "Informe o valor de outras perdas / custos",
    "validacaoZonaDeTransporte": "Informe a zona de transporte",
    "validacaoAcoesCorretivas": "Informe as ações corretivas",
    "validacaoAcoesPreventivas": "Informe as ações preventivas",
    "buttonCancelar": "Cancelar",
    "buttonIncluirBanco": "Incluir Banco",
    "buttonIncluirEmpresa": "Incluir Empresa",
    "buttonIncluirMembro": "Incluir Membro da Equipe",
    "buttonSalvar": "Salvar",
    "labelAgenciaComDigito": "Agência",
    "labelAguardandoAprovacaoSAP": "Aguardando a aprovação do SAP",
    "labelAguardandoAprovacaoSetorFinanceiro": "Aguardando a aprovação do setor financeiro",
    "labelAguardandoCorrecaoClientes": "Aguardando correção do Solicitante",
    "labelAguardandoCorrecaoFornecedor": "Aguardando correção do Solicitante",
    "labelAguardandoSetorDadosContabeis": "Aguardando o setor de Dados Contábeis",
    "labelAguardandoSetorDadosFiscais": "Aguardando o setor de Dados Fiscais",
    "labelAguardandoSetoresDadosFiscaisDadosContabeis": "Aguardando os setores de Dados Fiscais e Dados Contábeis",
    "labelAprovacaoFinanceiro": "Aprovação Financeiro",
    "labelBanco": "Banco",
    "labelCadastroCancelado": "Cadastro cancelado",
    "labelCadastroConcluido": "Cadastro concluído",
    "labelCadastroFornecedor": "Cadastro de Fornecedor",
    "labelCartaAutorizacao": "Carta Autorização",
    "labelCBU": "CBU",
    "labelClienteEnvasadoraProdutoAcabado": "Cliente Envasadora / Produto Acabado?",
    "labelContaCorrenteComDigito": "Conta corrente",
    "labelDadosBancarios": "Dados Bancário",
    "labelDocumentoBancario": "Documento Bancário",
    "labelIncotermFOB": "FOB?",
    "labelJustificativaCondicaoPagamento": "Justificativa Condição Pagamento",
    "labelJustificativaFormaPagamento": "Justificativa Forma Pagamento",
    "labelNome": "Nome",
    "labelNomeSobrenomeContato": "Nome/Sobrenome Contato",
    "labelNumeroFornecedorSAP": "Número Fornecedor SAP",
    "labelOrganizaçãoCompra": "Organização de Compra",
    "labelOutros": "Outros",
    "labelPaisFornecedor": "País do Fornecedor",
    "labelRetornarPara": "Retornar Para",
    "labelTipoLogradouro": "Tipo de Logradouro",
    "liAnexos": "Anexos",
    "liFornecedor": "Fornecedor",
    "optionContabilidade": "Contabilidade",
    "optionFinanceiro": "Financeiro",
    "optionOrganizacaoCompra": "Selecione a organização de compra",
    "optionPaisFornecedor": "Selecione o país do fornecedor",
    "optionSelecioneBanco": "Selecione um ou mais bancos",
    "optionSelecioneMoeda": "Selecione a moeda",
    "optionSelecioneOndeDeveRetornar": "Selecione para onde deve retornar",
    "optionSolicitante": "Solicitante",
    "optionTipoLogradouro": "Selecione o tipo de Logradouro",
    "placeAgenciaComDigito": "Agência",
    "placeCBU": "CBU",
    "placeContaCorrenteComDigito": "Conta corrente",
    "placeJustificativaCondicaoPagamento": "Justificativa Condição Pagamento",
    "placeJustificativaFormaPagamento": "Justificativa Forma Pagamento",
    "placeNome": "Nome",
    "placeNomeSobrenomeContato": "Nome/Sobrenome Contato",
    "placeNumeroFornecedorSAP": "Número Fornecedor SAP",
    "thAgencia": "Agência",
    "thBanco": "Banco",
    "thCBU": "CBU",
    "thContaCorrente": "Conta Corrente",
    "thEmpresa": "Empresa",
    "thOrganizacaoCompras": "Organização de Compras",
    "tituloNovaEmpresa": "Nova Empresa",
    "tituloNovoBanco": "Novo Banco",
    "validacaoAgenciaComDigito": "Informe Agência (com dígito)",
    "validacaoContaCorrenteComDigito": "Informe a Conta corrente (com dígito)",
    "validacaoIncotermFOB": "Incoterm FOB",
    "validacaoJustificativaCondicaoPagamento": "Informe Justificativa Condição Pagamento",
    "validacaoJustificativaFormaPagamento": "Informe Justificativa Forma Pagamento",
    "validacaoNome": "Informe o Nome",
    "validacaoNumeroFornecedorSAP": "Informe o Número Fornecedor SAP",
    "validacaoOrganizacaoCompra": "Informe a organização de compra",
    "validacaoPaisFornecedor": "Informe o país do fornecedor",
    "validacaoRetornarPara": "InformeRetornarPara",
    "validacaoSelecioneArquivoCodigoFiscal": "Selecione um arquivo do tipo Código Fiscal",
    "validacaoSelecioneArquivoTipoCartaAutorizacao": "Selecione um arquivo do tipo Carta Autorização",
    "validacaoSelecioneArquivoTipoDocumentoBancario": "Selecione um arquivo do tipo Documento Bancário",
    "validacaoSelecioneArquivoTipoInscricaoEstadual": "Selecione um arquivo do tipo Inscrição Estadual",
    "validacaoSelecioneArquivoTipoInscricaoMunicipal": "Selecione um arquivo do tipo Inscrição Municipal",
    "validacaoSelecioneBanco": "Informe um ou mais bancos",
    "validacaoSelecioneEmpresa": "Informe uma empresa",
    "validacaoSelecioneMoeda": "Informe a Moeda",
    "validacaoTipoLogradouro": "Informe o Tipo de Logradouro",
    "validaNomeSobrenomeContato": "Informe o Nome/Sobrenome do Contato",
    "labelMaterial": "Material",
    "labelCodigoDoMaterialNoSAP": "Código do Material no SAP",
    "placeCodigoDoMaterialNoSAP": "Código do Material no SAP",
    "validacaoCodigoDoMaterialNoSAP": "Informe o Código do Material no SAP",
    "labelDevolverPara": "Devolver Para",
    "labelSuprimentos": "Suprimentos",
    "optionSuprimentos": "Suprimentos",
    "optionFiscal": "Fiscal",
    "optionContabil": "Contábil",
    "optionEngenharia": "Engenharia",
    "labelClasseAvaliacao": "Classe Avaliação",
    "placeClasseAvaliacao": "Classe Avaliação",
    "validacaoClasseAvaliacao": "informe a Classe Avaliação",
    "labelModeloMaterial": "Modelo de Material",
    "optionSelecioneAPlanta": "Selecione a Planta",
    "labelDescricaoCurta": "Descrição Curta",
    "placeDescricaoCurta": "Descrição Curta",
    "validacaoDescricaoCurta": "Informe a Descrição Curta",
    "optionUnidadeMedida": "Unidade de Medida",
    "labelGrupoMercadoria": "Grupo de Mercadoria",
    "optionGrupoMercadoria": "Selecione o Grupo de Mercadoria",
    "validacaoGrupoMercadoria": "Informe o Grupo de Mercadoria",
    "labelDescricaoLonga": "Descrição Longa",
    "placeDescricaoLonga": "Descrição Longa",
    "validacaoDescricaoLonga": "Informe a Descrição Longa",
    "labelDescricaoImportada": "Descrição em Inglês",
    "placeDescricaoImportada": "Descrição em Inglês",
    "labelOrigemMaterial": "Origem do Material",
    "optionOrigemMaterial": "Selecione a Origem Material",
    "validacaoOrigemMaterial": "Informe a Origem Material",
    "labelEngenharia": "Engenharia",
    "labelFerramentaIntermutavel": "Ferramenta Intermutável",
    "labelItemCritico": "Item Crítico",
    "labelItemRecuperavel": "Item Recuperável",
    "labelDeposito": "Depósito",
    "optionDeposito": "Selecione o Depósito",
    "validacaoDeposito": "Informe o Depósito",
    "labelFuncaoMaterial": "Função do Material",
    "optionFuncaoMaterial": "Função do Material",
    "placeUtilizacaoEquipamento": "Utilização do Equipamento em",
    "optionUtilizacaoEquipamento": "Selecione a utilização do equipamento",
    "validacaoUtilizacaoEquipamento": "Informe a utilização do equipamento",
    "labelEquipamento": "Equipamento",
    "optionEquipamento": "Selecione o Equipamento",
    "validacaoEquipamento": "Informe o Equipamento",
    "labelFabricanteReferencia": "Fabricante/Referência",
    "placeFabricanteReferencia": "Fabricante/Referência",
    "validacaoFabricanteReferencia": "Informe o Fabricante/Referência",
    "labelEstoqueMinimo": "Estoque Mínimo",
    "placeEstoqueMinimo": "Estoque Mínimo",
    "validacaoEstoqueMinimo": "Informe o Estoque Mínimo",
    "labelEstoqueMaximo": "Estoque Máximo",
    "placeEstoqueMaximo": "Estoque Máximo",
    "validacaoEstoqueMaximo": "informe o Estoque Máximo",
    "placeTipoMRP": "Tipo MRP",
    "optionTipoMRP": "Selecione o Tipo MRP",
    "validacaoTipoMRP": "Informe o Tipo MRP",
    "placePlanejadorMRP": "Planejador MRP",
    "optionPlanejadorMRP": "Selecione o Planejador MRP",
    "validacaoPlanejadorMRP": "Informe o Planejador MRP",
    "placeTamanhoDoLoteMRP": "Tamanho do Lote MRP",
    "optionTamanhoDoLoteMRP": "Selecione o Tamanho do Lote MRP",
    "validacaoTamanhoDoLoteMRP": "Informe o Tamanho do Lote MRP",
    "labelTipoDeFert": "Tipo de FERT",
    "labelLata": "Lata",
    "labelampa": "Tampa",
    "labelDeixarVersaoBloqueadoEmZ1": "Deixar Versão Bloqueado em Z1?",
    "labelDeixarVersaoBloqueadoEm03": "Deixar Versão Bloqueado em 03?",
    "labelQuantidadeLatasPorCamada": "Quantidade de Latas Por Camada",
    "placeQuantidadeLatasPorCamada": "Quantidade de Latas Por Camada",
    "validacaoQuantidadeLatasPorCamada": "Informe a Quantidade de Latas Por Camada",
    "labelTipoDeLata": "Tipo de Lata",
    "placeTipoDeLata": "Tipo de Lata",
    "validacaoTipoDeLata": "Informe o Tipo de Lata",
    "labelObservacoes": "Observações",
    "placeObservacoes": "Observações",
    "labelInformacoesListaTecnica": "Informações Lista Técnica",
    "labelNovaInformacaoListaTecnica": "Nova Informação Lista Técnica",
    "labelQuantidade": "Quantidade",
    "placeQuantidade": "Quantidade",
    "validacaoQuantidade": "Informe a Quantidade",
    "labelProduto": "Produto",
    "placeProduto": "Produto",
    "validacaoProduto": "Informe o Produto",
    "labelCodigo": "Código",
    "placeCodigo": "Código",
    "validacaoCodigo": "Informe o Código",
    "labelFiscal": "Fiscal",
    "optionSelecioneCategoriaCFOP": "Selecione a categoria CFOP",
    "labelCategoriaCFOP": "Categoria CFOP",
    "validacaoCategoriaCFOP": "Informe a categoria CFOP",
    "labelClassificacaoFiscal": "Classificação fiscal",
    "labelUtilizacaoDoMaterial": "Utilização do Material",
    "placeUtilizacaoDoMaterial": "Utilização do Material",
    "validacaoUtilizacaoDoMaterial": "validacaoUtilização do Material",
    "labelLabEsc": "Lab./escr.",
    "optionLabEsc": "Selecione o Lab./escr.",
    "validacaoLabEsc": "Informe o Lab./escr.",
    "labelCentroDeLucro": "Centro de Lucro",
    "optionCentroDeLucro": "Selecione o Centro de Lucro",
    "validacaCentroDeLucro": "Informe o Centro de Lucro",
    "labelDepositoDeProducao": "Depósito De Produção",
    "optionDepositoDeProducao": "Selecione o Depósito De Produção",
    "validacaoDepositoDeProducao": "Informe o Depósito De Produção",
    "labelGrupoMRP": "Grupo MRP",
    "optionGrupoMRP": "Selecione o Grupo MRP",
    "validacaoGrupoMRP": "Informe o Grupo MRP",
    "labelAguardandoCorrecaoCadastro": "Aguardando correção no cadastro",
    "labelAguardandoSetorSuprimentos": "Aguardando setor de suprimentos",
    "labelAguardandoSetoresFiscalEContabil": "Aguardando setores fiscal e contábil",
    "labelAguardandoSetorFiscal": "Aguardando setor fiscal",
    "labelAguardandoSetorContabil": "Aguardando setor contábil",
    "labelAguardandoSetorEngenharia": "Aguardando setor de engenharia",
    "labelPesoBruto": "Peso Bruto",
    "placePesoBruto": "Peso Bruto",
    "validacaoPesoBruto": "Informe o Peso Bruto",
    "labelPesoLiquido": "Peso Líquido",
    "placePesoLiquido": "Peso Líquido",
    "validacaoPesoLiquido": "Informe o Peso Líquido",
    "labelTipoDeMaterial": "Tipo de Material",
    "labelCodigoDoMaterial": "Código do Material",
    "labelAplicacaoDoEquipamento": "Aplicação do Equipamento",
    "optionAplicacaoDoEquipamento": "Selecione a Aplicação do Equipamento",
    "validacaoAplicacaoDoEquipamento": "Informe a Aplicação do Equipamento",
    "labelPartNumber": "Part Number",
    "placePartNumber": "Part Number",
    "validacaoPartNumber": "Informe o Part Number",
    "labelQuantidadeLatasTampasPorPalete": "Quantidade de Latas/Tampas Por Palete",
    "placeQuantidadeLatasTampasPorPalete": "Quantidade de Latas/Tampas Por Palete",
    "validacaoQuantidadeLatasTampasPorPalete": "Informe a Quantidade de Latas/Tampas Por Palete",
    "labelCadastroDeMaterial": "Cadastro de Material",
    "labelCustoMaterial": "Custo Material",
    "placeCustoMaterial": "Custo Material",
    "validacaoCustoMaterial": "Informe o Custo Material",
    "labelCodigoNCM": "Código NCM",
    "placeCodigoNCM": "Código NCM",
    "validacaoCodigoNCM": "Informe o Código NCM",

    "validacaoParecer":"Informe o Paracer",
    "labelAguardandoAceite":"Aguardando aceite",
    "labelAguardandoResposta":"Aguardando resposta",
    "labelAguardandoRespostaEspecialistaLean":"Aguardando resposta do Especialista Lean",
    "labelAguardandoRespostaGerente":"Aguardando resposta do Gerente",
    "labelAguardandoRespostaLiderLean":"Aguardando resposta do Líder Lean",
    "labelAguardandoRespostaSuperiorImediato":"Aguardando resposta do Superior Imediato",
    "labelAlocacaoDeRecursosDeficienteFaltaDeRecursos":"Alocação de recursos deficiente/falta de recursos",
    "labelAlto":"Alto",
    "labelAnaliseDoProblemaESuasCausas":"Análise do problema e suas causas",
    "labelAnaliseDosPorques":"Análise dos Porquês",
    "labelAnalisePriorizacaoSeAplicavel":"Analise Priorização se Aplicável:",
    "labelAntesDaInovacao":"Antes da Inovação (latas/tampas por minuto)",
    "labelApprover":"Approver",
    "labelAprovacao":"Aprovação",
    "labelAprovar":"Aprovar",
	"labelTransportadora": "Transportadora",
	"optionTransportadora": "Selecione a transportadora",
    "labelARexamNaoTeraQueDesembolsarValoresParaATransportadora":"(A Rexam não terá que desembolsar valores para a transportadora)",
    "labelAtuaSobreGargalo":"Atua Sobre o Gargalo",
    "labelBaixo":"Baixo",
    "labelCancelada":"Cancelada",
    "labelCargo":"Cargo",
    "labelCategorizacao":"Categorização",
    "labelCausa":"Causa",
    "labelCausas":"Causas",
    "labelCliente":"Cliente",
    "labelClienteCadastro":"Cliente Cadastro",
    "labelCodigoDoProduto":"Código do Produto",
    "labelComentariosDoCliente":"Comentários do cliente",
    "labelConcluida":"Concluída",
    "labelConclusao":"Conclusão",
    "labelCondicoesAmbientaisOuClimaticas":"Condições ambientais ou climáticas",
    "labelCondicoesDoAmbienteDeTrabalhoInadequadas":"Condições do ambiente de trabalho inadequadas",
    "labelContencao":"Ação de Contenção - Ação Imediata definindo o destino do lote afetado e/ou suspeito",
    "labelConteudoInadequado":"Conteúdo inadequado",
    "labelControlesAdministrativosAusentesOuInadequados":"Controles administrativos ausentes ou inadequados ",
    "labelCriacaoDeNocCliente":"Criação de NOC Cliente",
	"labelEdicaoDeNocCliente":"Edição de NOC Cliente",
    "labelCriacaoDeProjetoInovacao":"Criação de Projeto Inovação",
    "labelCriacaoNocFornecedor":"Criação de NOC Fornecedor",
    "labelDadosDeAtendimentoReclamação":"Dados de atendimento a reclamação",
    "labelDataAutorizacaoDevolucao":"Data de Autorização da Devolução",
    "labelDataAutorizacaoRessarcimento":"Data autorização ressarcimento",
    "labelDataChegadaDoLoteDevoldidoAFabrica":"Data chegada do lote devolvido à fábrica",
    "labelDataDeAprovacaoPeloEspecialistaLean":"Data de Aprovação pelo Especialista Lean",
    "labelDataDeAprovacaoPeloGerente":"Data de Aprovação pelo Gerente",
    "labelDataDeAprovacaoPeloSuperiorImediato":"Data de Aprovação pelo Superior Imediato",
    "labelDataDeAprovaçãoPeloLiderLean":"Data de Aprovação pelo Líder Lean",
    "labelDataimplantacaoDoProjeto":"Data de Implantação do Projeto",
    "labelDeficienciaNaOrganizaçãoELimpezaDaArea":"Deficiência na organização e limpeza da área",
    "labelDefinicaoDoProblema":"Definição do Problema",
    "labelDepartamento":"Departamento",
    "labelDepoisDaInovacao":"Depois da Inovação (latas/tampas por minuto)",
    "labelDescricaoDoProjeto":"Descrição do projeto",
    "labelDesperdicioAnoAntesDaInovacao":"Desperdício ano (US$, antes da inovação)",
    "labelDesperdicioAnoDepoisDaInovacao":"Desperdício ano (US$, depois da inovação)",
    "labelDesperdicioMesAntesDaInovacao":"Desperdício mês (US$, antes da inovação)",
    "labelDesperdicioMesDepoisDaInovacao":"Desperdício mês (US$, depois da inovação)",
    "labelDesvioDeProcedimentoOuRequisito":"Desvio de procedimento ou requisito",
    "labelDevolucao":"Devolução?",
    "labelDispatch":"Dispatch",
    "labelEconomiaGeradaPorAno":"Economia gerada por ano (US$)",
    "labelEconomiaGeradaPorMes":"Economia gerada por mês (US$)",
    "labelEmailParaNotificacoes":"E-mail para Notificações",
    "labelEmAprovacao":"Em aprovação",
    "labelEmRevisaoDeResposta":"Em revisão de resposta",
    "labelEquipamentoMaterial":"Equipamento/Material",
    "labelEquipamentoQueFalhou":"Equipamento que falhou",
    "labelEquipeDoProjeto":"Equipe do Projeto",
    "labelErroEmDesenhosEspecificacoesOuDados":"Erro em desenhos, especificações ou dados",
    "labelEspecialistaLean":"Especialista Lean",
    "labelEspecialistaLeanQueAprovou":"Especialista Lean que aprovou",
    "labelEspecificacaoDeMaterialOuDeEquipamentoInadequada":"Especificação de material ou de equipamento inadequada",
    "labelEsteProjetoEstaSendoImportadoDeOutraUnidade":"Este projeto está sendo importado de outra unidade?",
    "labelEstimativaDoCustoDaReclamacaoAtendimento":"Estimativa do Custo da Reclamação/Atendimento",
    "labelEstimativaDoCustoDaReclamacaoOutros":"Estimativa do Custo da Reclamação/Outros",
    "labelFabrica":"Fábrica",
    "labelFabricaDevolucao":"Fábrica Devolução",
    "labelFalhaDoFornecedorDoEquipamentoOuMaterial":"Falha do fornecedor do equipamento ou material",
    "labelFalhaNaComunicacaoInternaVerbalOuOutros":"Falha na comunicação interna (verbal ou outros)",
    "labelFalhaNosMecanismosDeDeteccaoDeFalhas":"Falha nos mecanismos de detecção (de falhas)",
    "labelFaltaDeAtencaoAosDetalhes":"Falta de atenção aos detalhes",
    "labelFaltaDeProcedimento":"Falta de procedimento",
    "labelFaltaDeReciclagemPeriodica":"Falta de reciclagem periódica",
    "labelFenomenosExternos":"Fenômenos Externos",
    "labelFornecedorCadastro":"Fornecedor Cadastro",
    "labelGanhosMensurados":"Ganhos mensurados",
    "labelGanhosNaoMensurados":"Resultados alcançados",
    "labelGanhosObtidos":"Ganhos Obtidos",
    "labelGerente":"Gerente",
    "labelGerenteQueAprovou":"Gerente que aprovou",
    "labelGestao":"Gestão",
    "labelGrupoClassificacaoContabil":"Grupo Classificação Contábil",
    "labelHoraDeFabricacao":"Hora de Fabricação",
    "labelHouveRiscosEliminadosPeloPeojeto":"Houve Riscos Eliminados Pelo Projeto?",
    "labelInadequadaSupervisao":"Inadequada supervisão",
    "labelIncendioOuExplosaoExterna":"Incêndio ou explosão externa",
    "labelInformarLiderDoProjeto":"Informar o líder do Projeto",
    "labelInformeUmaResposta":"Informe uma resposta",
    "labelInfraestrutura":"Infraestrutura",
    "labelInovacaoAprovacaoDoSuperiorImediato":"Inovação - Aprovação do Superior Imediato",
    "labelInovacaoAprovacaoEspecialistaLean":"Inovação - Aprovação do Especialista Lean",
    "labelInovacaoAprovacaoGerente":"Inovação - Aprovação do Gerente",
    "labelInovacaoAprovacaoLiderLean":"Inovação - Aprovação do Líder Lean",
    "labelInovacaoCadastro":"Inovação - Cadastro",
    "labelInovacaoHistorico":"Inovação - Histórico",
    "labelInstalacoesInadequadas":"Instalações inadequadas",
    "labelInterfaceHomemMaquinaInadequadas":"Interface homem-máquina inadequadas",
    "labelInvestimentoDoProjeto":"Investimento do Projeto (em Reais)",
    "labelJustificativaDaReprovacao":"Justificativa da Reprovação",
    "labelJustificativaReprovacao":"Justificativa de Reprovação",
    "labelLider":"Líder",
    "labelLiderLean":"Líder Lean",
    "labelLiderLeanQueAprovou":"Líder Lean que aprovou",
    "labelManutencaoDasInstalacoesAusenteOuInadequada":"Manutenção das instalações ausente ou inadequada",
    "labelMapaCausaRaiz":"Mapa Causa Raiz",
    "labelmaterialDefeituoso":"Material defeituoso",
    "labelMaterialDeSuporteInadequado":"Material de suporte inadequado",
    "labelMatricula":"Matrícula",
    "labelMedio":"Médio",
    "labelMetodologiaInadequada":"Metodologia inadequada",
    "labelMotivoCorrecao":"Motivo de Correção",
    "labelNaoFoiFornecidoOTreinamento":"Não foi fornecido o treinamento",
    "labelNocCliente":"Noc Cliente",
    "labelNocInformativa":"NOC Informativa?",
    "labelNomeDoParticipante":"Nome do Participante",
    "labelNomeDoProjeto":"Nome do Projeto",
    "labelNotasRelevantes":"Notas Relevantes",
    "labelNovaCausa":"Nova Causa",
    "labelNovaPlanta":"Nova Planta",
    "labelOrganizacaoDoTrabalhoInadequada":"Organização do trabalho inadequada",
    "labelOutrasEconomiasMensais":"Saving mensal gerado (em Reais, não vinculado a perda de latas ou tampas)",
    "labelOutrosFatoresHumanos":"Outros fatores humanos",
    "labelOutroTipoDeDocumento":"Outro Tipo de Documento",
    "labelParecer":"Parecer",
    "labelParecerDaAreaExterno":"Parecer da Área (externo)",
    "labelParecerDaAreaInterno":"Parecer da Área (interno)",
    "labelPessoal":"Pessoal",
    "labelPlanejamentoDoTrabalhoInadequado":"Planejamento (do trabalho) inadequado",
    "labelPlantas":"Plantas",
    "labelPoliticaNaoAdequadamenteDefinidaDisseminadaOuRreforcada":"Política não adequadamente definida, disseminada ou reforçada",
    "labelPontosInovação":"Pontos Inovação",
    "labelPontosMelhoria":"Pontos Melhoria",
    "labelPorQue1":"Por quê 1",
    "labelPorQue2":"Por quê 2",
    "labelPorQue3":"Por quê 3",
    "labelPorQue4":"Por quê 4",
    "labelPorQue5":"Por quê 5",
    "labelPraticaInsuficienteDuranteOTreinamento":"Prática insuficiente durante o treinamento",
    "labelPrensaMatriz":"Prensa/Matriz/Lote",
    "labelProcedimento":"Procedimento",
    "labelProcedimentoNaoClaroAmbiguoOuIncompleto":"Procedimento não claro, ambíguo ou incompleto",
    "labelProjeto":"Projeto",
    "labelProjetoAprovado":"Projeto Aprovado",
    "labelProjetoDesenvolvidoNaUnidade":"Projeto Desenvolvido na Unidade",
    "labelProjetoReprovado":"Projeto Reprovado",
    "labelProjetos":"Projetos",
    "labelQual":"Qual?",
    "labelQuantidadeASerRessarcidaEmLata":"Quantidade a ser ressarcida em lata",
    "labelQuantidadeASerRessarcidaEmTampa":"Quantidade a ser ressarcida em tampa",
    "labelQuantidadeAutorizadaDevolver":"Quantidade autorizada a devolver",
    "labelQuantidadeDeAprovados":"Quantidade de Aprovados",
    "labelQuantidadeDeExpirados":"Quantidade de Expirados",
    "labelQuantidadeDeInscritos":"Quantidade de Inscritos",
    "labelQuantidadeDeReprovados":"Quantidade de Reprovados",
    "labelQuantidadeDevolvida":"Quantidade Devolvida",
    "labelQuantidadeemAprovacao":"Quantidade em Aprovação",
    "labelQuantidadeLatasTampasPerdidas":"HFI definitivo + latas/tampas perdidas em processo",
    "labelRelatorioDeParticipantes":"Relatório de Participantes",
    "labelRepostaDoFornecedor":"Reposta do Fornecedor",
    "labelReprovar":"Reprovar",
    "labelResponder":"Responder",
    "labelPerguntaResponder":"Deseja aceitar e responder a NOC?",
    "labelRespostaRexam":"Resposta Rexam",
    "labelRouboAssaltoVandalismo":"Roubo, assalto, vandalismo",
    "labelSelecioneAnaliseDePriorizacao":"Selecione a analise de priorização",
    "labelSeuProjetoEstaVinculadoPerdaDeLatasTampas":"Seu Projeto Está Vinculado a Perda de Latas/Tampas?",
    "labelSolicitarCorrecao":"Solicitar Correção",
    "labelSolucoesImplementadas":"Soluções Implementadas",
    "labelSuperiorImediato":"Superior Imediato",
    "labelSuperiorImediatoQueQprovou":"Superior Imediato que aprovou",
    "labelSupervisorResponsavel":"Gestor Responsável",
    "labelSuprimentoDeEnergiaOuAguaInadequados":"Suprimento de energia ou água inadequados",
    "labelTipoDeDocumento":"Tipo de Documento",
    "labelTipodeProjeto":"Tipo de Projeto",
    "labelTotalDeCreditos":"Total de Créditos",
    "labelTraducaoDoFato":"Tradução do Fato",
    "labelTreinamento":"Treinamento",
    "labelTurma":"Turma",
    "labelUnidade":"Unidade",
    "labelUnidadeDoParticipante":"Unidade do Participante",
    "labelUnidadeDoProjeto":"Unidade do Projeto",
    "labelUnidadesPerdidasPorAnoAntesDaInovacao":"Unidades perdidas por ano (antes da inovação)",
    "labelUnidadesPerdidasPorAnoDepoisDaInovacao":"Unidades perdidas por ano (depois da inovação)",
    "labelUnidadesPerdidasPorMesAntesDaInovacao":"Unidades perdidas por mês (antes da inovação)",
    "labelUnidadesPerdidasPorMesDepoisDaInovacao":"Unidades perdidas por mês (depois da inovação)",
    "labelValorDaLataTampa":"Valor da Lata/Tampa",
    "labelValorDoFrete":"Valor do Frete",
    "labelValorInovacao":"Valor Inovação",
    "labelValorMelhoria":"Valor Melhoria",
    "labelValorTotal":"Valor Total",
    "optionCliente":"Selecione o Cliente",
    "optionFabrica":"Selecione a fábrica",
    "optionInovacao":"Inovação",
    "optionMelhoria":"Melhoria",
    "optionProjeto":"Informe o Projeto",
    "optionResposta":"Resposta",
    "optionSelecioneACausaRaiz":"Selecione a causa raiz",
    "optionSelecioneAEtapaParaQualDesejaDevolver":"Selecione a etapa para qual deseja devolver",
    "optionSelecioneATurma":"Selecione a turma",
    "optionSelecioneFabricaDevolucao":"Selecione a fabrica devolução",
    "optionSelecioneParecer":"Selecione o Paracer",
    "optionSelecioneTipoDeProjeto":"Selecione o tipo de projeto",
    "optionSupervisorResponsavel":"Indique o melhor Gestor para avaliar este projeto",
    "optionTipoDeDocumento":"Selecione o tipo de documento",
    "optionUnidadeDoParticipante":"Selecione a unidade do participante",
    "optionUnidadeOndeProjetoFoiDesenvolvido":"Selecione a unidade onde o projeto foi desenvolvido",
    "placeAnaliseDoProblemaESuasCausas":"Análise do problema e suas causas",
    "placeAntesDaInovacao":"Antes da Inovação (latas/tampas por minuto)",
    "placeCausa":"Causa",
    "placeCodigoDoProduto":"Código do Produto",
    "placeComentarios":"Comentários",
    "placeComentariosDoCliente":"Comentários do cliente",
    "placeConclusao":"Conclusão",
    "placeContencao":"Ação de Contenção - Ação Imediata definindo o destino do lote afetado e/ou suspeito",
    "placeDadosDeAtendimentoReclamação":"Dados de atendimento a reclamação",
    "placeDefinicaoDoProblema":"Definição do Problema",
    "placeDepoisDaInovacao":"Depois da Inovação (latas/tampas por minuto)",
    "placeEmailParaNotificacoes":"Informe o E-mail para Notificações",
    "placeEstimativaDoCustoDaReclamacaoAtendimento":"Estimativa do Custo da Reclamação/Atendimento",
    "placeEstimativaDoCustoDaReclamacaoOutros":"Estimativa do Custo da Reclamação/Outros",
    "placeGanhosNaoMensurados":"Informe os resultados alcançados",
    "placeGrupoClassificacaoContabil":"Informe Grupo Classificação Contábil",
    "placeHoraDeFabricacao":"Hora de Fabricação",
    "placeInformeJustificativaDeReprovacao":"Informe a Justificativa de Reprovação",
    "placeInvestimentoDoProjeto":"Informe o investimento do Projeto (em Reais)",
    "placeMotivoCorrecao":"Informe o Motivo da Correção",
    "placeNomeDoProjeto":"Informe o Nome do Projeto",
    "placeNotasRelevantes":"Notas Relevantes",
    "placeOutrasEconomiasMensais":"Informe saving mensal gerado (em Reais, não vinculado a perda de latas ou tampas)",
    "placeOutroTipoDeDocumento":"Outro Tipo de Documento",
    "placeParecerDaAreaExterno":"Parecer da Área (externo)",
    "placeParecerDaAreaInterno":"Parecer da Área (interno)",
    "placePorQue1":"Por quê 1",
    "placePorQue2":"Por quê 2",
    "placePorQue3":"Por quê 3",
    "placePorQue4":"Por quê 4",
    "placePorQue5":"Por quê 5",
    "placePrensaMatriz":"Prensa/Matriz",
    "placeQual":"Qual?",
    "placeQuantidadeASerRessarcidaEmLata":"Quantidade a ser ressarcida em lata",
    "placeQuantidadeASerRessarcidaEmTampa":"Quantidade a ser ressarcida em tampa",
    "placeQuantidadeAutorizadaDevolver":"Quantidade Autorizada a Devolver",
    "placeQuantidadeDevolvida":"Quantidade Devolvida",
    "placeQuantidadeLatasTampasPerdidas":"HFI definitivo + latas/tampas perdidas em processo",
    "placeSolucoesImplementadas":"Soluções Implementadas",
    "placeTraducaoDoFato":"Tradução do Fato",
    "placeTurma":"Turma",
    "placeUnidadeDoProjeto":"Informe a Unidade do Projeto",
    "placeValorDoFrete":"Valor do Frete",
    "tituloEquipeDoProjeto":"Equipe do Projeto",
    "validacaoAlocacaoDeRecursosDeficienteFaltaDeRecursos":"Informe se houve Alocação de recursos deficiente/falta de recursos",
    "validacaoAnaliseDoProblemaESuasCausas":"Informe a Análise do problema e suas causas",
    "validacaoCausa":"Informe a Causa",
    "validacaoCliente":"Informe o Cliente",
    "validacaoClienteEnvasadoraProdutoAcabado":"Cliente Envasadora / Produto Acabado?",
    "validacaoComentariosDoCliente":"Informe os Comentários do cliente",
    "validacaoConclusao":"Informe a Conclusão",
    "validacaoCondicoesAmbientaisOuClimaticas":"Informe se houveram Condições ambientais ou climáticas",
    "validacaoCondicoesDoAmbienteDeTrabalhoInadequadas":"Informe se as Condições do Ambiente de Trabalho são Inadequadas",
    "validacaoConteudoInadequado":"Informe se houve Conteúdo inadequado",
    "validacaoControlesAdministrativosAusentesOuInadequados":"Informe se houveram Controles administrativos ausentes ou inadequados ",
    "validacaoDadosDeAtendimentoReclamação":"Informe os Dados de atendimento a reclamação",
    "validacaoDataAutorizacaoRessarcimento":"Informe a Data autorização ressarcimento",
    "validacaoDataChegadaDoLoteDevoldidoAFabrica":"Informe a Data de chegada do lote devolvido à fábrica",
    "validacaoDataimplantacaoDoProjeto":"Informe a Data de Implantação do Projeto",
    "validacaoDeficienciaNaOrganizaçãoELimpezaDaArea":"Informe se houve Deficiência na organização e limpeza da área",
    "validacaoDefinicaoDoProblema":"Informe a Definição do Problema",
    "validacaoDesvioDeProcedimentoOuRequisito":"Informe se houve Desvio de Procedimento ou Requisito",
    "validacaoDevolucao":"Informe se é devolução",
    "validacaoEmailParaNotificacoes":"Informe o E-mail para Notificações",
    "validacaoEquipamentoQueFalhou":"Informe se o Equipamento falhou",
    "validacaoErroEmDesenhosEspecificacoesOuDados":"Informe se houve Erro em desenhos, especificações ou dados",
    "validacaoEspecificacaoDeMaterialOuDeEquipamentoInadequada":"Informe se houve Especificação de material ou de equipamento inadequada",
    "validacaoEsteProjetoEstaSendoImportadoDeOutraUnidade":"Informe se este projeto está sendo importado de outra unidade",
    "validacaoEstimativaDoCustoDaReclamacaoAtendimento":"Informe a Estimativa do Custo da Reclamação/Atendimento",
    "validacaoEstimativaDoCustoDaReclamacaoOutros":"informe a Estimativa do Custo da Reclamação/Outros",
    "validacaoEtapaParaQualDesejaDevolver":"Informe a etapa para qual deseja devolver",
    "validacaoFabrica":"Informe a fábrica",
    "validacaoFabricaDevolucao":"Informe a fabrica devolução",
    "validacaoFalhaDoFornecedorDoEquipamentoOuMaterial":"Informe se houve Falha do Fornecedor do Equipamento ou Material",
    "validacaoFalhaNaComunicacaoInternaVerbalOuOutros":"Informe se houve Falha na comunicação interna (verbal ou outros)",
    "validacaoFalhaNosMecanismosDeDetecçãoDeFalhas":"Informe se houve Falha nos Mecanismos de Detecção de Falhas",
    "validacaoFaltaDeAtencaoAosDetalhes":"Informe se houve falta de atenção aos Detalhes",
    "validacaoFaltaDeProcedimento":"Informe se houve Falta de Procedimento",
    "validacaoFaltaDeReciclagemPeriodica":"Informe se houve Falta de reciclagem periódica",
    "validacaoGanhosNaoMensurados":"Informe os resultados alcançados",
    "validacaoGrupoClassificacaoContabil":"Informe Grupo Classificação Contábil",
    "validacaoHoraDeFabricacao":"Informe a hora de fabricação",
    "validacaoHoraDeOcorrencia":"Informe a hora de ocorrência",
    "validacaoInadequadaSupervisao":"Informe se houve Inadequada supervisão",
    "validacaoIncendioOuExplosaoExterna":"Informe se houve Incêndio ou explosão externa",
    "validacaoInformeAEtapaParaQualDesejaDevolver":"Informe a etapa para qual deseja devolver",
    "validacaoInformeCategoria":"Informe a categoria",
    "validacaoInformeJustificativaDeReprovacao":"Informe a Justificativa de Reprovação",
    "validacaoInformeSeDesejaAprovar":"Informe se deseja aprovar",
    "validacaoInstalacoesInadequadas":"Informe se houveram Instalações inadequadas",
    "validacaoInterfaceHomemMaquinaInadequadas":"Interface homem-máquina inadequadas",
    "validacaoInvestimentoDoProjeto":"Informe o Investimento do Projeto (em Reais)",
    "validacaoManutencaoDasInstalacoesAusenteOuInadequada":"Informe se houve Manutenção das instalações ausente ou inadequada",
    "validacaoMaterialDefeituoso":"Informe se o material está defeituoso",
    "validacaoMaterialDeSuporteInadequado":"Informe se houve Material de suporte inadequado",
    "validacaoMetodologiaInadequada":"Informe se houve Metodologia inadequada",
    "validacaoMotivoCorrecao":"Informe o Motivo de Correção",
    "validacaoNaoExistemDadosCadastrados":"Não existem dados cadastrados",
    "validacaoNaoFoiFornecidoOTreinamento":"Informe se Não foi fornecido o treinamento",
    "validacaonidadeDoProjeto":"Informe a Unidade do Projeto",
    "validacaoNomeDoProjeto":"Informe o Nome do Projeto",
    "validacaoOrganizacaoDoTrabalhoInadequada":"Informe se houve Organização do trabalho inadequada",
    "validacaoOutrasEconomiasMensais":"Informe saving mensal gerado (em Reais, não vinculado a perda de latas ou tampas)",
    "validacaoOutrosFatoresHumanos":"Informe se houveram Outros fatores humanos",
    "validacaoOutroTipoDeDocumento":"Informe o Outro Tipo de Documento",
    "validacaoParecerDaAreaExterno":"Informe o Parecer da Área (externo)",
    "validacaoParticipante":"Selecione o participante",
    "validacaoPerdaAntesDaInovacao":"Informe a Perda Antes da Inovação (latas/tampas por minuto)",
    "validacaoPerdaDepoisDaInovacao":"Informe a Perda Depois da Inovação (latas/tampas por minuto)",
    "validacaoPlanejamentoDoTrabalhoInadequado":"Informe se houve Planejamento (do trabalho) inadequado",
    "validacaoPoliticaNaoAdequadamenteDefinidaDisseminadaOuRreforcada":"Informe se houve Política não adequadamente definida, disseminada ou reforçada",
    "validacaoPorQue1":"Informe o Por quê 1",
    "validacaoPorQue2":"Informe o Por quê 2",
    "validacaoPorQue3":"Informe o Por quê 3",
    "validacaoPraticaInsuficienteDuranteOTreinamento":"Informe se houve Prática insuficiente durante o treinamento",
    "validacaoPrensaMatriz":"Informe Prensa/Matriz",
    "validacaoProcedimentoNaoClaroAmbiguoOuIncompleto":"Informe se o Procedimento Não Claro, Ambíguo ou Incompleto",
    "validacaoProjeto":"Informe o Projeto",
    "validacaoQual":"Informe Qual",
    "validacaoQuantidadeASerRessarcidaEmLata":"Informe a Quantidade a ser ressarcida em lata",
    "validacaoQuantidadeASerRessarcidaEmTampa":"Informe a Quantidade a ser ressarcida em tampa",
    "validacaoQuantidadeAutorizadaDevolver":"Informe a Quantidade Autorizada a Devolver",
    "validacaoQuantidadeDevolvida":"Informe a Quantidade Devolvida",
    "validacaoResposta":"Informe uma resposta",
    "validacaoRessarcimento":"Possui Ressarcimento?",
    "validacaoRouboAssaltoVandalismo":"Informe se houve Roubo, assalto, vandalismo",
    "validacaoSelecioneATurma":"Informe a turma",
    "validacaoSolucoesImplementadas":"Informe as Soluções Implementadas",
    "validacaoStatus":"Informe o Status",
    "validacaoSupervisorResponsavel":"Informe o supervisor responsável",
    "validacaoSuprimentoDeEnergiaOuAguaInadequados":"Inform se houveram Suprimento de energia ou água inadequados",
    "validacaoTipoDeDocumento":"Informe o tipo de documento",
    "validacaoTipodeProjeto":"Informe o Tipo de Projeto",
    "validacaoTraducaoDoFato":"informe a Tradução do Fato",
    "validacaoUnidadeDoParticipante":"Selecione a unidade do participante",
    "validacaoValorDoFrete":"Informe o Valor do Frete",
    "validacaUnidadeOndeProjetoFoiDesenvolvido":"Informe a unidade onde o projeto foi desenvolvido",
    "validaCodigoDoProduto":"Informe o Código do Produto",
    "labelHistoricoDeAprovacoes":"Histórico de Aprovações",
    "labelAguardandoDispatch":"Aguardando dispatch",
    "labelAguardandoAprovacao":"Aguardando aprovação",
    "labelAprovado":"Aprovado",
    "labelReprovado":"Reprovado",
    "labelLogar":"Entrar",
    "labelCPF":"CPF",
    "labelSenha":"Senha",
    "validacaoUsuario":"Digite seu usuário.",
    "validacaoSenha":"Digite sua senha.",
    "labelEsqueciSenha":"Esqueceu sua senha?",
    "labelEsqueciSenha1":"Esqueceu sua senha",
    "labelContinuarLogado":"Continue logado",
    "labelNovaConta":"Criar uma conta",
    "labelPrecisaNovaConta":"Precisa de uma conta ?",
    "labelResetPassword":"Redefinir senha",
    "placeUsuario":"Informe seu CPF.",
    "labelLembreiSenha":"Lembrei-me minha senha!",
    "labelMatricula":"Matrícula",
    "placeMatricula":"Informe sua matrícula",
    "validacaoMatricula":"Informe sua matrícula.",
    "labelDataNascimento":"Data de Nascimento",
    "validacaoDataNascimento":"Informe sua data de nascimento.",
    "labelValidarInformacoes":"Validar Informações",
    "labelChangePassword":"Alterar senha",
    "labelInfoUsuario":"Digite uma nova senha para ",
    "labelNewPassword":"Nova senha",
    "validacaoNewPassword":"Digite sua nova senha.",
    "labelConfirmNewPassword":"Confirmar nova senha",
    "validacaoConfirmNewPassword":"Confirme sua nova senha.",
    "validacaoPasswordsNotMatch":"As senhas não coincidem.",
    "labelPossuiRegistro":"Já está registrado?",
    "labelContinuar":"Continuar",
    "labelCNPJ":"CNPJ",
    "labelEmail":"E-mail",
    "labelEmailNFE":"E-mail NFE",
    "labelEmailRecuperacao":"Por favor insira o endereço de e-mail para recuperar senha",
    "labelE":"E",
    "labelLogin": "Login",
    "labelRecuperarSenha":"Recuperar Senha",
    "validacaoMotivo":"Informe o Motivo",
    "labelNomeRepresentante":"Nome do Representante",
    "placeNomeRepresentante":"Nome do Representante",
    "validacaoNomeRepresentante":"Informe o Nome do Representante",
    "labelResumoOcorrencia":"Resumo da Ocorrência",
    "placeResumoOcorrencia":"Resumo da Ocorrência",
    "validacaoResumoOcorrencia":"Informe o Resumo da Ocorrência",
    "validacaoDataAutorizacaoDevolucao":"Informe a data de autorização devolução",
    "labelCPM":"CPM",
    "tituloSemCadastroDePontos": "Cadastro de pontos ausente",
    "msgSemCadastroDePontos":"Entrar em contato com o Lean Corporativo (leaninforma@rexam.com)",
    "labelNovaAcao": "Nova Ação",
    "placeCausas": "Informe uma causa",
    "validacaoCausas": "Informe uma causa",
    "labelAcaoCorrespondente": "Ação Correspondente",
    "placeAcaoCorrespondente": "Informe a ação correspondente",
    "validacaoAcaoCorrespondente": "Informe a ação correspondente",
    "placeResponsavel": "Informe o responsável",
    "validacaoResponsavel": "Informe o responsável",
    "labelPrazo": "Prazo",
    "validacaoPrazo": "Informe o Prazo",
    "labelPrazoExecucao": "Prazo de Execução",
    "labelAcao": "Ação",
    "labelPlanoDeAcao": "Plano de Ação",
    "labelEtapaAnaliseInicial": "Análise Inicial e Ações Imediatas",
    "labelEtapaPlanoDeAcao": "Plano de Ação e Conclusão",
    "labelCodigoPlanoAcao": "Código Plano de Ação",
    "labelUrlCodigoPlanoAcao": "Url Plano de Ação",
    "placeCodigoPlanoAcao": "Informe o Código Plano de Ação",
    "validacaoCodigoPlanoAcao": "Informe o Código Plano de Ação",
    "obsCbuBancos":"(Obrigatório apenas para Argentina e Peru)",
    "labelPedirCorrecaoSolicitante":"Enviar para revisão do solicitante",
    "validacaoContencao":"Informar a Contenção",
	"optionLatas":"Latas",
	"optionTampas":"Tampas",
	"labelAcaoDeDeteccao":"Ação de Detecção - Por que o defeito não foi detectado e segregado internamente?",
	"placeAcaoDeDeteccao":"Ação de Detecção - Por que o defeito não foi detectado e segregado internamente?",
    "labelNumeroDoDocumento":"Número do documento",
    "placeNumeroDoDocumento":"Número do documento",
    "excelSaudeSeguranca":"Saúde e Segurança",
    "excelMeioAmbiente":"Meio Ambiente",
    "excelSegurancaAlimentos":"Segurança de Alimentos",
    "excelTituloAnexo":"ANEXO - AÇÃO CORRETIVA E PREVENTIVA (RESPOSTA DE RECLAMAÇÃO DE CLIENTE)",
    "excelDadosDescricao":"00 - DADOS E DESCRIÇÃO DA OCORRÊNCIA (Reclamação de Cliente)",
    "excelDefeitoReclamado":"Defeito Reclamado:",
    "excelCodLataTampa":"Cód. Lata-Tampa (nº lote):",
    "excelDataOcorrencia":"Data da Ocorrência:",
    "excelDataFabricacao":"Data Fabricação:",
    "excelNotaFiscal":"Nota Fiscal:",
    "excelQuantidadeReclamadaRetida":"Qtde Reclamada - Retida:",
    "excelDescricaoDesvio":"Descrição do desvio relatado pelo cliente:",
    "excelTraducaoFato":"Tradução do fato: (constatação após atendimento Ball)",
    "excelNotasRelevantes":"Notas Relevantes: (máquina, área, processo, complemento da origem da falha, etc)",
    "excelPreenchidoPor":"Preenchido por:",
    "excelDataPreenchidoPor":"Data:",
    "excelAcaoContencaoDeteccao":"01 - AÇÃO DE CONTENÇÃO E DETECÇÃO",
    "excelAcaoContencao":"Ação de Contenção:",
    "excelAcaoDeteccao":"Ação de Detecção:",
    "excelConfirmacaoCausas":"02 - CONFIRMAÇÃO DAS CAUSAS REAIS/POTENCIAIS E DEFINIÇÃO DE AÇÕES",
    "excelConfirmacaoAcao":"AÇÃO:",
    "excelConfirmacaoResponsavel":"RESPONSÁVEL:",
    "excelConfirmacaoPrazo":"PRAZO:",
    "excelConclusao":"03 - CONCLUSÃO",
    "excelConclusaoParecerProcedencia":"PARECER: (PROCEDÊNCIA)",
    "excelConclusaoComentarios":"COMENTÁRIOS:",
    "excelConclusaoRessarcimento":"RESSARCIMENTO? (S/N)",
    "excelConclusaoDevolucao":"DEVOLUÇÃO? (S/N)",
    "excelConclusaoQuantidadeAutorizadaRessarcimento":"Qtde. autorizada a ser ressarcida:",
    "excelConclusaoQuantidadeAutorizadaDevolvida":"Qtde. autorizada a ser devolvida:",
    "liSalvarRascunho":"Salvar Rascunho",
    "liExportarExcel":"Exportar Excel",
    "excelTitulo":"TÍTULO",
	"LabelDigito":"Dígito"

}






